### ISSUE TITLE
ugrep --pretty --save-config produce invalid config file

### ISSUE THREAD

**Issue by gaeulbyul** [Genivia/ugrep#101]
Steps to reproduce:
-----

1. run `ugrep --pretty --save-config`
2. run any ugrep command

Actual result:
-----

1. ugrep shows following error message:

> ugrep: invalid option --name, did you mean --neg-regexp, --not, --no-any-line, --no-binary, --no-bool, --no-byte-offset, --no-color, --no-confirm, --no-decompress, --no-dereference, --no-dotall, --no-empty, --no-filename, --no-group-separator, --no-heading, --no-hidden, --no-ignore-binary, --no-ignore-case, --no-ignore-files --no-initial-tab, --no-invert-match, --no-line-number, --no-only-line-number, --no-only-matching, --no-messages, --no-mmap, --no-pager, --no-pretty, --no-smart-case, --no-sort, --no-stats, --no-ungroup or --null?

2. `.ugrep` file contains...

```
# Enable/disable decompression and archive search, default: no-decompress
no-decompress

# Enable/disable ignore files, default: no-ignore-files
no-ignore-files

### OUTPUT ###

# Enable/disable sorted output, default: no-sort
name
```

Looks like the last line (`name`) in config file is invalid to ugrep.

**Comment by genivia-inc** [comment]
Whoops. Good catch! The `sort=` part is missing. Fixed in v3.1.6.
