### ISSUE TITLE
Wish: correct cpu feature detection at runtime - issue with AMD Phenom II

### ISSUE THREAD

**Issue by leahneukirchen** [Genivia/ugrep#103]
As a distro maintainer, I have to build ugrep with `--disable-avx`, because else it fails on a AMD Phenom II with "illegal instruction". But I think ugrep inspects cpuid already, so could it only use AVX when it's actually available?

**Comment by genivia-inc** [comment]
Thank you for your feedback. There are two CPU checks, one at compile time and one at runtime. You can see the check results with option `-V` as you probably already tried.

The runtime check uses the common `cpuidex` instruction. Registers are checked for AVX2 capability.

The `cpuidex` is set in `lib/input.cpp`, the inline check def is in `include/reflex/input.h` and the actual test is in `lib/matcher.cpp`.

The compiler may produces AVX2 instructions when the code is compiled with `-mavx2`, which could cause problems even when the runtime test fails but that should not happen when you run ugrep on the same machine as the one it was build on.

I will investigate.

**Comment by genivia-inc** [comment]
I suppose what happens in your case is that C++ happily compiles AVX2 instructions on the native machine arch, meaning that the C++ check performed in `configure` accepted AVX2 instructions when the machine actually does not support it. Consider this AVX2 test program:
~~~
#include <immintrin.h>
volatile int m;
int main()
{
  __m256i n = _mm256_set1_epi8(42);
  m = _mm256_movemask_epi8(_mm256_and_si256(n, n));
}
~~~
If the above code compiles, e.g. with:
~~~
cc -march=native avx2test.c
~~~
then the compiler assumes that the machine natively supports AVX2. There is a problem when the machine actually does not support AVX2. But this should never happen when the compiler is properly configured and installed.

Try running the compiled `a.out` code and see what happens?

**Comment by leahneukirchen** [comment]
Well the building machine has AVX2, but the target machines don't necessarily.
I think the problem is that enabling `-mavx2` in this case results in GCC also generating AVX2 code in other paths that are not guarded by cpuid checks.

However, it doesn't seem to be possible to use AVX2 intrinsics without `-mavx2`, without falling back to hacks like 
https://stackoverflow.com/a/21372620

I guess I'll just stick to SSE2 for now.

(Phenom II doesn't have AVX2, that's why there are errors. ;))

**Comment by leahneukirchen** [comment]
Just wrapping the headers is not enough however. One would need to split matcher.cpp into separate compilation units and then use `-mavx2` for them (as needed).

**Comment by genivia-inc** [comment]
I know. Fortunately this works with Visual Studio C++ which only compiles the SSE/AVX2 guarded parts of the code. Therefore ugrep.exe works for many CPUs that may have or not have SSE/AVX2. But not so for gcc/clang that require `-mavx2` and optimize all of the code as such. That's why Homebrew for MacOS for example builds executables for all MacOS machine configs separately. IMO that seems to be the only viable approach or disable AVX2 altogether.

**Comment by genivia-inc** [comment]
Ugrep v3.3.5 now performs a runtime check to enable AVX2 and AVX512BW when the machine supports these extensions. Fallback is SSE2, which is widely supported. See issue #143 for more info.

**Comment by leahneukirchen** [comment]
Great, thank you!
