### ISSUE TITLE
Can ugrep be used as a library?

### ISSUE THREAD

**Issue by xaljer** [Genivia/ugrep#107]

**Comment by genivia-inc** [comment]
The [RE/flex](https://github.com/Genivia/RE-flex) library is at the center of ugrep. A smaller [ugrep example](https://github.com/Genivia/RE-flex/blob/master/examples/ugrep.cpp) is included with RE/flex to demonstrate how.

Hope this helps.

**Comment by xaljer** [comment]
@genivia-inc Thanks.
