### ISSUE TITLE
When running ugrep.exe under Windows10 an error messages: "not compatible to 64 bit Version of Windows" occur

### ISSUE THREAD

**Issue by jerik** [Genivia/ugrep#11]
Steps: 
1. Downloaded ugrep.exe from Die Version von C:\Users\foo\bin\ugrep.exe ist mit der ausgeführten Windows-Version nicht kompatibel.  (Release 1.6.3)
2. Placed in a location which is in the PATH
3. Run the exe: 
```
C:\Users\foo>ugrep
Die Version von C:\Users\foo\bin\ugrep.exe ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software.
```
Translation of the error Message

> The version of C:\Users\foo\bin\ugrep.exe is not compatible with the running Windows version. Check the computer's system information, and then contact the publisher of the software.

Edition: Windows 10 Enterprise
Version: 1809
OS-Build: 17763.864

*How can I get ugrep to run on windows 10?*

**Comment by genivia-inc** [comment]
The executable runs on my windows 10 machine, so I suppose its a configuration on your machine that prevents running the executable. I'll create a x64 version.

**Comment by genivia-inc** [comment]
The updated master branch (not the release) now has `bin/win32` and `bin/win64` directories with the x86 and x64 executables. Let me know if this works for you.

**Comment by jerik** [comment]
Thanks. I used `ugrep.exe` from the master branch folder win64. I still get the error message. When I run it in the powershell, ist more verbose. 


```
PS C:\Users\foo> ugrep
Fehler beim Ausführen des Programms "ugrep.exe": Die angegebene ausführbare Datei ist keine gültige Anwendung für
diese Betriebssystemplattform.In Zeile:1 Zeichen:1
+ ugrep
+ ~~~~~.
In Zeile:1 Zeichen:1
+ ugrep
+ ~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```


Translated

```
PS C:\Users\foo> ugrep
Error running the ugrep.exe program: The specified executable file is not a valid application for
this operating system platform.in line:1 character:1
+ ugrep
+ ~~~~~.
In line:1 character:1
+ ugrep
+ ~~~~~
    + CategoryInfo : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

```

**Comment by genivia-inc** [comment]
Just to make sure, I downloaded the master branch and executed both win32 and win64 versions of ugrep.exe on a windows 10 machine with Command and Powershell. But I don't get an error. This is built with MSVC++ 2015 as a stand-alone MT console application (no DLLs necessary).

Make sure to execute `ugrep\bin\win64\ugrep.exe` and not something else. I think that's happening in your case. You can copy the exe file to a place on the execution path, e.g. 
go to *Settings* and search for *path*, then edit *environment variables* -> *Path* and add the directory `c:\<fill this in>\ugrep\bin\win32`.

**Comment by genivia-inc** [comment]
Please try the 1.6.5 release `bin/win64/ugrep.exe`, which is built with VS2017 with the latest updates.

**Comment by jerik** [comment]
It's working. And I it was working before as well. I tested it with the v.1.6.5 win32 and win64 and the 1.6.3 windows versions, all are working. 

It was a "owing to unfortunate circumstances" that it was not running in the beginning. I downloaded the ugrep.exe from https://github.com/Genivia/ugrep/tree/v1.6.3/bin/windows with right click on the ugrep.exe link. Google Chrome downloaded it as ugrep.exe which I executed with the desribed error message. 

But behind the [ugrep.exe](https://github.com/Genivia/ugrep/blob/v1.6.3/bin/windows) is a webpage. So I downloaded the html-page which was stored as ugrep.exe through Google Chrome. This could not work... 

Downloading from https://github.com/Genivia/ugrep/blob/v1.6.3/bin/windows/ugrep.exe through the [raw](https://github.com/Genivia/ugrep/blob/v1.6.3/bin/windows/ugrep.exe?raw=true) link the correct binary will be downloaded and it works like desired. 

cheers -- jerik

**Comment by genivia-inc** [comment]
I've updated the Windows versions of `ugrep.exe` to support options `-P` (Perl matching) and `-z` (decompress/unarchive). Also globbing wasn't properly enabled in the previous version of `ugrep.exe`, which works like a charm now in version 1.6.7.

Enjoy!
