### ISSUE TITLE
Add Deb Package to Ubuntu Repo

### ISSUE THREAD

**Issue by kdrypr** [Genivia/ugrep#110]
Hi,

Can you add deb package into ubuntu repo?

**Comment by genivia-inc** [comment]
Does this answer your question?
https://launchpad.net/ubuntu/+source/ugrep
There is also a similar question with an answer here:
https://askubuntu.com/questions/1268964/ugrep-ppa-snap-or-flatpack

**Comment by kdrypr** [comment]
Yes it is the answer to my question. Thank you.
