### ISSUE TITLE
-g does not work

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#12]
Hi
for 1.6.8
$ ugrep Hji -g file.txt - nothing
for 1.6.7 - everything is good
Thanks.
P.S.
tested on macOS, case sensitive.

**Comment by genivia-inc** [comment]
If you use `-g` without specifying files in 1.6.8 then recursive search is auto-enabled, which is nice. This should match the files in the working directory.

Use option `--stats` to get a report on what files are included or excluded from searches.

Version 1.6.9 has a fix for the missing char `f` that gets stripped from `-g file.txt`.
