### ISSUE TITLE
Combining patterns with different matching modes using boolean operators

### ISSUE THREAD

**Issue by trantor** [Genivia/ugrep#120]
Hello.
I've been using ugrep to perform fuzzy matching on source code to look for misspellings of certain words. However I would also like  to exclude a few candidates, such as the correct spellings, to leave only the ones I am interested in.
From I can gather from the documentation, it's not possible to mix and match, for instance, a fuzzy match with a fixed string match using boolean operators to combine them.
Am I correct? Is it a possible improvement for the tool?

Thanks in advance :)

**Comment by genivia-inc** [comment]
You can exclude certain words with boolean operators and with "negative patterns" `-N PATTERN` such as `-N correct` which is ignored in the input (essentially, negative patterns become invisible to the matcher).

However, boolean patterns and negative patterns are also "fuzzyfied" with option `-Z` and may match more than just the specified word, such as a misspelled `corect` in this example.

Instead, you could pipeline two ugrep: `ugrep <mispelled words> | ugrep -v <correct spelled words>' where the second ugrep finds all lines that DO NOT contain correctly spelled words. Not sure what kind of pipelined matching logic would work for your scenario.

**Comment by trantor** [comment]
Thanks @genivia-inc .
I encountered precisely the problem you described.
I thought about the chained `ugrep`s, however that would mostly work if operating on a single file, instead of a source tree, which is my use case. Hence my idea of restricting the "matching mode" (not sure if that's the right way to call it) per pattern instead of globally affecting all of them.
Since you confirmed my understanding, could you take the above suggestion as a RFE for future development?
Thanks a lot

**Comment by genivia-inc** [comment]
I wish it was that easy to implement, since I would probably have done that already. The matching engines are not hot-swappable internally.

The only way this could be done is by extending the fuzzy regex engine to support fuzzy match distances _per sub-pattern_. This in turn requires an extension of the regex syntax to _specify the max fuzzy match distance with the sub-pattern_ as a hint to the fuzzy regex engine. This regex syntax extension for fuzzy matching does not yet exist in any fuzzy regex matcher, I believe, but I could be wrong.

**Comment by genivia-inc** [comment]
Don't get me wrong, I would love to have a feature like this but it adds significant complexity and requires significant changes to the ugrep internals. Perhaps I will revisit this later in the future if there is a demand for it.

I may be wrong, but I believe your use case is specific to your requirements, which can be met in other ways by running a script to traverse the directory trees to perform fuzzy and non-fuzzy searches with one or more ugrep instances. Another approach is to "fuzzify" a pattern with extra `?` to make parts of the pattern optional.
