### ISSUE TITLE
ugrep hyphen semantics

### ISSUE THREAD

**Issue by essays-on-esotericism** [Genivia/ugrep#125]
Hello,

I've been experimenting with ugrep recently, and I discovered some unexpected behaviour that diverges from all the other grep utilities I've tested against.

The grep implementations I tested on my OpenBSD  machine were ugrep 3.1.11, ripgrep 12.1.0, GNU grep 3.4 and the default BSD grep that comes with the OpenBSD base system.

It appears that the handling of double hyphens "--" in conjunction with using a single hyphen '-' as an explicit directive to read from stdin differs between ugrep and the other grep implementations.

Here's an example of what I'm talking about:

	$ echo "-12345" | grep -Fx -- '-12345' -

When the above snippet is run with the other grep implementations, it works as expected with the single hyphen being taken as an explicit directive to read from stdin.

When the above snippet is run with ugrep, the single hyphen is treated as a literal file name, and thus throws an error about the non-existant file.

I'm not sure if this is a bug or a feature, so I just  thought I'd share this observation.

Regards,

Jordan

**Comment by genivia-inc** [comment]
Thanks for the feedback. This looks like a bug with the interpretation of the single hyphen `-` after `--`. Should be easy to fix!

**Comment by genivia-inc** [comment]
Line 4707 in src/ugrep.cpp:
~~~
else if (options && strcmp(arg, "-") == 0)
~~~
should be
~~~
else if (strcmp(arg, "-") == 0)
~~~
This works now:
~~~
echo 'abc-def' | ugrep -- '-def' -
~~~

**Comment by essays-on-esotericism** [comment]
Wow, that was fast -- thanks for your excellent work!
