### ISSUE TITLE
`ugrep -I` does not recognize `.vdi` images as binary to skip

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#126]
`.vdi` files start with `<<< Oracle VM VirtualBox Disk Image >>>\n\0\0\0\0...`

_Probably `grep` does not recognize them either, but you are trying to build a better product_ 😀

**Comment by genivia-inc** [comment]
The "binary file" checking is performed on the first 16K of input, unless the input is piped to ugrep then the first line of input is checked only (to ensure performance in that case, e.g. especially for piping `tail -f | ugrep`).  If there are any NUL (`\0`) or invalid UTF then the file is considered "binary". So I don't understand this problem here.

**Comment by genivia-inc** [comment]
I tried this with a .vdi file, but cannot replicate the problem:
~~~
$ ugrep -I -l 'Virtual' Win3.1.vdi 
$ ugrep -l 'Virtual' Win3.1.vdi
Win3.1.vdi
~~~
Also PDF files also start with a line of text "%PDF-1.3". This is what I get for the standard tests when installing ugrep, to make sure ugrep works as expected:
~~~
$ ugrep -I -l 'PDF' tests/Hello.pdf
$ ugrep -l 'PDF' tests/Hello.pdf
tests/Hello.pdf
$ ugrep -I 'PDF' tests/Hello.pdf
$ ugrep 'PDF' tests/Hello.pdf
%PDF-1.3
<< /ProcSet [ /PDF /Text ] /ColorSpace << /Cs1 7 0 R >> /Font << /TT1 8 0 R
(Mac OS X 10.12.6 Quartz PDFContext)
~~~
Works like a charm. Perhaps you're using some other options?

**Comment by stdedos** [comment]
This seems to have been a dud 😕

I have updated to the latest version (for the #127), and it has disappeared as expected.

**Comment by stdedos** [comment]
Although ... it seems that `ugrep` has somehow trashed my RAM/SWAP.
Luckily (?) it was not a serious problem - I just got alarms from my server-monitoring software.

62.6G+2.04G were filled up completely - and after `ugrep` exited, I was left with ~8G-9G of resident RAM, swap was 2.04G/2.04G full, and the rest was caches 😂

**Comment by genivia-inc** [comment]
That is good to know and thanks for checking.
