### ISSUE TITLE
zstd compression - file extension tzst

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#129]
Hi
Please add support for files with tzst extension. This is a short version of *.tar.zst
Thanks.

**Comment by genivia-inc** [comment]
It seems to the official extension now, according to Wikipedia https://en.wikipedia.org/wiki/Tar_(computing), so will add support for the short .tzst suffix in the next minor update.

**Comment by genivia-inc** [comment]
To support the .tzst short suffix for .tar.zst is a very small change to the code in `src/zstream.hpp` function`is_zstd()` to add the `.tzst` suffix. That's it.

Let's also add zstd to the advanced zip decompression methods. The bzip, lzma, and xz WinZip .zipx formats are already supported. Zip files compressed with advanced compression methods may use the .zipx suffix (also already supported).

**Comment by genivia-inc** [comment]
Added `.tzst` to ugrep v3.2.1
