### ISSUE TITLE
ugrep and symbolic link

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#13]
Hi
the folder contains a symbolic link to the file file.txt
file.txt contains the word "text", without quotes
ugrep -Rl '' and ugrep -rl ''
no file.txt in output
ugrep -ttext -R text, ugrep -r -ttext text
nothing
maybe I'm doing something wrong?
Thanks.

**Comment by genivia-inc** [comment]
Thanks for the feedback.

Sorry for the problem. A recent release changed the logic a bit to increase the performance, but that caused symlink dereferencing to fail when DIRENT is supported.

I'll release an update asap.

Global function `void find()` should be patched.  The if-condition that checks for symlink directories or files should be slightly modified as follows:
~~~
void find(...
  if (*basename == '.' && flag_no_hidden)
    return;
#ifdef OS_WIN
  ...
#else 
  struct stat buf;
  ...
      // if we got a symlink, use stat() to check if pathname is a directory or a regular file
      if ((type != DIRENT_TYPE_UNKNOWN && type != DIRENT_TYPE_LNK) || stat(pathname, &buf) == 0)
~~~

Thanks for reporting this. I have a bunch of unit tests, but it missed checking this regression issue. This should not happen again.

Besides this fix, the upcoming release adds some powerful new features!

**Comment by genivia-inc** [comment]
Version 1.7.0 is released with a fix. This update also includes new features.
