### ISSUE TITLE
--tag not tagging all results

### ISSUE THREAD

**Issue by hanyfarid** [Genivia/ugrep#131]
This is an excellent tool. Thank you.

On the file test.txt consisting of:
     lorem ipsum lorem

running the command
     ugrep -H  lorem --tag  test.txt

returns:
     test.txt:___lorem___ ipsum lorem

Its looks like the tag is only working on the first instance. On the other hand, the -color=always seems to work just fine.

**Comment by genivia-inc** [comment]
Thanks for the feedback! That's an odd problem. Will get this fixed asap.
