### ISSUE TITLE
Missing matches with \s\s patterns

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#132]
Yet another one of your favorite issues 😀

```console
u@h:/var/log/apt$ grep -zTrniP '\s\s11:04'
u@h:/var/log/apt$ grep -zTrnP '\s\s11:04'
history.log:    80:	End-Date: 2021-05-12  11:04:53
term.log:  1877:	Log ended: 2021-05-12  11:04:53
u@h:/var/log/apt$ 
```

I am looking for an apt-get operation in some midnight hours (original regex was `\s\s00:1`).
As a force of habit, all of my recursive regexes are done via `-Trin` flags, and then padded as needed.

However, it seems somehow the `-i` flag interferes with the matching process - even though there is no alpha-characters on the regex!

ugrep 3.2.1

**Comment by genivia-inc** [comment]
Interesting. The issue is the `\s` in a pattern with option `-P`. Pattern `\h` (space/tab) is OK. The `\s` pattern needed to be changed recently to prevent matching `\n`, perhaps that screwed up something else with `-P`?

**Comment by genivia-inc** [comment]
Found the issue in the recent update that was made to avoid `\s` from matching `\n`. With options `-PU` the pattern `\s\s` is not fully translated to `[\x09\x0b-\x0d\x20][\x09\x0b-\x0d\x20]`. Same problem without `-U` (but larger Unicode spacing pattern). Line 1285 in `lib/convert.cpp` should be `loc = pos + 1;` not `loc = ++pos;`. A subtle difference!

**Comment by stdedos** [comment]
Glad to know that this is now getting fixed (and possibly a system test case? 😄)

**Comment by genivia-inc** [comment]
Fixed. I've verified the test cases. I should have noticed this problem earlier in the tests. It flew under the radar because the tests were updated too. Should avoid updating several things at once, especially when test cases are added.

**Comment by stdedos** [comment]
It might be easier to everyone (and you) if you do piece-wise commits, instead of the one-commit-tag-release cycle you are following here 😀
