### ISSUE TITLE
ugrep: error: error in regex: lookbehind assertion is not fixed length

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#135]
Your favorite kind of bug reports (again 😛)

```console
u@h:~ $ xpra displaysds | grep -P '(?<=^\s)\s*xpra'
ugrep: error: error in regex at position 4
(?m)(?<=^(?:\x09|[\x0b-\x0d]|\x20|\xc2\xa0|\xe1\x9a\x80|\xe2\x80[\x80-\x8a]|\xe
    \___lookbehind assertion is not fixed length

u@h:~ $ xpra displaysds | /bin/grep -P '(?<=^\s)\s*xpra'
	xpra 
	xpra start [DISPLAY]
	xpra start-desktop [DISPLAY]
	xpra upgrade [DISPLAY]
	xpra upgrade-desktop [DISPLAY]
	xpra recover [DISPLAY]
	xpra shadow [DISPLAY]
	xpra attach [DISPLAY]
	xpra detach [DISPLAY]
	xpra info [DISPLAY]
	xpra version [DISPLAY]
	xpra stop [DISPLAY]
	xpra exit [DISPLAY]
	xpra clean-sockets [DISPLAY]
	xpra clean-displays [DISPLAY]
	xpra screenshot filename [DISPLAY]
	xpra control DISPLAY command [arg1] [arg2]..
	xpra print DISPLAY filename
	xpra shell [DISPLAY]
	xpra showconfig
	xpra list
	xpra list-sessions
	xpra list-windows
	xpra sessions
	xpra launcher
	xpra gui
	xpra start-gui
	xpra displays
	xpra list-mdns
	xpra mdns-gui
```

**Comment by genivia-inc** [comment]
I'm already working on a complete revision of option `-P` to ensure the native PCRE2 engine is used with minimal conversions applied to the regex. Right now, the regex is converted to support either PCRE2 or Boost.Regex Unicode matching. However, PCRE2 is more powerful than Boost.Regex, so certain Unicode-related conversions are unnecessary with PCRE2. This planned revision also improves option `-w` and patterns such as `\w` that become too big to handle by PCRE2, see #114. Native PCRE2 Unicode matching with `\w` is obviously best.

With respect to `\s`, the pattern is modified to remove `\n` as was discussed before, to prevent multiline matching when we don't want `\s` to match multiple lines. With the revision this will need to be addressed too, keeping the non-newline matching of `\s` intact at least for the "normal" cases.

**Comment by genivia-inc** [comment]
Testing of ugrep v3.3 is progressing well after a major upgrade to revise option `-P`. I've tested the upgrade thoroughly to check if the implementation indeed avoids issues that may hamper the use of PCRE2 with option `-P`, i.e.all PCRE2 regex pattern features should be available. Also `-w` and `-i` are updated for Unicode compliance when option `-P` is used with PCRE2. Patterns `\s` and `[^...]` are modified to exclude `\n` from being matched, which makes ugrep behave like grep but still allows explicit multiple line matching, e.g. using `\n` in patterns.
