### ISSUE TITLE
[FR] Create `tldr` entry for ugrep.

### ISSUE THREAD

**Issue by wookiee** [Genivia/ugrep#137]
[tldr](https://github.com/tldr-pages/tldr) is a popular CLI cheat-sheet tool for users to quickly look up or refresh themselves on how to perform common tasks with other useful tools (such as `ugrep`).

The documentation on `ugrep` is excellent, but when I cannot quite remember an incantation in any given CLI tool, `tldr` is the first thing I try.

I'd love to see a `ugrep` entry for `tldr`.

**Comment by genivia-inc** [comment]
Thank your for the feedback and suggestion! Excellent idea. Will add this to the TODO list.

**Comment by genivia-inc** [comment]
Thanks again for the suggestion. I went ahead to create a [PR](https://github.com/tldr-pages/tldr/pull/7749) to add English, Dutch and German tldr pages for ugrep.

**Comment by wookiee** [comment]
Hey, that's awesome! Thanks!
