### ISSUE TITLE
Question: Suppress matching part in output

### ISSUE THREAD

**Issue by highend** [Genivia/ugrep#146]
Hi,
using v3.3.6 on Windows 10.

I'm using e.g.:
`ugrep.exe -rInki "for i = 1 to" "D:\Test"`

I would only need the `path:line number:column:` part and not the matching part of the search term "for i = 1 to ..." after the last "column:" so:
Is there a native way to suppress the matching part in the search results?

Real world example:
`D:\Test\CalendarNotice.lua:282:9:   for i = 1, numNotices do`
and I only want:
`D:\Test\CalendarNotice.lua:282:9:`

**Comment by genivia-inc** [comment]
Perhaps use `--format` to produce the output you want with `--format='%f:%n:%k:%n'`? See the manual page section `FORMAT` for more details on the `%` fields and online: https://github.com/Genivia/ugrep#format

**Comment by highend** [comment]
Thanks a lot!
`--format='%f:%n:%k:%~`
does exactly what I need :)

**Comment by genivia-inc** [comment]
Oops, yes, the last should be `%~` to produce a newline.

**Comment by highend** [comment]
No problem, I've read that part of the help file (again) to make sure I'm doing it right :)

This is an absolutely incredible tool and by far the best cli one for Windows.
Thanks for creating it! 

I only wished it could not only grep things but also replace them, then it would be also the best cli tool as a sed replacement 👍

**Comment by highend** [comment]
I've stumbled upon a little... thing (don't know if this is a bug or just how it's supposed to work):

The perfect way for Sublime Text to open all files with a match (limited to only the first entry even if there are more matches inside a file) is something like this:
`-rInki -m1 --sort --format="%h:%n:%k%~"`
which should lead to (only one line shown):
`"D:\Test\CalendarNotice.lua":282:9`

but the output of the arguments above is:
`"D:\\Test\\CalendarNotice.lua":282:9`
It doubles the path separator...

Is this the expected behavior?

**Comment by genivia-inc** [comment]
The `%h` field quotes the pathname and escapes special characters (like C/Java/C# etc. to make it suitable to use in code). I'll mention that in the future in the FORMAT section of the manual. To just add quotes, use `"%h"`.

**Comment by highend** [comment]
Ok, thanks for your time, Robert!
