### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#15]
Please  fix it
Archives (.cpio,
.pax, .tar, .zip) and compressed archives (e.g. .taz, .tgz, .tpz,
.tbz, .tbz2, .tb2, .tz2, .tlz, and .txz)

to \&.cpio etc. or only for .pax and .tbz
without this, the page does not show completely.

**Comment by genivia-inc** [comment]
Ah, I see. My automatic `man.sh` generator of man pages does not replace the `.` yet.

**Comment by genivia-inc** [comment]
Adding the following line to `sed` in `man.sh` fixes this:
~~~
-e 's/^\.\([A-Za-z]\)/\\\&.\1/g' \
~~~
This line should appear just before the line
~~~
-e $'s/^    \(.*\)$/.TP\\\n\\1/' \
~~~
to prevent the generated `.TP` from being escaped.
