### ISSUE TITLE
Overlong paths are not supported on Windows

### ISSUE THREAD

**Issue by highend** [Genivia/ugrep#150]
Hi again,

Using v3.3.6

ugrep doesn't support searches in overlong (>= `MAX_PATH`) paths

E.g.:
```
ugrep.exe -i wonderful "R:\@overlong_folder_name\X3XKS9EEKC7648YUFRJ1DNZM6S0HXLMR8TYX9DKK4MM67TP55UJ5M1CSSJ2AQO0N8NVZSJP2VHH6H4L6TARUFZBECMEFPEPWH1DGEQ32EEJVY0X50G0RUE6LFFULYOZMHDAY4T0Q6PJWOEZ78S1IV58IJD4EFF50S2E5ZQQ7RVBXO81G0PNTL6PC8U2J7JG7XIGQ1DKOO9LL0DE4VKMBZDX719FNBX6DF49BAMR8HA8KNQ"
```

Result:
```
ugrep: warning: R:\@overlong_folder_name\X3XKS9EEKC7648YUFRJ1DNZM6S0HXLMR8TYX9DKK4MM67TP55UJ5M1CSSJ2AQO0N8NVZSJP2VHH6H4L6TARUFZBECMEFPEPWH1DGEQ32EEJVY0X50G0RUE6LFFULYOZMHDAY4T0Q6PJWOEZ78S1IV58IJD4EFF50S2E5ZQQ7RVBXO81G0PNTL6PC8U2J7JG7XIGQ1DKOO9LL0DE4VKMBZDX719FNBX6DF49BAMR8HA8KNQ: No such file or directory
```

Even when using an expanded path, it won't work:
```
ugrep.exe -i wonderful "\\?\R:\@overlong_folder_name\X3XKS9EEKC7648YUFRJ1DNZM6S0HXLMR8TYX9DKK4MM67TP55UJ5M1CSSJ2AQO0N8NVZSJP2VHH6H4L6TARUFZBECMEFPEPWH1DGEQ32EEJVY0X50G0RUE6LFFULYOZMHDAY4T0Q6PJWOEZ78S1IV58IJD4EFF50S2E5ZQQ7RVBXO81G0PNTL6PC8U2J7JG7XIGQ1DKOO9LL0DE4VKMBZDX719FNBX6DF49BAMR8HA8KNQ"
```

Result:
```
ugrep: warning: cannot open directory \\?\R:\@overlong_folder_name\X3XKS9EEKC7648YUFRJ1DNZM6S0HXLMR8TYX9DKK4MM67TP55UJ5M1CSSJ2AQO0N8NVZSJP2VHH6H4L6TARUFZBECMEFPEPWH1DGEQ32EEJVY0X50G0RUE6LFFULYOZMHDAY4T0Q6PJWOEZ78S1IV58IJD4EFF50S2E5ZQQ7RVBXO81G0PNTL6PC8U2J7JG7XIGQ1DKOO9LL0DE4VKMBZDX719FNBX6DF49BAMR8HA8KNQ: No error
```

That folder contains two files:
```
Sublime 3 lines.txt
Sublime 5 lines.txt
```

both containing the word `wonderful`

**Comment by genivia-inc** [comment]
Ah, the "beauty" of Windows systems strikes again.

**Comment by highend** [comment]
1. That registry setting ONLY exists for Windows 10, version 1607+. Every other version before (or Windows 8.1. 8, 7, etc.) would fail
2. I just tried it in a VM with Windows 10, version 10.0.19042.572 (20H2)
Set the necessary registry value, rebooted, used the same ugrep calls again

Result: Same error as in the initial posting

**Comment by genivia-inc** [comment]
That could be, but Microsoft is telling us otherwise... just saying that we already follow the recommended API.

According to forum discussions on `MAX_PATH`, this is a common limitation, so even copying files on old Windows systems may not work. So not sure if there is any point of trying to handle long paths on older Windows 7, 8.

**Comment by highend** [comment]
>  just saying that we already follow the recommended API

This is a two-fold process (for Windows 10 v1607+) and looking at the manifest of ugrep.exe it doesn't contain the necessary
```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
```

Here is a minimal bit of test source code for `PureBasic` (because I'm not fond of C++)
```
DisableExplicit

Define.WIN32_FIND_DATA FileData
Define file.s
file = "\\?\C:\@overlong_folder_name\KHGJRFH9L7HGJ14CQ45OQAE2LYUH3D58913V3EMOOUY5ETVSDGKAD1AUP6OOLT2TLV3BDSQITL8L60NEN0HL6FJWDZZOTDVWLWS041KE0ELZF18VNQ8QQVWTL90P9GE6C1E4VIW0A6DFP9DVEI2UKR59GZ3WHFDAT68T5NI0PST4I4W0V8857I3XY0HE0RMW28L8IU80A687E1JZ5U2Q5IIG48GDDUWM53QJGISP29UUWD\Sublime 3 lines.txt"

hFile = FindFirstFile_(file, @FileData)
If hFile <> #INVALID_HANDLE_VALUE
  OutputDebugString_("FindFirstFile: Success")
  FindClose_(hFile)

Else
  OutputDebugString_("FindFirstFile: Error")
EndIf
```
PureBasic uses Unicode internally and function names with an appended underscore call Win32 API functions. In this case, `FindFirstFile_` calls `FindFirstFileW`.

Now for some testing.
01. With the prefix for '\\?\' for `file` and without the manifest
-> Works fine for all Windows versions (Win 7 and above)
02. Without the prefix for '\\?\' for `file` and without the manifest
-> Doesn't work on any Windows version
03. Without the prefix but with the manifest
-> Works fine on Windows 10 v1607+ with the necessary registry entry

As I said I'm not a C++ guy so I didn't check your source but this stuff should work if the prefix is used, even without any manifest and under all Windows versions.

And because `ugrep` is missing the required manifest part it doesn't work under Windows 10 v1607+ with the prefix left out even when the registry entry is set

**Comment by genivia-inc** [comment]
Funny how MS continues to make simple things complicated. Since the time I programmed with 80s MS-DOS, I have mostly abandoned Windows-specific programming, preferring Unix and later Linux and everything with a shell e.g. bash. Love "exotic" OS like Symbian and Palm OS, which are _necessarily_ limited due to resource constraints, as opposed to Windows 10.

I've pulled up the Manifest Tool in MSVC++ to check on the application manifest settings. Quick to figure out.

**Comment by genivia-inc** [comment]
The longPathAware is now added in my dev version. Verified with a ugrep of ugrep.exe to check it's indeed now included in the exe 😀

**Comment by genivia-inc** [comment]
Easy does it: the 3.3.6 release artifact ugrep.exe is updated.

Tested with some `\\?\C:\PATH` queries and everything looks OK.

However, I suspect that we could slap on the `\\?\` prefix for long pathnames automatically in ugrep internally. It looks though that the full path from the root is to be specified after `\\?\`. So relative paths should be converted to absolute paths for this to work.

**Comment by highend** [comment]
> However, I suspect that we could slap on the \\?\ prefix for long pathnames automatically in ugrep internally

Best option^^ Make sure that for UNC (network paths) ``\\?\UNC`` is used :)
