### ISSUE TITLE
Vim CtrlP default command gives error (windows 10)

### ISSUE THREAD

**Issue by kv-gits** [Genivia/ugrep#151]
Setup ugrep command for ctrlp plugin according to readme and getting error 

```invalid escape, error in regex at position 13```

**Comment by genivia-inc** [comment]
Thanks for the feedback. From this it is not clear what the problem could be. I suppose option `-P` should work regardless since it offers a wider range of escape codes than standard regex (POSIX) grep.

**Comment by genivia-inc** [comment]
Ah, I see. The `""` got somehow missing in the `.vimrc` `g:ctrlp_user_command` in the README:
~~~
let g:ctrlp_user_command='ugrep "" %s -l -I -3 --ignore-files'
~~~

**Comment by kv-gits** [comment]
Now works good! Thanks!

**Comment by genivia-inc** [comment]
README updated! Thanks.
