### ISSUE TITLE
Out of tree builds don't work

### ISSUE THREAD

**Issue by ericonr** [Genivia/ugrep#155]
Should be simple to reproduce:

```
$ mkdir build; cd build
$ /path/to/ugrep/configure
$ make
```

Instead of completing successfully, it prints an error:

```
make  all-recursive
make[1]: Entering directory '/tmp/build2'
Making all in lib
make[2]: Entering directory '/tmp/build2/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/build2/lib'
Making all in src
make[2]: Entering directory '/tmp/build2/src'
make[2]: *** No rule to make target '/home/ericonr/mypro/1-small/ugrep/lib/libreflex.a', needed by 'ugrep'.  Stop.
make[2]: Leaving directory '/tmp/build2/src'
make[1]: *** [Makefile:461: all-recursive] Error 1
make[1]: Leaving directory '/tmp/build2'
make: *** [Makefile:361: all] Error 2
```

So there seems to be something wrong with how libreflex is referred to in the build system.

**Comment by genivia-inc** [comment]
> Should be simple to reproduce:
> ```
> $ mkdir build; cd build
> $ /path/to/ugrep/configure
> $ make
> ```
This won't work in the way presented, since `build` is an empty directory. Did you intent to copy the repo there?

**Comment by ericonr** [comment]
No, I am doing specifically an out of tree build. It's a way of avoiding dirtying up the repository itself by building everything in a separate directory. I think most autoconf projects support it, though it's not a huge deal... Just documenting that it isn't supported works just as well for me.

**Comment by ericonr** [comment]
Found this https://stackoverflow.com/questions/1311231/store-gnu-make-generated-files-elsewhere

**Comment by genivia-inc** [comment]
OK. Got it. One line should be changed to make this work properly. In ugrep/src/Makefile.am the correct line is:
~~~
ugrep_LDADD    = $(PTHREAD_LIBS) $(top_builddir)/lib/libreflex.a
~~~
This replaces `top_srcdir` with `top_builddir`. That's pretty obvious.

However, `make test` still fails because the test data and test scripts are in the source `tests` directory. The `tests/verify.sh` script expects `../src/ugrep` to be present, which isn't. Not sure how to address this problem or if this should work too.

**Comment by genivia-inc** [comment]
I figured that a few clever tweaks is all that is necessary to make `make test` work with out-of-tree builds too. The `verify.sh` script is changed to use the `UGREP_TEST_BIN` environment variable that points to the ugrep executable, e.g. when built out-of-tree:
~~~
UGREP=${UGREP_TEST_BIN:-../src/ugrep}

UG="$UGREP --color=always --sort $@"
~~~
I've changed the `Makefile` in the root dir as follows, using `env` to set the `UGREP_TEST_BIN` variable, which is set to the full absolute path to the ugrep executable:
~~~
UGREP = $(shell pwd)/$(top_builddir)/bin/ugrep$(EXEEXT)

test:		${UGREP}
		@echo
		@echo "*** SINGLE-THREADED TESTS ***"
		@echo
		cd $(top_srcdir)/tests && env UGREP_TEST_BIN=${UGREP} ./verify.sh -J1
		@echo
		@echo "*** MULTI-THREADED TESTS ***"
		@echo
		cd $(top_srcdir)/tests && env UGREP_TEST_BIN=${UGREP} ./verify.sh
		@echo
		@echo "OK"
		@echo
~~~
This approach works. I tested it with MacOS, Linux, Cygwin and Android. So I assume it will work with all *nix systems.

**Comment by ericonr** [comment]
Thanks for looking into this! Any idea what's up with my test attempt?

```
*** SINGLE-THREADED TESTS ***

cd /home/ericonr/mypro/1-small/ugrep/tests && env UGREP_TEST_BIN=/tmp/build3/./bin/ugrep ./verify.sh -J1
../config.h not found, exiting
make: *** [Makefile:961: test] Erro 1
```

**Comment by ericonr** [comment]
#156
