### ISSUE TITLE
How to add ANSI escape codes to `--format`?

### ISSUE THREAD

**Issue by NightMachinery** [Genivia/ugrep#157]
I want to put some ANSI escape codes to color and add hyperlinks to `--format`. I have tried `\e[38;2;0;0;100m%f%s%n%~%t%[1]#%~`, `\x1b[38;2;0;0;100m%f%s%n%~%t%[1]#%~`, `\[[38;2;0;0;100m%f%s%n%~%t%[1]#%~`; None of which work.

**Comment by genivia-inc** [comment]
It depends on the shell you use. Bash expands `\e` when used in `$'...'`. For example `echo $'\e[38;2;0;0;100mtest\e[0m'`.

Ugrep does not need to expand control sequences since most shells offer ways to do just that. Try bash:
~~~
$ ugrep --format=$'\e[38;2;0;0;100m%f%s%n%~%t%[1]#%~' ...
~~~
