### ISSUE TITLE
[FR] Make `%b` and `%e` accept `[NUM]` arguments for capture groups

### ISSUE THREAD

**Issue by NightMachinery** [Genivia/ugrep#159]
I.e., `%[1]b` would output the starting byte offset of the first capture group.

**Comment by genivia-inc** [comment]
Should be useful to have. I'll need to take a look at the details of the internals to see if this can work. Perhaps the same could be done with line numbers `%[NUM]n` (multiline matches produce captures at different lines) and column offsets `%[NUM]k`.
