### ISSUE TITLE
Feature Request - larger hex view

### ISSUE THREAD

**Issue by timoc** [Genivia/ugrep#16]
If i am grepping for strings in a binary with the pager, the hex view can break up strings for an in pager refined search (for string associations)

I would like to have the option for a 4 colum hex view, or N colum hex view, so i can use the in pager search to match a larger line.

**Comment by genivia-inc** [comment]
Sounds interesting. Do you mean to stretch the width of the hex view beyond the 16 bytes per line (beyond 80 characters per line)? I'm not sure what you are looking for.

Utilities like `od` offer options to display hex bytes (`-x1`), shorts (`-x2`), or ints (`-x4`), while keeping the columns displayed under 80 chars.

**Comment by genivia-inc** [comment]
Is this what you are looking for? Option `--hex-cols=6` shows 6*8 byes per line:
![image](https://user-images.githubusercontent.com/13117347/73602372-2db13380-4541-11ea-92a0-a9cbaa8a4306.png)

**Comment by genivia-inc** [comment]
Ugrep 1.7.6 has a new option `--hexdump=[1-8][b][c]` to enlarge the hex view up to a wide 8x8 bytes per line. Option `b` removes space breaks and option `c` removes the character column.
