### ISSUE TITLE
Windows: FILE parameter globs not expanded

### ISSUE THREAD

**Issue by idigdoug** [Genivia/ugrep#160]
On Windows, FILE parameters with globs always fail.
```
C:\>ug Hello *
ugrep: warning: *: No such file or directory
```
The shell does not glob the parameters. This is often a good thing, as it means I need to do less escaping for patterns and other parameters, but it is annoying for the FILE parameters.

Ideally, ugrep would perform globbing on the FILE parameters and leave the remaining parameters alone, so I would want the expansion to happen in init after we check for `-Q` and `-e PATTERN`, but before we verify that the FILE parameters exist. I suspect a FindFirstFile-style glob would be appropriate.

I'd be willing to prototype a change if this sounds reasonable.

**Comment by idigdoug** [comment]
Proposed fix: https://github.com/Genivia/ugrep/pull/162

**Comment by genivia-inc** [comment]
I agree that globbing should be universally supported on all platforms, including Windows.
