### ISSUE TITLE
Cyrillic character substitution when processing CP1251 encoded file. 

### ISSUE THREAD

**Issue by Nazim-ua** [Genivia/ugrep#168]
Greetings.
I have a problem when processing a cp1251 encoded file on windows.
Some of the Cyrillic uppercase characters are substituted. 
I detected substitutions by :
A(U+0410)->Ā(U+0100)
Ґ(U+0490)->Љ(U+0409)
There is no substitution in lower case. 

The search command:
ugrep --encoding=CP1251 -iP -e "айблит" test_cp1251.txt >test_cp1251_n.txt
The command to print all text:
ugrep --match --encoding=CP1251 test_cp1251.txt >test_cp1251_n.txt

Text for testing:
Добрый доктор Айболит!
Он под деревом сидит.
Приходи к нему лечиться
И корова, и волчица,
И жучок, и червячок,
И медведица!
Всех излечит, исцелит
Добрый доктор Айболит!

йцукенгшщзхъ\фывапролджэячсмитьбю.ё
ЙЦУКЕНГШЩЗХЪ/ФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,Ё

йцукенгшщзхї\фівапролджєячсмитьбю.ґ
ЙЦУКЕНГШЩЗХЇ/ФІВАПРОЛДЖЄЯЧСМИТЬБЮ,Ґ

**Comment by genivia-inc** [comment]
Thank you for your feedback. It looks like there is a typo in the translation table in `input.cpp`. There are two 0x409 entries and one 0x100 entry in the table.

Will fix this table asap and release an update.

**Comment by genivia-inc** [comment]
Fixed in 3.3.9. The code page tables are initially from Wikipedia, so I wonder what had happened.

**Comment by genivia-inc** [comment]
You're welcome and thanks for reporting this problem!

By the way, I noticed yesterday that someone very recently has been editing almost all Wikipedia pages related to character sets. He removed the Unicode code points from the tables, which makes it quite hard to verify code point table implementations as you can see here for yourself for the CP-1251 code page table: https://en.wikipedia.org/wiki/Windows-1251

Before this change, the character set tables contained useful Unicode code point information that is now gone. I hope this change can be and will be reverted. Perhaps more people will need to explain to this guy that this is not a helpful change, at least not to those that need information to translate code pages to Unicode/UTF-8.
