### ISSUE TITLE
--format have no field to output search pattern in -Z (fuzzy) mode 

### ISSUE THREAD

**Issue by anotatta** [Genivia/ugrep#170]
Although --format has various fields such as %1 or %[NUM]#
there is no field to format the original search pattern when doing search
in fuzzy mode (which precludes -P option).

I tried %0, but the output is the the fuzzy pattern, not the original search pattern.

This is more like a feature request.
Thanks for such a great program.

**Comment by genivia-inc** [comment]
I think I understand what you suggest: to display the regex sub-pattern that belongs to a matched pattern. Option -P provides additional format fields but option -Z does not. The reason for this is that -Z uses POSIX matching like GNU/BSD grep, but with fuzzy pattern matching semantics. There is no Perl matching version of -Z fuzzy matching.

Unfortunately, POSIX matching makes it difficult to track the sub-matches made by a -Z pattern. There is some academic research on the subject of POSIX matching with sub-match extraction that could/should work with -Z. But it that work still lacks some important properties that Perl matching gives you almost for free, such as backreferences that can be very useful to match patterns.

**Comment by anotatta** [comment]
I was thinking along the line of the regex sub-pattern that belongs to the search pattern.
But for fuzzy -Z search, from your explanation I understand now the complexity involved.
Thanks.
