### ISSUE TITLE
README links to Debian package version points only to unstable package

### ISSUE THREAD

**Issue by jonassmedegaard** [Genivia/ugrep#178]
Project README links to newest Debian package - but only newest in the *unstable* branch of the distro.

I recommend to instead use this shorter URI for package versions in all actively maintained distro releases, including the generally recommended *stable* release more meaningful to most users of Debian: https://packages.debian.org/ugrep

**Comment by genivia-inc** [comment]
Thanks for the feedback, much appreciated! The link has been corrected in the README.
