### ISSUE TITLE
Issue with install in wsl ubuntu

### ISSUE THREAD

**Issue by RuneBergh** [Genivia/ugrep#18]
ugrep.cpp: In member function ‘bool Grep::open_file(const char*)’:
ugrep.cpp:2156:10: error: ‘filter’ was not declared in this scope
     if (!filter(file, pathname))
          ^~~~~~
ugrep.cpp:2156:10: note: suggested alternative: ‘file’
     if (!filter(file, pathname))
          ^~~~~~
          file
ugrep.cpp: In member function ‘bool Grep::close_file(const char*)’:
ugrep.cpp:3044:31: warning: unused parameter ‘pathname’ [-Wunused-parameter]
   bool close_file(const char *pathname)
                               ^~~~~~~~
ugrep.cpp: In function ‘void sigint_reset_tty(int)’:
ugrep.cpp:360:5: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     (void)write(1, "\033[0m", 4);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:436: recipe for target 'ugrep-ugrep.o' failed
make[1]: *** [ugrep-ugrep.o] Error 1
make[1]: Leaving directory '/home/rbergh/ugrep/src'
Makefile:456: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

I did not have an issue with WSL and ugrep before.

**Comment by genivia-inc** [comment]
I suppose `zlib` is not installed, which causes `filter` to be absent. I'll resolve this.

**Comment by genivia-inc** [comment]
The master branch is updated. Everything should work now.

Annoyingly there is no easy way anymore to trash return values of functions marked `warn_unused_result`. We can safely ignore the return of `write()` in the signal handler, which is just there to try to reset the terminal colors on SIGINT and it does not matter if the `write()` succeeded or not.

**Comment by RuneBergh** [comment]
Yes indeed, good point, its annoying its no easy way to trash what can safely be ignored. Sorry for the late reply, just got time to try this again. 

I got a series of new errors on WSL in the latest build. I thought it was a permission issue from my end but no amount of sudo would fix it. Hopefully its just a simple user-error from my end, but i dont really see it in this case. 

error.cpp:98:1: fatal error: opening dependency file .deps/libreflex_a-error.Tpo: Permission denied
 } // namespace reflex
 ^
compilation terminated.
posix.cpp:88:1: fatal error: opening dependency file .deps/libreflex_a-posix.Tpo: Permission denied
 }
 ^
letter_scripts.cpp:1305:1: fatal error: opening dependency file .deps/libreflex_a-letter_scripts.Tpo: Permission denied
 }
 ^
Makefile:471: recipe for target 'libreflex_a-error.o' failed
utf8.cpp:279:1: fatal error: opening dependency file .deps/libreflex_a-utf8.Tpo: Permission denied
 } // namespace reflex
 ^
input.cpp:1326:1: fatal error: opening dependency file .deps/libreflex_a-input.Tpo: Permission denied
 } // namespace reflex
 ^
compilation terminated.
compilation terminated.
make[2]: *** [libreflex_a-error.o] Error 1
language_scripts.cpp:11211:1: fatal error: opening dependency file .deps/libreflex_a-language_scripts.Tpo: Permission denied
 }
 ^
compilation terminated.
compilation terminated.
Makefile:527: recipe for target 'libreflex_a-posix.o' failed
block_scripts.cpp:605:1: fatal error: opening dependency file .deps/libreflex_a-block_scripts.Tpo: Permission denied
 }
 ^
unicode.cpp:103:1: fatal error: opening dependency file .deps/libreflex_a-unicode.Tpo: Permission denied
 }
 ^
compilation terminated.
make[2]: *** [libreflex_a-posix.o] Error 1
compilation terminated.
compilation terminated.
Makefile:485: recipe for target 'libreflex_a-input.o' failed
make[2]: *** [libreflex_a-input.o] Error 1
Makefile:541: recipe for target 'libreflex_a-unicode.o' failed
make[2]: *** [libreflex_a-unicode.o] Error 1
Makefile:555: recipe for target 'libreflex_a-utf8.o' failed
make[2]: *** [libreflex_a-utf8.o] Error 1
Makefile:569: recipe for target 'libreflex_a-block_scripts.o' failed
make[2]: *** [libreflex_a-block_scripts.o] Error 1
Makefile:583: recipe for target 'libreflex_a-language_scripts.o' failed
make[2]: *** [libreflex_a-language_scripts.o] Error 1
Makefile:597: recipe for target 'libreflex_a-letter_scripts.o' failed
make[2]: *** [libreflex_a-letter_scripts.o] Error 1
matcher.cpp:644:1: fatal error: opening dependency file .deps/libreflex_a-matcher.Tpo: Permission denied
 } // namespace reflex
 ^
compilation terminated.
Makefile:499: recipe for target 'libreflex_a-matcher.o' failed
make[2]: *** [libreflex_a-matcher.o] Error 1
convert.cpp:1823:1: fatal error: opening dependency file .deps/libreflex_a-convert.Tpo: Permission denied
 } // namespace reflex
 ^
compilation terminated.
Makefile:443: recipe for target 'libreflex_a-convert.o' failed
make[2]: *** [libreflex_a-convert.o] Error 1
pattern.cpp:2882:1: fatal error: opening dependency file .deps/libreflex_a-pattern.Tpo: Permission denied
 } // namespace reflex
 ^
compilation terminated.
Makefile:513: recipe for target 'libreflex_a-pattern.o' failed
make[2]: *** [libreflex_a-pattern.o] Error 1
make[2]: Leaving directory '/home/rbergh/ugrep/lib'
Makefile:456: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rbergh/ugrep'
Makefile:356: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by genivia-inc** [comment]
That stuff happens when executing `sudo make install` before a local `make` was completed because this builds the libs locally as root. Just do a `sudo make clean && make -j && sudo make install`.
