### ISSUE TITLE
Unclear which "BSD grep" is referenced in benchmark table

### ISSUE THREAD

**Issue by emaste** [Genivia/ugrep#186]
Based on context I presume "BSD grep 2.5.1" in the benchmark table is macOS's default /usr/bin/grep, but it's not specified. If this is macOS's grep it would be worth annotating it (e.g. "macOS BSD grep") or adding a note below the table.

I believe this is the the repo Apple uses for "BSD grep": https://github.com/apple-oss-distributions/text_cmds/tree/text_cmds-106/grep
If so this looks like a copy of grep from FreeBSD in 2012; I am unsure if Apple made changes, and there are a lot of bug fixes made in the years since that they're missing.

I tried comparing ugrep against /usr/bin/grep and GNU grep on my FreeBSD laptop and ugrep and GNU grep are about 2.5x as fast.

**Comment by genivia-inc** [comment]
It's the 2.5.1-FreeBSD version on MacOS. It's important to be fair and accurate when comparing performance. So this is already mentioned in the performance table in the README.

**Comment by genivia-inc** [comment]
By the way, I am working on speed improvements for very large `-F` pattern strings as well as improving the speed for some insanely complex regex patterns that produce tens to hundreds of thousands of DFA states. The prototyping is going very well, so I hope to release 3.7 soon.
