### ISSUE TITLE
macOS Illegal instruction: 4

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#19]
Hi
for compiled binary from you
1. macOS versions of ugrep depends on libpcre2-8.0.dylib
please make static pcre2 lib and make ugrep without depends on pcre2 dylib.
2. modify ugrep with install_name_tool -change or add pcre2 dylib to /opt/local/lib and now i have a message:
Illegal instruction: 4
macOS High Sierra.
Regards.

**Comment by genivia-inc** [comment]
I will remove option `-P` from the binaries altogether. It's not the best for usability perhaps, but safe for now. I'll take a look at using the static libraries, but eventually we should create a Mac homebrew formula or macports.

To install pcre2 on Mac, use [macports](https://www.macports.org):

    $ sudo port install pcre2

If you don't have bzip2-dev and lzma-dev, try this:

    $ sudo port install bzip2
    $ sudo port install xz

**Comment by grylem** [comment]
maybe I found the reason: Illegal instruction: 4
I used an mac computer for testing and the latest version of ugrep that works on it - 1.7.6,
all others include the latter give an error -  Illegal instruction: 4

**Comment by genivia-inc** [comment]
It could be an AVX problem. I've now updated `bin/macosx/ugrep` in the master branch to use SSE2 only.

**Comment by grylem** [comment]
Works on new mac with Mojave/Catalina, but on old with High Sierra - Illegal instruction: 4

**Comment by genivia-inc** [comment]
We should create a homebrew formula for ugrep instead of sharing the binary, because it's best to use ugrep's optimizations for speed. I'll get to that in a few days.

**Comment by genivia-inc** [comment]
I've created a homebrew formula. However, the `brew audit` command says "repository not notable enough (<30 forks, <30 watchers and <75 stars)". Well, this is not surprising as the repo is relatively quite new.

It seems we need more stars and forks to release a homebrew formula.

Any help is appreciated.

**Comment by genivia-inc** [comment]
See "help wanted" https://github.com/Genivia/ugrep/issues/21

**Comment by genivia-inc** [comment]
For those that want a MacOS version of ugrep with all features enabled, use `brew tap https://github.com/Genivia/ugrep` to clone ugrep on your system with [homebrew tap](https://docs.brew.sh/Taps). Then `brew install ugrep` to install ugrep . I'll create a homebrew formula later, see #21.
