### ISSUE TITLE
Show file hit count

### ISSUE THREAD

**Issue by raelb** [Genivia/ugrep#196]
Hi,
Is there an option to show the number of matches for each file? For example when using the -l switch (don't show match snippet), but still show the number of hits for each file.
If not, please consider as a feature request.
Thanks.

**Comment by raelb** [comment]
Yes, thanks, I didn't notice that command before. However, I want the option to not show result where count = 0. Otherwise I get a huge list of spurious results.

**Comment by genivia-inc** [comment]
The beauty of bash (and other shells) is that you can pipe results to another utility, like so:
~~~
ugrep -c PATTERN ... | ugrep -v ":0"
~~~
This won't work with the TUI though, but `--pager` is fine:
~~~
ugrep --color=always -c PATTERN ... | ugrep -v --pager ":0"
~~~
Grepping is not only for searching for files, it's also often used to filter results of other command-line tools.

**Comment by genivia-inc** [comment]
I wonder if we can extend option `-m` (`--max-count`) to accept a range, like `-mN,M` to show only between N and M matches. If M is omitted, as in `-mN,` (note the comma!) this will show match N and up if at least N matches were found. This will not break grep compatibility and won't need another new option.

**Comment by raelb** [comment]
Thanks for the tip re piping. It works, but console colors are lost. It still seems strange to include results with count = 0. I would think by default they should be excluded, and only included if a modifier is included, e.g. -ca (all). Anyway it sounds like you are just following grep behaviour.

It's seems a little unintuitive to call `-m1,` (we're essentially doing the reverse of the flag...), but it does still make sense. Anyway it would be nice to have some option to exclude 0 results.

**Comment by genivia-inc** [comment]
The short-form `-m` option has a long counterpart `--max-count`. Adding `--min-count` should be logical and intuitive:
~~~
    -m [MIN,][MAX], --min-count=MIN, --max-count=MAX
            Stop reading the input after MAX matches in each input file when
            specified.  Require at least MIN matches when specified, omitting
            the first MIN matching lines from the output.
~~~

**Comment by raelb** [comment]
Yeah, the more I think about it, the more I like it :)

**Comment by genivia-inc** [comment]
I've added `--min-count` to ugrep v3.7.6. This works for options -c, -l, -L and -q. Other combinations may be supported in a future update, since this will take more time to implement and thoroughly test.

**Comment by raelb** [comment]
Thanks, It's been very useful
