### ISSUE TITLE
List only directories in TUI mode?

### ISSUE THREAD

**Issue by raelb** [Genivia/ugrep#197]
Hi,
Is it possible to list only directories - in general, and also specifically in Query TUI mode?
i.e. I want to search for a string in subfolder names recursively, but not in any files.
Thanks

**Comment by raelb** [comment]
To elaborate on motivation for this (if it is unclear): The TAB and SHIFT-TAB commands are very handy to move into or out of a directory, but you need to first locate a file in the directory in order to move into that directory. Often you want to first locate a directory so you can move into that, and then search for a file.

**Comment by genivia-inc** [comment]
Thanks for the feedback and suggestion.

Only listing the named of directories with `-l` is not possible, but you can use Control-S to skip to the next directory and Control-W to jump back up.

Control-W and -S are quick ways to skip over the files displayed, or with options -l and -c the directories displayed.

Does that help?

**Comment by genivia-inc** [comment]
The new ugrep `--tree` option is a nice alternative view for option `-l` to list directory trees. In the TUI press ALT-l (ell) to activate list view. Then use CTRL-S and CTRL-W to jump forward/backward. Use TAB to jump into a directory and SHIFT-TAB to jump back. If you have a .ugrep configuration file then add `tree` to it to list directory trees like so:
![tree](https://camo.githubusercontent.com/2b4f4176755899bd81b4f8628cdbc1646f980303aae7163e8cf5be72b48caa39/68747470733a2f2f7777772e67656e697669612e636f6d2f696d616765732f736372362e706e67)
