### ISSUE TITLE
ZSH/Fish autocompletion

### ISSUE THREAD

**Issue by sujitawake** [Genivia/ugrep#198]
Curious if there are any near future plans to develop zsh/fish autocompletion scripts? This would be very helpful indeed.

**Comment by genivia-inc** [comment]
Thanks for your question and suggestion.

This is something to look into as an enhancement for a future update. I can't add it soon, but will put it on the TODO list.

If someone else finds to time to work on this as a contribution to ugrep, that would be fantastic 😀

**Comment by genivia-inc** [comment]
Looking into this. So to get started, I would expect to find autocompletions for grep somewhere, like here: https://github.com/zsh-users/zsh-completions . If grep has autocompletions, then those would be a good starting point for ugrep. Any suggestions?

**Comment by arrufat** [comment]
For fish, you can run `fish_udpate_completions` and it will parse the man pages in your system and generate completions for all your commands, including ugrep.
I've done it and it works great:
![image](https://user-images.githubusercontent.com/1671644/202059106-931bf8e0-50d5-4971-ad1c-eea4686dc212.png)

**Comment by genivia-inc** [comment]
@sujitawake and @arrufat I'm closing this as the suggestion to use [fish_udpate_completions](https://fishshell.com/docs/current/cmds/fish_update_completions.html) works great. Let me know if there is something else I can do for you.

**Comment by varenc** [comment]
I would love zsh completions which this issue mentioned! I don't think there's a way to turn an automatically generated fish completion into a zsh completion. (Though I'd love to find something for zsh that worked as well as fish_udpate_completions)

**Comment by genivia-inc** [comment]
Bash completions are now added to the ugrep repo, located in the `completions` directory.

I would really like to add fish and zsh completions too. If you are happy with the results generated by the fish/zsh completion generators, then we should add those. Note that a couple of new options were added to ugrep, so perhaps running the generators again is needed to bring them up to date.

**Comment by sujitawake** [comment]
I tried copying the above gist suggested by @varenc, and putting it under the `~/.oh-my-zsh/completions` directory doesn't initialize the completions for me. Am I missing something here?

That being said, having something "dedicated" to zsh would be extremely helpful.

**Comment by genivia-inc** [comment]
@sujitawake @arrufat @varenc I get your pleas to get this working for fish and zsh. The completion file formats doesn't look all that complicated. Let me write a script to generate fish and zsh completion files from the ugrep help page. I've done the same recently for bash completion to show the "usage" of ugrep.

**Comment by genivia-inc** [comment]
Fish completions are now autogenerated with a new `compgen` script. Next up will be zsh. Files are located in the repo completions dir.

**Comment by genivia-inc** [comment]
The upcoming updated build and installation scripts will install the bash, fish and zsh completions. The installation location is decided by the shell's package installer checked by `./configure`, where the usual vendor-installed tool completion locations are:
- bash completions: `/usr/local/share/bash-completion/completions/`
- fish completions: `/usr/local/share/fish/vendor_completions.d/`
- zsh completions: `/usr/local/share/zsh/site-functions/`

**Comment by genivia-inc** [comment]
The latest commit to the repo includes updated fish and zsh completions. Those will be installed after `./build.sh` and `sudo make install` to install the ugrep commands and to install the bash, fish and zsh autocompletions.

This update performs bash, fish and zsh completions for the `ug`, `ug+`, `ugrep`, and `ugrep+` commands. I've tested it and it works nicely. I'm happy to make changes or improvements based on your feedback. So your are welcome to let me know your thoughts.

The `bash` and `fish` completions suggest option argument values for `-t` (`--file-type=`), `--encoding=`, `-D` (`--devices=`), `-d` (`--directories=`), `--hexdump=`, `--sort=`,  and `-Z` (`--fuzzy=`).

Note that the `=` is mandatory with long option argument values! GNU recommends `=` for long options with arguments. It's not done automatically with `fish` completions, unfortunately.

The `zsh` completions do not suggest option argument values. I don't know yet how to make that reliably work. The zsh completion documentation is helpful, but not that clear on the details how to accomplish this. I need more time to digest the specification, which is quite long and without examples, alas.

**Comment by arrufat** [comment]
Great, thank you!

**Comment by genivia-inc** [comment]
OK, I figured how to reliably define option arguments with zsh completions. I've committed an update that adds them. Several short and long options take arguments. Choices are provided, for example for option `-t` (`--file-type=`) the file types are completed.
