### ISSUE TITLE
Fuzzy search with option --sort=best

### ISSUE THREAD

**Issue by jschleus** [Genivia/ugrep#205]
If I use the command

 `ugrep --sort=best -Z1 "ab" approx.test` 

for the following  simple file `approx.test` 
```
a
ab
```
for me surprisingly I got as output both lines in the order seen above.

OK, `-Z1` means "one error" is allowed so the match of the line`a` is correct but because also the option `--sort=best` is used I would expect the exact match `ab` as the first line.

By the way, similar to the options combination `-B -y` available for  the `agrep` command of the `tre` package I would wish to have an option that would show only the best match(es).

**Comment by genivia-inc** [comment]
The `--sort` option applies to files, not lines.

The ordering first shows all files with _at least_ on exact match, then files with at least one mismatch but no exact match, then files with at least two mismatches etc. The matches are not sorted by lines, but by files searched. This option has no. effect If one file is searched.

**Comment by jschleus** [comment]
Grrh, embarrassing that I overlooked that in the manual page.

Nevertheless it would be nice to have such a feature for matches within a file. Here an extract of the manual page of the `agrep` command of the `tre` package (but over 12 years old, written by Ville Laurikari): 
```
-B, --best-match
       Only output the best matching records, that is, the records with the lowest cost.
       This  is  currently implemented by making two passes over the input files
       and cannot be used when reading from standard input.
```

**Comment by genivia-inc** [comment]
The `--sort=best` option performs two passes over the input, the first to determine the edit distance cost and the second to display the contents. So it is possible to use the cost of the first pass to constrain the output to the best matches only. This is not entirely as trivial as it sounds though, because the master thread performs the first pass and the workers perform the second pass to output matches, meaning that the minimal cost should be passed on to the worker thread responsible for the output.

I will add this to the TODO list.

Thanks for the suggestion!

**Comment by jschleus** [comment]
Oh, that's good or hopeful news. I'm sure that would be very helpful in some use cases.
And probably it would make `ugrep` to the only maintained "grep"-like tool with this feature.

**Comment by genivia-inc** [comment]
I have a working prototype version that is being tested and verified. Looks like this will be a nice addition!

On a practical note, we can either add a new option `--best-match` or add a new `best` argument to option `-Z` (`--fuzzy`) like `-Zbest` (`--fuzzy=best`).

I prefer the latter approach, because adding a new option makes it only meaningful when `-Z` is also used, which seems redundant (why two options?). Making `best` an optional argument to option `-Z` makes more sense, IMHO. So you can use `-Zbest3` for example and `-Zbest+3` to only allow up to 3 character insertions and showing the best matches (e.g. zero insertions if there is at least one exact match). It's short and quick.

What do you think?

**Comment by jschleus** [comment]
That's great news. With regard to the associated options, I can well agree with your arguments.

**Comment by genivia-inc** [comment]
Now available in the ugrep 3.7.11 release update.

**Comment by genivia-inc** [comment]
PS. a little secret: `--best-match` also works when used with `-Z`. Bit I kept `--best-match` out of the man page and documentation since it is redundant with `-Zbest`. Trying to keep things simple.

**Comment by jschleus** [comment]
Oh, nice. Thanks for the "secret" info.

Til now I don't have tested the new feature intensively but I plan to replace in some of my scripts while searching for "best matches" the  "tre" `agrep` tool by the `ugrep` tool.

Nevertheless some small comments:

a)  If using a test file `data1` with the content
```
3.13.5
1.23
13.25
1.23.4
a.23.4
b.23.5
2.23.5
```
one get using the command `ugrep -Zbest "1\.23\.5" data1` the result
```
1.23.4
```
what is also in my human and subjective rating the best match. But it is probably a "wrong" result
since two other lines match also with one error. I think the output of the command `agrep -B -y "1\.23\.5" data1`
```
1.23.4
b.23.5
2.23.5
```
is here more correct. Or have I something overseen? Or is the position or the character class of the non-matching character also relevant?

b) A probably obsolete remark since regarding only an "old" release:

If one use the previous version 3.7.10 the command `ugrep -Z "1\.23\.3" data1` with the above mentioned file works but `ugrep -Z "1.23.3" data1` leads at least on my system (Linux openSUSE Leap 15.3, 64-bit, gcc 7.5.0 (SUSE Linux)) to an endless-loop. But version 3.7.9 is again working as expected.

c) If using a test file `data2` with the content
```
110
101
011
222
000
```
one get using the command `ugrep -Zbest "11" data1` the obviously correct result
```
110
011
```
where the matching digits "1" are red-colored and the non-matching "0" black-colored, ok.
But if one use the command `ugrep -Zbest "111" data1` with the result
```
110
101
011
```
only the leading "0" in the last line is black-colored, all other digits are red-colored. Is that the expected behavour?

d) Off-topic: The FOSS server [fossies.org](https://fossies.org) (that I maintain) supports now also "ugrep":

&nbsp;[https://fossies.org/linux/ugrep](https://fossies.org/linux/ugrep)

That server offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the GitHub "master" branch of "ugrep". That continuously updated report is generated within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

 &nbsp;https://fossies.org/linux/test/ugrep-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently still half-hourly.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them.

Ok, only a few and obviously harmless bugs were found, moreover mostly only in code comments and thus invisible to users.

**Comment by genivia-inc** [comment]
The `-Z` fuzzy matcher always matches the first character(s) of the pattern to optimize search speed as the manual page says. It is not only to optimize search speed, but also to avoid matching everything when the fuzzy max is larger than 1 and the pattern is short.

The way around this (to fuzzy match the first character) is to use a `.?` at the start

**Comment by genivia-inc** [comment]
BTW. update 3.7.11 fixes the blocking issue that I already found in some strange cases.
