### ISSUE TITLE
configure with libs/includes in non-default loactions

### ISSUE THREAD

**Issue by darked89** [Genivia/ugrep#207]
Hello,

I was trying to enable zstd on Centos 7 system without zstd installed system-wide. So I have put it in:
/home/username/soft

and tried:

```
./configure  --prefix=/home/username/soft  --with-zstd=/home/username/soft 
```

I am getting:

```
checking if zstd is wanted... yes
checking for ZSTD_decompressStream in -lzstd... no
checking for zstd.h... yes
libzstd not found: ugrep option -z won't decompress .zst files
```

What is quite puzzling:

```
./configure
# gives
checking if zlib is wanted... yes
checking for inflateEnd in -lz... no
checking for zlib.h... yes
zlib not found: ugrep option -z is not available
```

But:
```
ls -l /usr/include/zlib.h 
-rw-r--r-- 1 root root 86717 May 19  2016 /usr/include/zlib.h

ls -l /usr/lib/libz.so.1*
lrwxrwxrwx 1 root root    13 Sep  4  2018 /usr/lib/libz.so.1 -> libz.so.1.2.7
-rwxr-xr-x 1 root root 89736 May 19  2016 /usr/lib/libz.so.1.2.7
```

This is a HPC system with modules, so I do:
```
module load gcc/11.2.0
```

I have checked that there is neither ```zlib.h``` nor ```libz.so.1``` somewhere in ```/prod/comp/gcc/11.2.0/include``` and /prod/comp/gcc/11.2.0/lib```, so I guess ```zlib.h``` reported as found by configure is from  ```/usr/include/zlib.h```.

My question:
What are the proper options to run ```./configure``` so it will find/recognize libs/includes in i.e. /home/username/soft?

Many thanks for your help

Darek Kedra 
EDIT: spell

**Comment by genivia-inc** [comment]
I have to take a closer look.

**Comment by genivia-inc** [comment]
> What is quite puzzling:
> ```
> ./configure
> # gives
> checking if zlib is wanted... yes
> checking for inflateEnd in -lz... no
> checking for zlib.h... yes
> zlib not found: ugrep option -z is not available
> ```
The autoconf zlib script looks for include/zlib.h in /usr/local, /usr, /opt/local, /sw in that order or the specified --with-zlib=DIR location first before these standard locations. When zlib.h is found in one of those places, it will try to compile with -L<place>/lib to load -lz. So it uses -L/usr/local/lib if /usr/local/include/zlib.h was found. Likewise, if the specified location is /home/username/soft, which is checked first before the standard locations, has include/zlib.h then -L/home/username/soft/lib will be used with -lz.

The zstd autoconf script m4/ax_check_zstdlib.m4 that I wrote does the same thing. Perhaps some files or directories in  /home/username/soft aren't readable?

**Comment by darked89** [comment]
Hello,
Thank you for your help.

I did a bare bones run of ```configure``` with and without the ```module load gcc/11.2.0```.
The gcc module sets:
```
LD_LIBRARY_PATH=/prod/comp/gcc/11.2.0/lib64:/prod/comp/gcc/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0:/prod/libs/gnu/mpfr/4.0.1/lib:/prod/libs/gnu/mpc/1.1.0/lib:/prod/libs/gnu/gmp/6.1.2/lib:/prod/slurm/current/lib:/opt/gold/lib:/opt/gold/lib/Gold
```

Without this module:
```
LD_LIBRARY_PATH=/prod/slurm/current/lib:/opt/gold/lib:/opt/gold/lib/Gold
```  

The good thing: no module loading & using system's gcc  4.8.5 does produce working ```ugrep```, so I can start using it on this system. 

Also: I think this issue can be closed. Most likely these are issues related to a configuration of the cluster. 

DK

**Comment by genivia-inc** [comment]
Thanks for the update. Good to know.
