### ISSUE TITLE
ugrep build Linux Mint 

### ISSUE THREAD

**Issue by ttsoares** [Genivia/ugrep#210]
Operating System: Linux Mint 20.3
 Kernel: Linux 5.4.0-117-generic
./build
...
mv -f .deps/ugrep-screen.Tpo .deps/ugrep-screen.Po
In file included from ugrep.cpp:151:
zstream.hpp: In member function ‘std::streamsize zstreambuf::ZipInfo::decompress(unsigned char*, size_t)’:
zstream.hpp:488:40: error: ‘BZ_OK’ was not declared in this scope; did you mean ‘Z_OK’?
  488 |                 if (num == 0 && ret == BZ_OK)
      |                                        ^~~~~
      |                                        Z_OK
mv -f .deps/ugrep-cnf.Tpo .deps/ugrep-cnf.Po
make[2]: *** [Makefile:462: ugrep-ugrep.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/ugrep-query.Tpo .deps/ugrep-query.Po
mv -f .deps/ugrep-output.Tpo .deps/ugrep-output.Po
make[2]: Leaving directory '/home/ttsoares/community.ops.io/ugrep/src'
make[1]: *** [Makefile:464: all-recursive] Error 1
make[1]: Leaving directory '/home/ttsoares/community.ops.io/ugrep'
make: *** [Makefile:364: all] Error 2

autoreconf -fi  did not help.

**Comment by navarroaxel** [comment]
I compiled `ugrep` using a live Mint 20.3. :thinking: 
Linux 5.4.0-91-generic.

**Comment by genivia-inc** [comment]
It looks like I made a mistake in typing `BZ_OK` at zstream:488 instead of `Z_OK`. Both have the same value and meaning, but `BZ_OK` is not defined without libbz2.

**Comment by genivia-inc** [comment]
Fixed.

**Comment by ttsoares** [comment]
Thank you :-)
