### ISSUE TITLE
Searching .bz2 files on Windows

### ISSUE THREAD

**Issue by phcaptjim** [Genivia/ugrep#211]
I'm wondering how one would search .bz2 files on Windows given the fact that you need "libbz2" to make it work.  On linux it should not be a big deal, but not sure how to do that on Windows?  Has anyone successfully greped using -z on Windows for .bz2?  Thanks.

**Comment by genivia-inc** [comment]
The ugrep.exe binary supports bz2, gz, zip, lz4, zstd, Z (compress) and tar/pax/cpio archives. The tests/archive.tbz test case is compressed with libbz2 and ugrep.exe can handle it with option `-z`. I've created a MSVC++ project with instructions (included in the repo) to build ugrep.exe with all supported compression libraries.

What is the problem?

**Comment by phcaptjim** [comment]
Thanks!  I just upgrade to VS2019.  I can do a build for Pcre-UGREP with all appropriate libraries (for me BZIP2) and that will get me going with compressed files?  I was confused as to whether or not it already supports the `-z `option or if the build is required.

**Comment by genivia-inc** [comment]
The ugrep.exe binaries are included in the repo. If you want to build ugrep.exe from source then see the vs/README.md which I use to build ugrep.exe, and another by a contributor with a different setup in msvc/README.md. Building ugrep.exe with all libraries is not trivial but the instructions should help.

**Comment by phcaptjim** [comment]
Thanks again!  It's working great.
