### ISSUE TITLE
What's in a name? That which we call a zip by any other name would spell as sweet

### ISSUE THREAD

**Issue by unDeadHerbs** [Genivia/ugrep#213]
There are a variety of file types which are merely disguised zip files.  Among them are all of the new MS-Office types (`docx`, `xlsx`, `pptx`) and Simulink files (`slx`).

I request a command line flag for listing extensions that should be treated as `zip` files.

Example use case and syntax:  Searching for all uses of a model in a Simulink project.
`ugrep model_name -r -z=slx`

**Comment by genivia-inc** [comment]
Ugrep already searches zip files regardless of their suffix extension, by detecting the "PK" zip magic header signature. No need for a new option. Just use `-z`.
