### ISSUE TITLE
building ugrep against a system copy of libreflex

### ISSUE THREAD

**Issue by carlwgeorge** [Genivia/ugrep#215]
I'm considering packaging ugrep for Fedora and EPEL (extra repo for RHEL and RHEL-like distros).  Fedora packaging guidelines [recommend building against system libraries instead of bundled libraries](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) when possible.  It appears that ugrep bundles https://github.com/Genivia/RE-flex.  Is it possible to build RE-flex as a shared library and then tell ugrep to link against that shared library?  I didn't see an obvious way to do this looking at the build instructions.

**Comment by Robert-van-Engelen** [comment]
The reason why I stayed away from separately linking the RE-flex library with ugrep is that it caused headaches for me to make sure RE-flex is updated before ugrep when I add a feature to RE-flex that a new version of ugrep uses. If RE-flex is not updated before or simultaneously with ugrep, then ugrep builds will break. This gives me speed advantage to release ugrep versions quickly without having to wait and worry about RE-flex updates. At some point I may no longer have to add features to RE-flex to improve ugrep. At that time is might be best to part ways.

**Comment by carlwgeorge** [comment]
Thanks for the explanation.  It is of course your choice how the software is structured.  Thankfully a few years back Fedora relaxed their bundling policy to permit this kind of situation.  I'll proceed with adding ugrep to Fedora with reflex bundled.  If things change in the future, reflex can be added as a shared library at that point.

**Comment by bkmgit** [comment]
Should the reflex library bundled with ugrep be considered a beta version and that at  https://github.com/Genivia/RE-flex a stable version? Re-flex has features that would make it worth having a fully separate package.  It is possible to make a [Git Submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and then use GitHub actions to run tests to ensure things do not break.  Happy to add this functionality.  It seems that [block_scripts.cpp](https://github.com/Genivia/ugrep/blob/master/lib/block_scripts.cpp), [language_scripts.cpp](https://github.com/Genivia/ugrep/blob/master/lib/language_scripts.cpp) and [letter_scripts.cpp](https://github.com/Genivia/ugrep/blob/master/lib/letter_scripts.cpp) are the main additions to the bundled library in ugrep that is not in the RE-flex repository.

**Comment by Robert-van-Engelen** [comment]
The script .cpp files are part of RE/flex and located in a separate directory named `unicode`. I understand the rationale to separate the two and if Fedora handles these situations with separate libraries and dependencies on versions, that's great to know. If version dependencies are enforced then it's safe. But it is a hassle at this time (see my earlier comment) and effectively takes time and focus away from working on the important stuff IMO. I get no help with development other than occasional minor contributions and suggestions. I was able to write these and many other projects rather quick (and solidly I should add) by not having to worry about other factors or having to rely on external libs much. If I use an external library (e.g. PCRE2, compression libs) then I write wrappers in around them to do everything I want them to get done and to isolate their quirks if there is a (future) issue using them.

**Comment by bkmgit** [comment]
Many thanks for this very useful software and pointing out the unicode directory. 

Will the latest release versions of ugrep and RE/flex be compatible?  This would enable packaging them separately.  It would also make contributions easier.

When building for Fedora, the shared library build of RE/flex is possible and enables reuse by other projects due to the compatibility with flex. Thanks for leaving in the commented version of what should be changed that did not work on Mac.

**Comment by bkmgit** [comment]
Sorry, it seems one should take the latest release version of ugrep, and then apply changes to RE/Flex whenever ugrep is released.

**Comment by Robert-van-Engelen** [comment]
RE/flex right now is compatible with ugrep. I do try to release them in tandem within a couple of days, but not necessarily in the "right order" and it may take longer than a few days. I also experimented more often with RE/flex in ugrep before releasing a RE/flex update. Ugrep is more or less a beta for adding features that eventually get into RE/flex after more testing and feedback.

**Comment by bkmgit** [comment]
Ok. CI can also be setup on GitHub https://github.com/bkmgit/RE-flex/tree/ci - tests for Mac and Windows also possible.  Docker can be used for other operating systems if needed.  Travis is nice, but does not seem to be configured to run tests.
