### ISSUE TITLE
Multi-Term Search on Windows

### ISSUE THREAD

**Issue by nkl0x55** [Genivia/ugrep#216]
Hi,
I'm trying to search through files for the string exactly matching script and 200 but excluding 404 
Not sure how to achieve this on Windows cmd line.
Below is screenshot of attempted command & results:
![image](https://user-images.githubusercontent.com/5791182/181054324-03ebab4b-90cf-4aae-a5a0-8be84d1bc671.png)

**Comment by genivia-inc** [comment]
BTW. when in doubt, use --stats to display the search details performed. This also shows the search patterns.

**Comment by nkl0x55** [comment]
Hi,

Thanks for the -F option, it works for my need.
