### ISSUE TITLE
can ugrep search visio/docx/excel file on windows?

### ISSUE THREAD

**Issue by zhuzhzh** [Genivia/ugrep#221]
I installed libreOffice on windows10. but ugrep still can't search

**Comment by genivia-inc** [comment]
You can also search compressed files with `-z` and this will find matches in .xlxs, .docx, and .pptx that are zip-compressed XML files, but this matches XML contents not contents converted to text (with `soffice`):
~~~
ug -z -lr -Odocx,xlsx,pptx
~~~
