### ISSUE TITLE
Recursively searching into .src.rpm or even just .cpio files

### ISSUE THREAD

**Issue by ydirson** [Genivia/ugrep#228]
For the context, a .src.rpm files notably contains a cpio archive, which itself contains a compressed tarball with source files, along with some more files.

https://github.com/Genivia/ugrep/issues/185 gives a hint to use filter to search into otherwise-unsupported archives, so I tried a filter to use `rpm2cpio`, and with cpio being a supported format I expected `ug` to recurse and find match inside the tarball.

So I expected this to do the job:
```
$ ug -rz --filter="rpm:rpm2cpio %" "system-v1" mnt/ch83src/SPackages/xcp-python-libs-2.3.5-1.xs8.src.rpm
```

... and digging further, I was even confused thinking piping it the cpio was working
```
$ rpm2cpio mnt/ch83src/SPackages/xcp-python-libs-2.3.5-1.xs8.src.rpm | ug -rz "system-v1" 
git/python-libs/xcp/repository.py:            if treeinfo.has_section('system-v1'):
git/python-libs/xcp/repository.py:                ver_str = treeinfo.get('system-v1', category_map[category])
$
```
... until I looked more closely at the matches and realized that despite getting a stdin stream to analyze, the `-r` flags was getting `ug` to grep the current directory (instead? additionally?  in any case that's really confusing).

In fact, even after extracting the cpio file to the fs to give it a supposedly-known suffix, it won't recurse:

```
$ strace -e process -s1024 -f ug -rz "system-v1" /tmp/foo.cpio
execve("/usr/bin/ug", ["ug", "-rz", "system-v1", "/tmp/foo.cpio"], 0x7ffe1528dd58 /* 40 vars */) = 0
clone(child_stack=0x7f2e823c0fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTIDstrace: Process 8273 attached
, parent_tid=[8273], tls=0x7f2e823c1700, child_tidptr=0x7f2e823c19d0) = 8273
[pid  8272] clone(child_stack=0x7f2e81b3dfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTIDstrace: Process 8274 attached
, parent_tid=[8274], tls=0x7f2e81b3e700, child_tidptr=0x7f2e81b3e9d0) = 8274
[pid  8274] exit(0)                     = ?
[pid  8274] +++ exited with 0 +++
[pid  8273] clone(child_stack=0x7f2e8133cfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTIDstrace: Process 8275 attached
, parent_tid=[8275], tls=0x7f2e8133d700, child_tidptr=0x7f2e8133d9d0) = 8275
[pid  8273] exit(0)                     = ?
[pid  8273] +++ exited with 0 +++
[pid  8275] exit(0)                     = ?
[pid  8275] +++ exited with 0 +++
exit_group(1)                           = ?
+++ exited with 1 +++
$
```

What am I missing ?

**Comment by genivia-inc** [comment]
The `--filter` option forks a task, whose output is piped into ugrep. The `-r` option recurses directories, which you don't need to use with compressed and archived files because these are always searched at any depth.

It's mentioned in the README that `-r` is recursing directories. Archives aren't physical directories.

Hope this helps.

**Comment by genivia-inc** [comment]
I should add that `--filter` is applied _before_ files are unarchived, not _after_. Note that filter utilities may take file names, which are physically present in the FS. Therefore, an archived file (in tar, zip etc) cannot be converted with a filter utility unless the filter utility also unarchives the file(s) as well.
