### ISSUE TITLE
Multiple ugrep on windows

### ISSUE THREAD

**Issue by AlQubeAl** [Genivia/ugrep#230]
Hello,

with ripgrep i can use `rg.exe -v -j 6 -a "[^\x00-\x7F]" "input.txt" | rg.exe -j 6 -a --passthru "^[ \t]*" -r "" > "output.txt"`

but if i run the same command with ugrep i will get `ugrep: warning: cannot read (standard input): No such file or directory` 
`ugrep.exe -v -j6 -a "[^\x00-\x7F]" "input.txt" | ugrep.exe -a -j6 --passthru "^[ \t]*" --replace="" > "output.txt"`

Why?

Edit:
I have solved the problem, problem was i used in each pipe the multithreading command "-j". If i just use it in the first pipe it will work.
`ugrep.exe -v -j6 -a "[^\x00-\x7F]" "input.txt" | ugrep.exe -a --passthru "^[ \t]*" --replace="" > "output.txt"`

**Comment by genivia-inc** [comment]
> Edit: I have solved the problem, problem was i used in each pipe the multithreading command "-j". If i just use it in the first pipe it will work. `ugrep.exe -v -j6 -a "[^\x00-\x7F]" "input.txt" | ugrep.exe -a --passthru "^[ \t]*" --replace="" > "output.txt"`

Note that ugrep option `-j` (conditional case insensitive search) does something different than option `-J` (number of threads).
