### ISSUE TITLE
Organizing and beautifying the results ala nvim-telescope

### ISSUE THREAD

**Issue by thisismygitrepo** [Genivia/ugrep#231]
I'm besotted by the cleanliness of live grep plug-in of `nvim` called [nvim-telescope](https://github.com/nvim-telescope/telescope.nvim).

I wanted to have this tool as stand-alone executable and I came to discover `ugrep`. I used `-Q` option to get a live session, and it was great results-wise, but the visuals are below par in juxtaposition with [plugin](https://camo.githubusercontent.com/3d59e34d1f406890adf620546d3d97017ce0aacda034b1788c66fa872f192134/68747470733a2f2f692e696d6775722e636f6d2f5454546a6136742e676966)

Can we please have windows to isolate files names, file contents (using a preview window)? This makes `-Q` option a much more **interactive** experience compared to scrolling down voluminous pages of results.

I managed to generate this experience with other tools, called `fzf` with `bat`, using this command 
`fzf --ansi --preview-window 'right:60%' --preview 'bat --color=always --style=numbers,grid,header --line-range :300 {}'`

However, fzf is just a file finder, no grepping. 
Alternatively, if someone managed to put together something that gives this experience with existing tools, please share. Thanks.

**Comment by genivia-inc** [comment]
I agree that if there is a design idea or approach to beautify the TUI output without sacrificing the natural connection with grep, that would be nice.

The `-Q` output is very grep-like, naturally. That was by intent. The output is heavily dependent on the option choices in the help page, which are all grep options plus extras to extend grep as ugrep. File names, paths etc can all be specified there using a one-to-one correspondence to grep options. Saving a .ugrep configuration file with your preferences also helps a lot. Ugrep's TUI is also built to allow searching voluminous drives (giga and terabytes), without blocking and it is instantly restartable when correcting the regex pattern. This puts some constraints on what can be output and how it is output. It is a LOT easier if everything could be stored in memory, but alas, that is not realistic when searching an entire drive with lots of matches that generate gigs of output. Can any other existing search tool do that actually? Note that quoting after `-Q` can output selections or everything by pressing ENTER than select lines or 'A' etc.

**Comment by genivia-inc** [comment]
One thing I should add: I usually start looking for matching files with option `-l` (ugrep TUI `ALT-l`) to list files. In the TUI TAB into a file to view (the file shown on top) and press whatever ALT keys you want to list more details of that file, such as add/increase context (`ALT-])` or use/increase fuzzy matching (`ALT-}`), and even change the regex. Then SHIFT-TAB back out to get back to the list (also restores the regex). This approach is very effective if you know how to use ugrep's (and grep's) powerful options with ugrep's TUI navigation keys.

Perhaps the TUI could have a split window with the matching file shown? The list of matching files is still produced with `-l` though. So it's not clear to me what design this would have to follow to make it obvious.

**Comment by genivia-inc** [comment]
Closing this. See #254 for split-screen TUI enhancements, such as to preview a matching file.
