### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by rrthomas** [Genivia/ugrep#233]
With 3.9.2:

```
$ ugrep --directories foo
ugrep: invalid option --directories, did you mean --decompress, --depth, --dereference, --dereference-recursive, --devices, --directories or --dotall?
```

Thanks for your continued work on ugrep, which continues to be my grep of choice!

**Comment by genivia-inc** [comment]
This should say `missing argument for --directories` instead of reporting an invalid option. Will update this in the the next release cycle, perhaps in a few weeks as I don't have time now.
