### ISSUE TITLE
Please support locale-specific/unicode matching with `--basic-regexp`

### ISSUE THREAD

**Issue by rrthomas** [Genivia/ugrep#234]
GNU grep, for example, matches accented letters with `[:alpha:]` in UTF-8 locales.

Yes, I could either use GNU grep, or use `-P` to match `\p{L}` instead, but it would be nice to be able to use "standard" patterns with `ugrep -G` and not have to worry!

I also appreciate that ugrep currently documents the POSIX character classes as being ASCII-only, so it might be necessary to add a flag to support locale-sensitive POSIX regexs; at least for my use case that would be fine—I expect to have to use a shell alias or similar to "configure" ugrep to work the way I want.

**Comment by genivia-inc** [comment]
> Yes, I could either use GNU grep, or use -P to match \p{L} instead, but it would be nice to be able to use "standard" patterns with ugrep -G and not have to worry!

You don't need to use `-P` for Unicode pattern matching. So `\P{L}` and `\w` work by default to match Unicode. Only if you use `-U` to disable Unicode then they're limited to ASCII.

The `[:alpha:]` character class and the other forms of this are kept non-Unicode for legacy compatibility reasons.

In a future update I want to update option `-w` to perform Unicode word boundary matching and also make the word boundaries `\b` `\<` `\>` Unicode. They are Unicode with option `-P`, but not without at the moment.

**Comment by rrthomas** [comment]
Thanks for the hint! Of course, the attraction of using `[:alpha:]` and similar is that they work with non-PCRE-supporting tools.

**Comment by genivia-inc** [comment]
I will take a closer look at `[:alpha:]` and friends to make them use the current locale.

In the meantime, I've updated my dev version to implement option `-w` (`--word-regexp`) and boundaries `\b`, `\B`, `\<` and `\>` to obey Unicode (not locale specific). This updated `-w` also runs faster by up to 15% depending on the match frequency.

**Comment by genivia-inc** [comment]
So it seems that `[[:alpha:]]` should match `[\p{Lu}\p{Ll}]` i.e. lower and upper case letters only, judging from some experiments. With ugrep this can be specified as `[\u\l]` where `\u` is `\p{Lu}` and `\l` is `\p{Ll}` where these short escape forms aren't standard. Perhaps `[[:alnum:]]` should match `[\p{Lu}\p{Ll}\p{Nd}]`.

**Comment by rrthomas** [comment]
Looks good, thanks for your work on this!
