### ISSUE TITLE
ugrep static build

### ISSUE THREAD

**Issue by wetal2357531** [Genivia/ugrep#235]
Are there instructions on how to make a static ugrep build?  I want to use your program on Android (armv7a processor).  I tried to make a static build of ugrep myself, but it turned out to be a partially working program.  If I specify the direct path to the file in which to search, the lines are found.  And if I run it like this: "ugrep searchstring" or "ugrep searchstring *.txt" or "ugrep -r searchstring" or "ugrep -z -e searchstring", then an error occurs:

terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error 34587456
Aborted

Maybe I didn't make the link string of the executable file correctly?  Here is the static link line:

cd src
g++ -static -std=gnu++11 -Wall -Wextra -Wunused -O2 ugrep-ugrep.o ugrep-cnf.o ugrep-glob.o ugrep-output.o ugrep-query.o ugrep-screen.o ugrep-stats.o ugrep-vkey.o ugrep-zopen.o -L/usr/lib/arm-linux-gnueabihf -lpthread -L/usr/lib/gcc/arm-linux-gnueabihf/8 -lstdc++ -L/usr/lib/arm-linux-gnueabihf -lm -L/usr/lib/gcc/arm-linux-gnueabihf/8 -lgcc -L/usr/lib/arm-linux-gnueabihf -lzstd -L/usr/lib/arm-linux-gnueabihf -llz4 -L/usr/lib/arm-linux-gnueabihf -llzma -L/usr/lib/arm-linux-gnueabihf -lbz2 -L/usr/lib/arm-linux-gnueabihf -lz -L/usr/lib/arm-linux-gnueabihf -lpcre2-8 -L../lib -lreflex -o ../static/ugrep &> /host-rootfs/storage/emulated/0/ugrep-3.9.2_static_errors.txt

Could I have used the wrong versions of static libraries?

  Please make an instruction on static compilation of ugrep.

**Comment by genivia-inc** [comment]
On Android I have successfully built and tested ugrep with [termux](https://termux.dev/en/). In fact, I use this setup to test ugrep on Android for every release of ugrep. Just run the `./build.sh` script that comes with ugrep to build ugrep on Android.
