### ISSUE TITLE
Null byte in filename when grepping through tar archive

### ISSUE THREAD

**Issue by bcyran** [Genivia/ugrep#242]
Unfortunately this issue will be very vague. I was not able to reproduce it from scratch and I cannot share the files which cause it. Nevertheless I'm reporting, maybe it will be useful in some way.

I have one particular tar file which causes `ugrep` to output a null byte at the end of the inner file name (when using `--decompress` option). The results look as follows (null byte marked as `^@`):
```
archive.tar{path/inside/archive/file.xml^@}:a match...
...
```

Some info:
- This null is present here both with and without `--json`.
- This happens only for two particular files in the archive, all others are fine.
- The problem doesn't persist if I unpack the file and run ugrep on it. It doesn't persist if I repack this file into a new archive as well.
- Listing the archive using `tar` doesn't yield any nulls, the problematic files are displayed correctly.
- In general `tar` and other programs work with the archive happily, without any problems.

**Comment by genivia-inc** [comment]
Thanks. I will take a look at this. Tar has an interesting way of storing long paths with extended headers, which have to be reassembled. Is the path very long perhaps?

**Comment by genivia-inc** [comment]
Is there a way for you to share the tar archive for testing? This will help me a lot to find and fix the problem. If you are OK with that, then email it to the Genivia company email address, see www.genivia.com/contact.html and include a proper subject line. Thanks.

**Comment by bcyran** [comment]
@genivia-inc Unfortunately, I can't share the archive but I don't think it's necessary anymore.

You've hit the nail on the head - the issue is caused by the path length. I was able to reproduce it with any file. The null byte appears at the end when the path is longer than 100 characters.

**Comment by genivia-inc** [comment]
The next release cycle will include a fix. I'm 99% confident it is fixed, but I can't be sure since I can only produce a limited set of test cases, which are mostly ustar tar files and tar files with long path names using XHD headers. But tar has many variants. Long path names are also stored with typeflag L, which ugrep also handles (and includes my proposed fix.)
