### ISSUE TITLE
Cannot build with pcre2 < 10.34 anymore

### ISSUE THREAD

**Issue by barsnick** [Genivia/ugrep#245]
The feature PCRE2_MATCH_INVALID_UTF was added in pcre2-10.34:
https://github.com/PCRE2Project/pcre2/commit/16c046ce50f292d09fe12670370f1a1d227d8184

Since ugrep started setting this in version 3.9.3, it can no longer compile with older versions of pcre2.

Perhaps you may want to wrap this code into an `#ifdef`:
https://github.com/Genivia/ugrep/blob/e0064068ce8823c5bfeeed95b918b20229032ded/include/reflex/pcre2matcher.h#L295-L296

**Comment by genivia-inc** [comment]
Good point. This flag is necessary, but a workaround is to not call `pcre2_jit_match` when `PCRE2_MATCH_INVALID_UTF` is not defined:
~~~
#ifdef PCRE2_MATCH_INVALID_UTF
      if (jit_ && !(flg & PCRE2_ANCHORED))
        rc = pcre2_jit_match(opc_, reinterpret_cast<PCRE2_SPTR>(buf_), end_, pos_, flg, dat_, ctx_);
      else
#endif
        rc = pcre2_match(opc_, reinterpret_cast<PCRE2_SPTR>(buf_), end_, pos_, flg, dat_, ctx_);
~~~
so we can now make this optional:
~~~
#ifdef PCRE2_MATCH_INVALID_UTF
    if (cop_ & PCRE2_UTF)
      cop_ |= PCRE2_MATCH_INVALID_UTF; // recommended in the PCRE2 docs when using UTF-8
#endif
~~~
The `pcre2_match` still uses JIT when available, but does some more work.

What do you think?

**Comment by barsnick** [comment]
> What do you think?

I thought I had posted a comment, but my browser must have fooled me.

I guess the fix is perfect, if `pcre2_jit_match()` actually requires the patch.

I saw your update 3.9.4, and it builds fine on the older platforms.
