### ISSUE TITLE
Case-insensitive matching don't work properly

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [Genivia/ugrep#248]
Case-insensitive don't work with cyrilic (and maybe not only with cyrilic)

`test.txt` content:

```
Пример Текста
пример текста
```

behavior of ugrep (3.9.5), GNU grep (3.7) and ripgrep (13.0.0) on this screenshot

![upl](https://user-images.githubusercontent.com/46464602/215354054-71b2e9c9-8f49-40f4-8b6a-a0052632b384.png)

**Comment by genivia-inc** [comment]
Use option `-P` with `-i`, see `ugrep --help -i` because `ugrep` option `-i` is backward compatible to GNU/BSD grep which handles ASCII case-insensitive matching only:
~~~
    -i, --ignore-case
            Perform case insensitive matching.  By default, ugrep is case
            sensitive.  By default, this option applies to ASCII letters only.
            Use options -P and -i for Unicode case insensitive matching.
~~~
The reason is that to avoid unexpected problems with existing scripts that use grep when it is replaced with ugrep.
