### ISSUE TITLE
Files larger than 4GB in a tar archive cause ugrep to stop searching

### ISSUE THREAD

**Issue by Nullaccount** [Genivia/ugrep#249]
In the tar archive described below (potentially others as well), any file larger than exactly 4 GB will cause ugrep to stop searching at the 4 GB mark. Any text after the 4 GB point will not be searched. ugrep skips all remaining files in the archive located after the > 4 GB file.

### Environment
OS: Windows 10 22H2
FS: NTFS
Version: ugrep 3.9.6 WIN64

### Notes & Reproduction
I initially ran into a problem where I was unable to search lines in a .tar.gz archive containing a single 9GB file. After splitting/recreating the file all morning I excluded issues related to the contents of the file and narrowed it down to size related issues.

If I create a tar archive with the following files, ugrep will stop searching the 4 GB + 32 bytes file at the 4 GB mark. The remaining files in the archive are not searched. For reproduction I created files filled with "123456789012345" + Line Feed (0x0A). On the second line of each file I replaced some of the numbers with a text token. In the file > 4 GB  I did the same on each of the two 16 B lines after the 4 GB mark.

0.txt (32 B)
1.txt (4 GB exactly, not necessary for reproduction, just shows that ugrep will proceed as long as the file is <= 4GB)
2.txt (4 GB + 32 B)
3.txt (32 B)

Any text in the 32 B trailer of 2.txt is not matched and nothing in 3.txt is matched.
`ugrep -z 'TOKEN' .\repro.tar`

When using the `--stats` switch ugrep reports only reports 3 files searched and reports 536870912 lines searched (which is the 4GB mark of 2.txt, right before the 32 B trailer).

Issue is not affected by changing the number of lines prior to the 4 GB mark, it appears to only be dependent on file size.

The same behavior exists if the archive is gzip'ed. 

### Simplified Reproduction
In a simplified version of the reproduction without 1.txt and with each of the lines up to the end of the file marked with `Token T-n Lines` the output is as follows and fails to search the `T-1` and `T-0` lines.

**Input:**
```
repro.tar
 - 0.txt (32 B)
 - 2 ALT.txt (4 GB + 32 B)
 - 3.txt (32 B)
```

**Result:**
ugrep fails to search any content in the tar archive after the 4GB mark of "2 ALT.txt"
```
.\ugrep.exe -z --stats  'TOKEN' '.\repro.tar'
{0.txt}:1TOKEN789012345
{2 ALT.txt}:1TOKEN789012345
{2 ALT.txt}:TOKEN T-5 Lines
{2 ALT.txt}:TOKEN T-4 Lines
{2 ALT.txt}:TOKEN T-3 Lines
{2 ALT.txt}:TOKEN T-2 Lines

Searched 1 file in 5.24 seconds: 1 matching (100%) + 1 in archives
Searched 268435457 lines: 6 matching (2.235e-06%)
The following pathname selections and search restrictions were applied:
  --no-hidden (default)
Lines matched ignoring case if:
  "TOKEN" matches
```

**Expected Result:**
When using a .zip file with the same contents created with 7Zip ugrep correctly searches all files.
```
.\ugrep.exe -z --stats  'TOKEN' '.\output.zip'
{0.txt}:1TOKEN789012345
{2 ALT.txt}:1TOKEN789012345
{2 ALT.txt}:TOKEN T-5 Lines
{2 ALT.txt}:TOKEN T-4 Lines
{2 ALT.txt}:TOKEN T-3 Lines
{2 ALT.txt}:TOKEN T-2 Lines
{2 ALT.txt}:TOKEN T-1 Lines
{2 ALT.txt}:TOKEN T-0 Lines
{3.txt}:1TOKEN789012345

Searched 1 file in 5.4 seconds: 1 matching (100%) + 2 in archives
Searched 268435462 lines: 9 matching (3.353e-06%)
The following pathname selections and search restrictions were applied:
  --no-hidden (default)
Lines matched ignoring case if:
  "TOKEN" matches
```

**Comment by genivia-inc** [comment]
There is in principle no limit to the size of an archive, because it is incrementally searched. Perhaps something else is specifically happening. Will take a closer look ASAP.

**Comment by genivia-inc** [comment]
For aggressively testing ugrep in the past and still today, I've used many tests (besides the tests run at installation), including a 12GB text file and compressed versions of this file:
~~~
ugrep -c 'Sherlock Holmes' en.txt
7673
ugrep -z -c 'Sherlock Holmes' en.txt.gz
7673
ugrep -z --zmax=2 -c 'Sherlock Holmes' en.zip
en.zip{en.txt}:7673
en.zip{en.txt.gz}:7673
~~~
So I'm confident it is not compression that is the problem. I think it is the tar format somehow. The tar format is ancient and has many extensions ("hacks") to allow long file paths, larger files and date/time information.

**Comment by genivia-inc** [comment]
Searching a tar with a 12GB text file works in my case with the latest ugrep on MacOS, both compressed and uncompressed:
~~~
tar cvf en.tar en.txt
ugrep -c 'Sherlock Holmes' en.tar
7673
tar zcvf en.tgz en.txt
ugrep -z -c 'Sherlock Holmes' en.tgz 
en.tgz{en.txt}:7673
~~~
This is with bsdtar 3.5.1. I suppose you have a different tar version?

**Comment by Nullaccount** [comment]
I couldn't find what the original archive creator used, I've tested using:
- 7Zip 19.00
- 7Zip 22.01
- windows native tar command (bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp as ported by Microsoft, included in OS)

**Comment by genivia-inc** [comment]
@Nullaccount thanks for the info. Bsdtar should be the same, so it is unlikely a tar-specific issue. Perhaps it is a Windows-build-related issue in ugrep.exe. I will test ugrep.exe soon to see if I can replicate the problem.

**Comment by Nullaccount** [comment]
I noticed in your comment you used `-c` for the single-file tar archive en.tar. I was assuming that `-c` on a tar archive would just search it as a binary but I see that it doesn't require `-a` which makes me wonder: Is `-c` is implicitly doing a `-z` decompression/parse, or is implicitly `-a` searching the tar as if it were a binary file?

Note that in all examples I've been using `-z` on the uncompressed tar archive, as without `-z` ugrep simply reports that the binary matches and does not list the files within the archive.

I've tested on a few different sample files:

1. For a .tar containing 3 files less than 4 GB
  - ugrep -c, -zc, and -z all produce the correct expected output
2. For a .tar containing a single > 4 GB
  - `ugrep -c` reports the correct number of matches
  - `ugrep -z` and `ugrep -zc` both stop matching after 4GB
3. For the 'simplified reproduction' tar I described I get the following same results as the single-file test above (\# 2):
  - `ugrep -c 'TOKEN' '.\repro.tar'` returns 9 (correct)
  - `ugrep -zc 'TOKEN' '.\repro.tar'` stops counting after 6 tokens (same bug as described in issue)
  - `ugrep -z 'TOKEN' .\repro.tar'` stops counting after 6 tokens (same bug as described in issue)

**Comment by Nullaccount** [comment]
Looks to me like the issue is that the octal conversion of the file size from the tar header users strtoul which only returns a ulong to fill the uint64 size_t. My issue was fixed by changing it to strtoull. Didn't make a pull because I'm tired and haven't tested anything past "fixes my specific issue".

https://github.com/Genivia/ugrep/blob/8e3e1db7e2e37b2881e2679003439d7b4716d71d/src/ugrep.cpp#L1141

```
size_t size = strtoull(reinterpret_cast<const char*>(buf + 124), NULL, 8);
```

**Comment by genivia-inc** [comment]
@Nullaccount The problem could be related to GNU tar, which has custom tar header extensions. I found a discrepancy with their format of their size field and the ugrep implementation, which may affect large file sizes. I tested with 12GB files archived with bsdtar, gnutar (with gnutar header extensions). Everything appears to work properly now. To confirm so we can release an update, please try the ugrep.exe update 3.9.7 located in the bin/win64 directory of the latest commit (this new 3.9.7 version is not released yet).

**Comment by genivia-inc** [comment]
I made a second commit with `strtoul` replaced by `strtoull` as suggested, thanks.

**Comment by Nullaccount** [comment]
Can confirm that the new 3.9.7 binary is passing all of the tests I made regarding the issue! Thanks!
