### ISSUE TITLE
Flags -n and -o combined should print same line number twice

### ISSUE THREAD

**Issue by matvore** [Genivia/ugrep#251]
While ugrep at HEAD does this:

```
$ echo foo foo | bin/ugrep -no foo
1:foo
foo
```

GNU grep does this:
```
$ echo foo foo | grep -no foo
1:foo
1:foo
```

The GNU grep behavior seems better as the output is more script-friendly, and it's what I intuitively expected.

**Comment by genivia-inc** [comment]
It is a choice though. Early BSD and GNU grep versions displayed no additional line numbers either (I'm pretty sure, through I cannot find more info on this on the Web). I was used to that. It makes it immediately visibly clear that these are additional matches on the same line. However, the problem starts when sending grep results to filters that expect line numbers, even though that wasn't always the case in the past. Ugrep is meant to be compatible with grep whenever possible (new grep or old grep?), so it makes a bit more sense to include line numbers with additional matches to emulate new grep.

**Comment by genivia-inc** [comment]
I forgot to mention that ugrep option `-nou` with `-u` (`--ungroup`) does include full headers (i.e. line numbers) for every `-o` match. This option makes the choice more flexible, but it is not the same way GNU grep works.

**Comment by genivia-inc** [comment]
I've build an update that shows headers with each `-o` match, like the "new" grep. Wrapping up testing as we speak. Also updated `--format` output when used with `-o` to also enable `-u` to show all matches, improved `--json`, `--xml`, `--csv` output when used with `-o`, updated `--replace` output field `%m` to output the number of matches sequentially, new `--format` and `--replace` field `%M` outputs number of matching lines.

**Comment by genivia-inc** [comment]
Updated to release v3.11.0.

**Comment by genivia-inc** [comment]
Another thought for improvement: perhaps option `--separator=SEP` should override the `:`, `+`, and `|` default separators? This option only overrides the default `:` separator at moment.

If we let `--separator=SEP` override `:`, `+` and `|` then we can always recreate the exact GNU grep output when desired.

**Comment by matvore** [comment]
Thank you for the quick handling of this.

I would have also respected the decision of requiring `-u` for the GNU behavior. But I also think a lot of users may gripe about it, given GNU grep is a de-facto standard at this point.

There are other ways that ugrep deviates from GNU grep behavior and those are more obviously conscious decisions and they make sense (e.g. color output by default and -E by default)

`--separator=` sounds like it could be useful in a niche scripting case, where someone has filenames that include the default separators. I also suspect that most will write a hacky workaround in their script before they discover the feature.

If you want to make it more discoverable, perhaps add a stderr warning right before exit that says e.g. "Some filenames contain a separator character (any of `:+|`). Use `--separator` to override to a better value."

Just some suggestions.
