### ISSUE TITLE
Ignore matches of VERY long lines

### ISSUE THREAD

**Issue by JamiKettunen** [Genivia/ugrep#256]
I've tried to ignore e.g. minimized SVG files in my `ug` output with stuff like `-t "!svg"` but this simply won't do the trick for minimized JavaScript for example as I sometimes actually need to find something in a codebase like that as well.

Is there a way to for example treat all matches over X characters "as a binary file" and just show `File X matches pattern` or similar? I'm not a fan of a match that outputs e.g. 7k characters at once to my terminal for example.

**Comment by genivia-inc** [comment]
I understand. Yes, indeed, long matches are not great to display. But you can use option `-o` with options `-ABC` to display a match with some context for the `-o` option (`--only-matching`). For example: `ug -o -C20` shows a a match on a line with up to 20 chars before and after the match as context. There is no other grep tool that can do that.

You can also use `--width=COLS` to set the max window width, but that doesn't always show the match.

**Comment by JamiKettunen** [comment]
Thank you for the tips! Those will work just fine for the job ^^
