### ISSUE TITLE
add-filters.sh executed twice

### ISSUE THREAD

**Issue by andreasstieger** [Genivia/ugrep#258]
In ugrep 3.12, `add-filters.sh` is a script that generates the `ug+` and `ugrep+` wrapper shell scripts. Essentially it performs a build-time detection of installed text extractors.

The script is executed twice: both during `make build` and `make install`. This is a useless duplication.

**Comment by genivia-inc** [comment]
Thanks for the feedback. I have no better solution, since `make` runs twice (it also copies binaries twice already). Detecting if bin/ug+ exists might be an option, though there is a default bin/ug+ already.

**Comment by andreasstieger** [comment]
Obsoleted by 60b255d and discussion in #260
