### ISSUE TITLE
add-filters.sh not generating ug+/ugrep+ commands during build

### ISSUE THREAD

**Issue by andreasstieger** [Genivia/ugrep#259]
In ugrep 3.12, `add-filters.sh` is a script that generates the `ug+` and `ugrep+` wrapper shell scripts. Essentially it performs a build-time detection of installed text extractors.

I have a distribution package build which does NOT have any of the filter programs installed during build time:

````
[   54s] Creating ugrep+ and ug+ to search pdfs, documents, image metadata:
[   54s] pdf: no, requires pdftotext
[   54s] doc: no, requires antiword
[   54s] docx: no, requires pandoc
[   54s] epub: no, requires pandoc
[   54s] odt: no, requires pandoc
[   54s] rtf: no, requires pandoc
[   54s] gif: no, requires exiftool
[   54s] jpg: no, requires exiftool
[   54s] mpg: no, requires exiftool
[   54s] png: no, requires exiftool
[   54s] tiff: no, requires exiftool
[   54s] 
[   54s] OK
[   54s] 
````

But for some reason the generated file still references `pandoc`:

````
[   54s] + cat /home/abuild/rpmbuild/BUILDROOT/ugrep-3.12.0-84.1.x86_64/usr/bin/ug+
[   54s] #!/bin/bash
[   54s] ug --filter='odt,docx,epub,rtf:pandoc --wrap=preserve -t markdown % -o -' "$@"
````

Something is off here.

**Comment by andreasstieger** [comment]
Apparently you ship default scripts: https://github.com/Genivia/ugrep/blob/v3.12.0/bin/ug%2B#L2, and you fall back to them of filters are detected. Doing this at build-time is problematic (see #260), but also you are shipping both the code and a code generator.

**Comment by andreasstieger** [comment]
Actually this is seems more broken. In a standard `%configure && make && make install` run in a rpm packaging environment the `ug+` is not re-generated.

**Comment by genivia-inc** [comment]
Thanks for the feedback. Apparently I missed the extra line in the add-filters.sh script that should not be there as it adds pandoc as a filter regardless. I will update add-filters.sh
