### ISSUE TITLE
add-filter.sh is build-time detection, but should be run-time

### ISSUE THREAD

**Issue by andreasstieger** [Genivia/ugrep#260]
In ugrep 3.12, `add-filters.sh` is a script that generates the `ug+` and `ugrep+` wrapper shell scripts. Essentially it performs a build-time detection of installed text extractors.

This is a problem for distribution packaging: If you detect the `pdftotext`, `antiword`, `pandoc`, `exiftool` at build time, then installing them after the fact does not enable them for these commands when they are installed later. We could of course make them build-time dependencies and pull them into the build root, but that is not the best way to do this.

Please implement this properly by converting this into a run-time dynamic detection.

**Comment by genivia-inc** [comment]
I had a runtime version at first, but I did not like that approach at all, since I want to make sure the correct tools are available by checking their `--version` or `--help` output for a match. If the wrong tool is installed or if the wrong tool is installed later, then havoc may ensue when the tools run in ugrep e.g. replacing files in your file system.

It's not safe.

**Comment by andreasstieger** [comment]
There is no code in this script at all that is sensitive to the `--help` or `--version` output. The situation you describe is actually that this code implements: The tools installed at run-time count, not the ones at build time.

Did you consider GNU libextractor for this?

**Comment by genivia-inc** [comment]
> There is no code in this script at all that is sensitive to the `--help` or `--version` output. The situation you describe is actually that this code implements: The tools installed at run-time count, not the ones at build time.

Please look better before commenting. There is a check in add-filters.sh:
~~~
filters=
if [ -x "$(command -v pdftotext)" ] && pdftotext --help 2>&1 | src/ugrep -qw Poppler ; then
  filters="${filters}${filters:+,}pdf:pdftotext % -"
  echo "pdf: yes"
~~~
If `pdftotext` is installed that isn't the correct tool, then this prevents it from being used.

Consider the fact that a wrong tool might write files if it's command line options aren't compatible, then that would be really bad.

Using a run-time check is possible too, but there is extra overhead to check. This is better done at installation time. Especially on slow machines such as SBCs.

**Comment by genivia-inc** [comment]
This is the ug+ runtime version I had experimented with. It does not check if the filter command is the correct one. There might be other tools with the same name such as `pdftotext` in particular, so checking the tool's `--version` or `--help` is more than useful, but adds quite a bit of overhead.
~~~
#!/bin/bash
filters=
# search pdf files when pdftotext is installed https://pypi.org/project/pdftotext
if [ -x "$(command -v pdftotext)" ]; then
  filters="${filters}${filters:+,}pdf:pdftotext % -"
fi
# search doc files when antiword is installed https://github.com/rsdoiel/antiword
if [ -x "$(command -v antiword)" ]; then
  filters="${filters}${filters:+,}doc:antiword %"
fi
# search office documents and ebooks when pandoc is installed https://pandoc.org
if [ -x "$(command -v pandoc)" ]; then
  filters="${filters}${filters:+,}odt,docx,epub,rtf:pandoc --wrap=preserve -t markdown % -o -"
fi
# search image metadata with exiftool when installed https://exiftool.sourceforge.net
if [ -x "$(command -v exiftool)" ]; then
  filters="${filters}${filters:+,}gif,jpg,jpeg,mpg,mpeg,png,tiff:exiftool %"
fi
ug --filter="${filters}" "$@"
~~~

**Comment by andreasstieger** [comment]
"Installation time" for "package build time" for package based distributions. That includes SBCs who don't build on the deployed system.

**Comment by genivia-inc** [comment]
Sure, when binaries are shipped then the installation-time only approach to generate ug+ won't do much good.

I don't want to require these commands up front in the ugrep dependencies. It might fail to get ugrep installed on some systems.

The installation time approach is useful to alert users on the presence or absence of these commands, after which they can decide to install them when deemed useful to them.

I want to keep installation time reporting like we have at the moment.

But we can replace ug+ and ugrep+ with runtime checks.

**Comment by andreasstieger** [comment]
yep. I checked what some other packagers are doing. They didn't all bump the build dependencies, so ship the default script. 

Opportunistic checking might be a way, but I am not sure if this is the best user experience. I have no better idea for an implementation.

**Comment by genivia-inc** [comment]
A runtime check is slow on a MacOS M1 machine:
~~~
time ug+ Hello tests/Hello.pdf
     1:	Hello
0.153u 0.032s 0:00.20 90.0%	0+0k 0+0io 0pf+0w
~~~
Compare this to the version without checks:
~~~
time ~/Github/ugrep/bin/ug+ Hello tests/Hello.pdf
     1:	Hello
0.008u 0.009s 0:00.12 0.0%	0+0k 0+0io 0pf+0w
~~~
On a Raspberry Pi 3 this timing is not so bad as I had feared: 0.172 with runtime check versus 0.145 seconds without check.

**Comment by genivia-inc** [comment]
I've committed updated files without add-filters.sh. The build.sh script reports which tools are installed to alert users. The ug+ and ugrep+ scripts perform checks at runtime. But without the expensive exiftool output check (why bother, how many exiftool commands do exist in practice?)

Please check if this works for you.

**Comment by andreasstieger** [comment]
Built a package and gave it a good spin. Works fine.

**Comment by genivia-inc** [comment]
Let me know if this commit works for you. I will hold off to release v3.12.1 until then.

**Comment by genivia-inc** [comment]
OK. I will release v3.12.1.
