### ISSUE TITLE
minor documentation nitpick

### ISSUE THREAD

**Issue by minusf** [Genivia/ugrep#262]
The `-z` flag lists `.zip` as an "Archive" as opposed to "compressed archives":

```
       -z, --decompress
              Decompress files to search, when compressed.  Archives
              (.cpio, .pax, .tar and .zip) and compressed archives
              (e.g. .taz, .tgz, .tpz, .tbz, .tbz2, .tb2, .tz2, .tlz, .txz, .tzst)
...
```

while zip can make uncompressed archives, this is not its default mode of operation thus i would call zip a compressed archive...

the wikipedia holding page for zip also calls it like that:

...
- [ZIP (file format)](https://en.wikipedia.org/wiki/ZIP_(file_format)), a compressed archive file format

...

**Comment by genivia-inc** [comment]
You're right. Didn't notice it until you mentioned it. Thanks for making ugrep better!
