### ISSUE TITLE
enhancement idea:  create option to do record search similar to awk using record separator variable RS

### ISSUE THREAD

**Issue by acelticsfan** [Genivia/ugrep#263]
For ugrep's purposes, and to start simple, it doesn't need to support regex as part of the record separator/delimiter.  I think simply supporting a record separator option of just static string would be useful for most purposes.

It could search for and display the record (multi-line) with its separator line for any particular string.  

For example, I use awk like this:

awk -v RS="===== " "/DMI/" my_file

This finds any multi-line record that starts and ends with a delimiter of "===== ".  Once it has grabbed a record, it searches for DMI on the opening line with the separator / delimiter.  But, it would be cool if it had the flexibility to search the entire record to see if it matches.

Then, it prints any matching record.

All of this is just a suggestion or idea.  Just throwing it out there if there is any interest down the road in such a feature.  Thanks.

To quote from the awk man page:
```
   Records
       Normally,  records  are  separated  by  newline characters.  You can control how records are separated by assigning values to the built-in variable RS.  If RS is any single character, that character separates records.
       Otherwise, RS is a regular expression.  Text in the input that matches this regular expression separates the record.  However, in compatibility mode, only the first character of its string value is used for separating
       records.   If  RS  is set to the null string, then records are separated by empty lines.  When RS is set to the null string, the newline character always acts as a field separator, in addition to whatever value FS may
       have.
```

**Comment by genivia-inc** [comment]
Thanks for the suggestion! Let me take a closer look and get back soon.

**Comment by genivia-inc** [comment]
It's an interesting idea. However, it might be an overkill to make ugrep move towards a awk-like tool. I use awk too and like it a lot. But there are things better done with awk when you need to analyze or extract information from records with field data.

It is possible with ugrep to match multi-line patterns, such as `^=====\n.*DMI.*` which shows the delimiter followed by the line with DMI. Maybe not exactly what you want, but ugrep like grep are just search tools.

Thanks for your suggestion!
