### ISSUE TITLE
Help in searching a tbz2 archive

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#264]
I have created an archive using the `tar cjf "${HOME}/file.tbz2" ...files` command. I am trying to search said archive for the `<body` string (which I know at least some files contain, as extracting and searching for it works). What am I doing wrong here?

A couple of my tried commands:
```shell
grep "<body " file.tbz2 
grep -z "<body " file.tbz2 
grep -z "<body>" file.tbz2 
grep --verbose -z "<body>" file.tbz2 
grep --verbose -Trinz "<body>" file.tbz2 
grep -Trinz "<body>" file.tbz2 
grep -Trin --decompress "<body>" file.tbz2 
grep -Trin --decompress -l "" file.tbz2 
ugrep -q file.tbz2 
ugrep -Q file.tbz2 
ugrep -Qx file.tbz2 
ugrep -Qz file.tbz2 
grep -Trin --decompress "<body>" file.tar.bz2 
```

**Comment by genivia-inc** [comment]
Option `-z` recognizes `.tbz2`, `.tb2`, `.bz2`, and `.bzip2` suffixes.

- If the bzip2 library is not installed then ugrep will not handle this compression format.
- If the file is actually not compressed with bzip2 then ugrep will likely fail to search it.

**Comment by genivia-inc** [comment]
The test cases in ugrep/tests include a bzip2 test produced with:
~~~
bzip2 -9 -c archive.tar > archive.tbz
~~~
If libbz2 is installed then ugrep is verified with this bzip2 file. The file is compressed with version `bzip2, a block-sorting file compressor.  Version 1.0.8, 13-Jul-2019`.

**Comment by genivia-inc** [comment]
What I'm saying is, how did your bz2 file get compressed? Which version of bzip2? Why would it be different than other bzip2 files?

**Comment by stdedos** [comment]
> If libbz2 is installed then ugrep is verified with this bzip2 file. The file is compressed with version `bzip2, a block-sorting file compressor. Version 1.0.8, 13-Jul-2019`.


Yeah - same here:
```
bzip2, a block-sorting file compressor.  Version 1.0.8, 13-Jul-2019.
```

How can I figure out why my `ugrep` refuses to parse my file? 😕 



> What I'm saying is, how did your bz2 file get compressed? 

> `tar cjf "${HOME}/file.tbz2" ...files`

> Which version of bzip2? Why would it be different than other bzip2 files?

"Idk why it would be any different". That baffles me as well

**Comment by genivia-inc** [comment]
A quick sanity check with bzip2 and tar option -j all look fine to me, for example:
~~~
% wc big.cpp
  768916 2742743 36136266 big.cpp

% ug -c soap big.cpp
316438

% ug -z -c soap big.cpp.bz2 
316438

% tar cjvf big.cpp.tbz big.cpp
% ug -z -c soap big.cpp.tbz
big.cpp.tbz{big.cpp}:316438

% mv big.cpp.tbz big.cpp.tbz2
% ug -z -c soap big.cpp.tbz2 
big.cpp.tbz2{big.cpp}:316438
~~~
Still not sure why your tar with option -j produces a file that ugrep does not search?

**Comment by genivia-inc** [comment]
Still didn't find problems with the bzip2 decompression. Can you share the compressed file and uncompressed file so I can try to replicate the problem?

**Comment by genivia-inc** [comment]
Any chance you have to share the compressed and uncompressed files for testing is much appreciated. If these are not for public eyes, then please send it to our corporate contact by email.

**Comment by stdedos** [comment]
I'd rather not send it. Any chance I can run you some diagnostics locally? 😄

**Comment by genivia-inc** [comment]
> I'd rather not send it. Any chance I can run you some diagnostics locally? 😄

Not really.

But you can try a quick test like this:
~~~
ugrep -c -z "<body" file.tbz2 --stats
~~~
This should report something was searched and possibly found.

A diagnostic would require a few code additions to log libz2 activity e.g. to stdout.

**Comment by stdedos** [comment]
It seems that this is my fault.

I was at
```console
$ ugrep --version
ugrep 3.8.0 x86_64-pc-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4 +zstd
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
```

but my build scripts were broken for a while.

I did the effort now, and I updated to

```console
$ ugrep --version
ugrep 3.12.1 x86_64-pc-linux-gnu +avx2 +pcre2jit +zlib +bzip2 +lzma +lz4 +zstd
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
```

and now it works 😄 

Apologies for the false alarm, I guess

**Comment by stdedos** [comment]
As a side note, the debugging wasn't that useful:


```console
$ ugrep -z "<body " file.tbz2 --stats -c
0

Searched 1 file in 0.00855 seconds: 0 matching (0%)
The following pathname selections and search restrictions were applied:
  --dereference
  --no-hidden (default)
Lines matched if:
  "<body " matches
```

> A diagnostic would require a few code additions to log libz2 activity e.g. to stdout.

It could've been done on stderr, another fd - or immediately to a separate file 😅

**Comment by genivia-inc** [comment]
Thanks for the update on this issue and closing it.
