### ISSUE TITLE
Some questions, suggestions and/or feature requests

### ISSUE THREAD

**Issue by E3D3** [Genivia/ugrep#272]
The `ugrep` I used is ugrep 3.3.3 x86_64-pc-linux-gnu +sse2 +pcre2_jit +zlib +bzip2 +lzma +lz4 +zstd

To summarise, I have:
- a question about missing `ug+` and `ugrep+`.
- a question about filters.
- a question about or feature request for pdf filter matches to display page numbers.
- a feature request for user friendly README

I discovered `ugrep` when searching for pdf grepping tools in my software repository, via `Synaptic Package Manager`, a GUI used in Debian & variants. After clicking on the link to the homepage (in Synaptic package manager), I landed on the [wiki page](https://github.com/Genivia/ugrep/wiki) that advertises ugrep as a user friendly multi-tool, so I opened the [main github page/README.md](https://github.com/Genivia/ugrep/blob/master/README.md) to read more about it.

When seeing that github page for the first time I immediately wondered why such a super-tool had so few stars, until I saw the length of the page. This is IMHO a typical TL-DR case and totally **not user friendly**, especially with the table of contents not on top or bottom of the page. So I searched the web-page for "pdf", an found the filter example:

> Search pdf, doc, docx, e-book, and more with `ug+` using filters associated with filename extensions:

> `ug+ PATTERN ...`
> `ug --filter='pdf:pdftotext % -' PATTERN ...`
> ... 6 more examples left out ...

> **ProTip** the `ug+` command is the same as the `ug` command, but also uses filters to search PDFs, documents, and image metadata, when the `pdftotext`, `antiword`, `pandoc`, and `exiftool` are installed (optionally, not used when not installed).

English is not my native language and above text is very confusing for me. The first line suggest that I need `ug+`, but lines 3 to 7 shows examples using `ug` instead of `ug+`. Does this mean that without the given requirements, both can searches PDFs etc., only without using smarter filters ? And that `ug+` is like an alias for `ug --filter='WHATEVER % -` so that I should read the first sentence with an added or, like:

> Search pdf, doc, docx, e-book, and more with `ug`+ **OR** using filters associated with filename extensions:

The web-page doesn't tell more about "requirements" (for PDFs) so I installed `ug` to try it, of course without reading the whole web-page. I have more to do this week. I first discovered that there was no `ug+` command, and was sure that I misinterpreted the documentation. Although I had only `pdftotext` & `exiftool` installed, I hoped that `ug+` still worked, only without using some kind of advanced filters. Then I tried the `ug --filter=pdf ...` example, and was surprised that it worked. Only `ugrep` didn't display the pdf page numbers of the found matches, and sometimes even not the file name of the matches ! Using option `--with-filename` solved the last issue, but I couldn't find any reference in the `ugrep` or `pdftotext` documentation about the first problem. So I uninstalled `ugrep`.

After successfully annoying some innocent passersby because of my lost time, I re-installed `ugrep`. This time after installing the missing `pandoc` & `antiword`, with the false hope to get the `ug+` and `ugrep+` commands to, at least, shorten the long filter options to avoid many new aliases. Searching the web-page and [issues](https://github.com/Genivia/ugrep/issues) again didn't help. The `ug --filter=pdf...` example showed the same results as without `pandoc` and `antiword` installed. Maybe I understand it after reading the whole web-page but I'm sure that my psychotherapist will get serious problems if I, after 190 times pressing page-down, discover that `ugrep` is not the right tool for me. So I uninstalled `ugrep` again, installed `pdfgrep` and finished my orginal task.

p.s.
- Why is: `ProTip try --help help ...` a tip if it only shows
> Options and arguments:
> --help [WHAT], -? [WHAT]
> Display a help message, specifically on WHAT when specified.

> Other options:

> -Q[DELAY], --query[=DELAY]
> Query mode: user interface to perform interactive searches.
> ... more text ...

The text below it doesn't make evident if the `-Q` option is relevant for help and distracting, even disturbing because it spend one sentence about response time, which is absolutely not enough to know why I should worry or search for info about it.
- What is it with all the lightbulbs ProTip's ? Are they usefull when only in the introduction and not after the real explanations ?
- I don't know how I did it but I first posted this in [Discussions](https://github.com/Genivia/ugrep/discussions), and got a 404-page when trying to re-open it. That why I changed it in an issue. Sorry that it is so long because I find it hard to express myself in English. It is not a payback for the long README ;)

**Comment by genivia-inc** [comment]
Using ugrep 3.3.3? Well that version is old!

Perhaps you want to upgrade and then check again.
