### ISSUE TITLE
Some regex don't work

### ISSUE THREAD

**Issue by damanis** [Genivia/ugrep#273]
**Reproduce**:
- clone nodejs project `git clone git@github.com:nodejs/node.git`
- run `ugrep 'emit.*\bfinish\b' -t js`
**Current output**: empty
**Expected output**: same as `rg 'emit.*\bfinish\b' -t js`

**Comment by genivia-inc** [comment]
Use `ug --help regex` to list the patterns that require option `-P`. It's documented.

Sorry, but you must us option `-P` to use `\b` within regex patterns. There should be an error message. Will look at it to produce a warning/error in this case.

A few anchor and boundary patterns cannot be used _inside_ regex, but only work at the _start and end_ of a regex in POSIX regex patterns (the default). These are `^`, `$` (both are obvious!), `\b`, `\B`, `\<`, `\>` and lookahead/lookbehind patterns.

**Comment by genivia-inc** [comment]
I should mention that handling `\b`, `\B`, `\<` and `\>` within a regex (not only at the start and end of a regex) is on the TODO list of features to add to ugrep and to RE/flex. For now, these have limitations, unless option `-P` is used. Working on other cool new features right now.

**Comment by genivia-inc** [comment]
I've implemented an update that handles word boundaries within regex patterns. The boundaries can be specified anywhere in a regex. However, backtracking to find alternative (longer) matches is limited, so it's not as powerful as Perl matching with boundaries that always backtrack until a match is found (which can be inefficient).

The update will be included in the next release cycle, probably v4.2 (or v4.1.1).

**Comment by genivia-inc** [comment]
And the good news is that I got this to work with fuzzy regex search too!
