### ISSUE TITLE
[FR] interactive headless mode

### ISSUE THREAD

**Issue by nkh** [Genivia/ugrep#281]
- Add the possibility to run without generating any output until some commands are issued

- The caller can redirect stdin and stdout which can be used to communicate

# use case 1:

start a uc process in the background and reuse it the process without having to pay for fork time, Often when the search targets are small the startup time take a significant percentage of each call specially if many libraries needs loading

w3mimagedisplay uses this kind IPC

# use case 2:

regexp/fuzzy process for front end (I've seen the discussion about extra pane and I'll join there)

when the front end is dynamic, the search results need to be kept (which you already do with -Q I believe) but often only part of the results (a page worth) are needed in the front end

**Comment by genivia-inc** [comment]
For use case 2: this is already done with `-Q`.

The search results are kept with `-Q` and only the first two/three screen fulls are produced by ug when searching. Then ug waits until you type a key command or scroll down to see more. It is an incremental process already to reduce CPU cost.

**Comment by genivia-inc** [comment]
For use case 1: I don't know why this is necessary, because ugrep `-Q` does not do forks. Ugrep is the main running process and spawns threads to search. The threads join when the search is completed or cancelled (e.g. to start a new search).

A fork is used by ugrep with the optional `--filter` to pre-process files to search, e.g. PDFs, docs etc. There is not much that can be done here to optimized, since there is no simple way to do IPC with these third-party tools (or whatever we want to use as a filter).

**Comment by genivia-inc** [comment]
This should answer your questions.

**Comment by nkh** [comment]
I wasn't clear enough it seems , so none of my questions are really answered. I try again.

- case 1 was partially answered in the other issue, results are not kept and searches start again from the beginning. even in that case there's no interaction, ie the number of files already processed, the number of search result, ... I'm thinking reuse and integration, which are also missing from other grep like tools except FZF

- case 2, not the UI you put on top of ug but a UI a user would write that would use ug in the background. 

You see ug in the perspective of ug being **the** program to run when I have the perspective of another program being in the front and *ug* being a library albeit one with a CLI interface.

I put a graph in #254 , that should make my point of view clearer.

**Comment by nkh** [comment]
I KNOW HOW A FILE CACHE  WORKS THANK YOU. 36 year in the industry and teaching. YOU are missing the point probably because you are concentrating on what you do and not listening to what other look for but I may have misunderstood "listen to users to continue to add new and updated features"

Let gather the points then we can maybe stop with the unnecessary uppercases.

- The UI realm is not the same thing as the search efficiency realm, you have a hammer not everything is a nail.

- it's not about what's in the FILE CACHE or not but about NOT having to handle a file AT ALL, that is the main point and that means that the result don't have to be computed again since they are already known, CACHING THE RESULTS, redoing something that doesn't need to be done is about the least efficient things to do, talking about it is the only thing less efficient.

- you ask why one would have an architecture, you deem less efficient, to work with other tools rather than YOU do it all monolithic, and efficient. Seriously, consider your question again, or I'll just accept that you want to be in your corner of the search domain and do it all in one block, that's also fine but as far from the Unix spirit as it can be.

You have a nice evening.

**Comment by genivia-inc** [comment]
So you state that you only tried ugrep for one minute see #282.

Then you claim you know all about it and what I should do differently, when it actually already does what you suggest.

It seems to me you do not know what you are talking about.

Please do not harass people with questions without some effort to read and understand. 

Then after explaining it again with a factual answer how ugrep works you repeat the same questions.

You give me no information what machine/OS you are using.

And now you make claims that "CACHING THE RESULTS" is needed, when the results will actually change with each keypress to update the pattern or options. Polling the terminals (windows) and cursor movements and scrolling will not change results, thus will not do a new search.

How difficult is this to understand? For someone with 36 years experience?

BTW. I started coding in the early 80s. But does that matter? I only count professional years at work.

**Comment by nkh** [comment]
You obviously are not well as your behavior is not normal.  I hope you get better.

**Comment by genivia-inc** [comment]
Look, if you want a "headless" search engine, why don't you write one yourself? I'd start adding sockets or named pipes and a xfer protocol to fork or create a deamon app to accept requests and return results. Or start with GNU grep. It's all open source.

Don't force your ideas on projects without doing some research up front, knowing the limits of the current state-of-the-art and by presenting convincing use cases.

Want a new feature? Show a compelling use case or better: several use cases. I don't see the point of a headless ugrep engine without a convincing use case.

The concept could also be risky. Opens up potential security hazards when the IPC/sockets/pipes are not restricted to trusted clients (perhaps only the forking process of course). It would be the ideal tool for hackers to get access to someones files if such a ugrep engine runs in the background that can be accessed by a hacker via a xfer protocol.
