### ISSUE TITLE
ugrep does not warn if searching a directory

### ISSUE THREAD

**Issue by fazalmajid** [Genivia/ugrep#283]
The behavior of ugrep is subtly different from GNU grep and ag when the search target is a directory:

```
ragnarok ~/build>ug getDirent node-v20.5.1
ragnarok ~/build>grep getDirent node-v20.5.1
grep: node-v20.5.1: Is a directory
ragnarok ~/build>ag getDirent node-v20.5.1
node-v20.5.1/test/parallel/test-fs-utils-get-dirents.js
5:const { getDirents, getDirent } = require('internal/fs/utils');
20:// getDirents
23:  getDirents(
...
```

As a new ugrep user, I would suggest either warning as GNU grep does, or implicitly setting `-r` if the target is a directory rather than silently ignoring it.

**Comment by genivia-inc** [comment]
Thanks for the feedback.

This is something that I commented on before, that ugrep considers a directory on the command line as a target to search at one level deep, like `ls` does and some other unix utilities do as well.

If you don't want that, use `-dread`. To make this permanent with the `ug` command, add this line to .ugrep:
~~~
directories=read
~~~
This changes the default to warn.

Hope this helps. If something isn't working as expected, please let us know.

**Comment by genivia-inc** [comment]
See also #270

**Comment by genivia-inc** [comment]
I will add a new item to the list of "search targets" in the .ugrep config file saved with option `--save-config` to alert users that this is possible. The line added to .ugrep allows the user to enable warnings by uncommenting the line:
~~~
# Warn when searching directories specified on the command line (like grep) with directories=read
# directories=read
~~~

**Comment by genivia-inc** [comment]
The v4.0.4 release saves a config file with `ug --save-config` that includes this line as a hint to edit if desired.
