### ISSUE TITLE
Pager starts before command line parsing is done

### ISSUE THREAD

**Issue by walles** [Genivia/ugrep#285]
Tthis happened for me on macOS with `ugrep 4.0.4 x86_64-apple-darwin22.4.0 +avx2 +pcre2jit +zlib +bzip2 +lzma`.

```
~ $ ug --pager=date '[' /dev/null
ugrep: error: error at position 5
(?m)[
     \___mismatched [ ]


Sön 27 Aug 2023 07:58:35 CEST
~ [2]$
```

# Expectation

Since regex parsing fails, there's no value in starting the pager.

And the pager started, as can be seen by the current timestamp being printed.

# Note

Reported here: https://github.com/walles/moar/issues/149

Kindly don't start the pager if command line parsing fails!

**Comment by genivia-inc** [comment]
Thanks for the feedback to help make ugrep better!

I agree! I never noticed this before. It's an oversight on my part. Even with `--pager` which uses `less -R` by default, the error shows up without `less` complaining or otherwise waiting, so we never noticed it as a problem.

**Comment by genivia-inc** [comment]
Problem fixed. The fix will be released with the next release cycle in 3 weeks or about, so will keep this open until then.

Thanks for reporting this problem!
