### ISSUE TITLE
Bug: Invalid Syntax when specifying negative PATTERN

### ISSUE THREAD

**Issue by anotatta** [Genivia/ugrep#293]
I got an invalid syntax when specifying negative PATTERN (-N option) with Perl Regex (-P option).

(?m)(?^PATTERN)|^(\d+)
      \___invalid syntax

It works fine with default regex (not -P option).
I think it is because with -P option, it should be (?m)(?!PATTERN)|^(\d+)

**Comment by genivia-inc** [comment]
The -P option does not support negative patterns. The -P option uses PCRE2, which makes it difficult to implement negative patterns, unfortunately. There is possibly a complicated way this can be done by using group captures to find what patterns should be ignored/negated, but it's not been proven that avenue is guaranteed to work in all use cases and scenarios of regex patterns.

Ugrep should report a more informative error message when -N is used with -P. I will look into that for the next release.

**Comment by genivia-inc** [comment]
Let me add that I had hoped to implement negative patterns with PCRE2 e.g. by using negative lookahead/lookbehind hacks. But that approach is not trivial and doesn't work in general. For example, `ug -e '[0-9]+' -N 123` is not the same as the PCRE2 regex with a negative lookahead `(?!123)[0-9]+` or with a negative lookbehind `[0-9]+(?<!123)`. These still partly match `123` (the first matches `23` and the second matches `12`).
