### ISSUE TITLE
Simple search fails

### ISSUE THREAD

**Issue by damanis** [Genivia/ugrep#294]
Usually, work properly, but, for example:
```
λ ug --version
ugrep 4.0.5 x86_64-pc-linux-gnu +avx2 +zlib +bzip2
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
λ ug -w xset GNUstep/
λ rg -w xset GNUstep/
GNUstep/Library/WindowMaker/autostart:20:1:xset r rate 300
GNUstep/Library/WindowMaker/autostart:21:1:xset m 20/10 4
```

**Comment by genivia-inc** [comment]
You forgot to use option -r to recurse deeper in GNUstep.

When a directory is specified on the command line, it is searched at one level deep, just like `ls` lists the contents of a directory but not deeper into subdirectories or symlinks to directories. Specify -r or -R to do that, or -2, -3 ... to specify a max depth.

Only if you do not specify any targets to search, then recursive searching is done as if -r was specified.
