### ISSUE TITLE
Feature idea: Jump to line

### ISSUE THREAD

**Issue by leahneukirchen** [Genivia/ugrep#296]
From the interactive mode, ^Y opens the file in a pager or an editor, however you lose track of the search result.

Most Unix pagers and Editors (less, vim, emacs...) support being called like `program +NNN file` to jump to line NNN, this would simplify use a lot.

**Comment by genivia-inc** [comment]
That's a great idea.

It is not that simple to implement though, because the TUI has no concept of line numbers of the matches. A simple implementation can take the line number shown on the screen if `-n` is active. This is the only clue we can use. It won't work if `-n` is not active, or if `-l` or `-c` are active.

**Comment by leahneukirchen** [comment]
If it only works with -n, that's good enough for me.

**Comment by genivia-inc** [comment]
I've implemented this feature in my dev version. Some pagers do not support `+linenum` such as `moar` see #286 where I added a comment about this.

So we have two choices:

1. always add `+linenum` regardless of the pager specified, but this may not start the pager if the pager like `moar` returns an error.
2. only add `+linenum` when the pagers are `more` or `less` or `vi` or `vim` or `emacs`

I prefer 2 which is safe, so I'll include this in the next release.

**Comment by leahneukirchen** [comment]
More tools that do it: most, w3m, pico, nano, joe, zile, vile, mg, mcedit, vis, kak... :)

**Comment by genivia-inc** [comment]
OK, ok... got it!

**Comment by walles** [comment]
> More tools that do it: most, w3m, pico, nano, joe, zile, vile, mg, mcedit, vis, kak... :)

Out of curiosity @leahneukirchen, how did you come up with that list?

**Comment by leahneukirchen** [comment]
My thinking of every editor I had here and trying. ;)

Notably, helix doesn't support it (but I'll file a bug).

**Comment by genivia-inc** [comment]
Implemented in ugrep v4.2 (released).
