### ISSUE TITLE
[FR] support Brotli

### ISSUE THREAD

**Issue by genivia-inc** [Genivia/ugrep#312]
Support searching Brotli-compressed files, suggested in #254 by @GwynethLlewelyn

https://github.com/google/brotli

**Comment by GwynethLlewelyn** [comment]
\o/
Thanks so much!

**Comment by genivia-inc** [comment]
> \o/ Thanks so much!

You're welcome. Available in the updated repo and will be released with the official v4.3.3 update soon.
