### ISSUE TITLE
Using `-o -CN` mixes `:` and `+` delimiters

### ISSUE THREAD

**Issue by postsolar** [Genivia/ugrep#317]
If I do
```shell
> ug -o -C20 -Ink pattern --color=always
```
I will get lines with `:` and lines with `+` used as delimiters, which doesn't compose well with other tools like fzf.

My suggestion: add an option to explicitly set the delimiter.

**Comment by genivia-inc** [comment]
The default `:` delimiter is changed with `--separator=xyz`. Same as GNU grep. This option replaces the default `:`, `+` (same line) and `|` (match spans multiple lines) separators with the specified `xyz` string.

**Comment by postsolar** [comment]
I saw this flag, but it gave me errors, so I assumed it's not what I'm thinking it is. Now after this sanity check I understand I've been using it like `--separator 'xyz'`, without the `=`. Thank you!

**Comment by genivia-inc** [comment]
You may want to specify `separator=xyz` in your .ugrep file to permanently change it, if that's what you prefer.

**Comment by genivia-inc** [comment]
I'm thinking that `+` should be removed as a separator and just be a `:`. Ugrep should be compatible with GNU grep without requiring a `--separator`. The `+` isn't all that useful actually, since it was just meant to be a minor visual aid. Will consider removing `+` in the upcoming release cycle.

**Comment by postsolar** [comment]
Makes sense — the visual aid is already provided by ellipses.
