### ISSUE TITLE
[question] Un-ignore flag?

### ISSUE THREAD

**Issue by wavexx** [Genivia/ugrep#342]
Coming from ripgrep, I'm wondering if there is a way to quickly reset the "ignore" rules with a command flag? (same as ripgrep's -u flag, for example).

I'm using a couple of "ignore-files" rules in my `.ugrep` config, which are helpful to exclude non-interesting things in a project. Occasionally though I want to search for all files and drop any previous ignore rules, but still preserve my other options in `.ugrep`.

ripgrep offers the "-u/--unignore" flag, which when used once resets the ignore list, repeated also searches for hidden files, exactly for this sort of usage scenario.

Is there something similar in ugrep?

**Comment by genivia-inc** [comment]
Thanks for asking. You can undo the `--ignore-files` options with `--no-ignore-files`, when specified after. Most long options permit a `--no-` to disable. It's a bit longer to type than a short option.

If you've specified `ignore-files` in .ugrep and want to override it in specific directories to search from, then `ug --no-ignore-files --save-config` will save a .ugrep locally without the `ignore-files`. This local .ugrep will be used when executing `ug` from that directory as the PWD.

Or perhaps create an alias to add to your .bashrc to run ug with `--no-ignore-files`, like `alias ugall 'ug --no-ignore-files'`.

**Comment by genivia-inc** [comment]
I've added a sentence _"Long options may start with `--no-' to disable, when applicable"_ when executing `ug --help OPTION` as a reminder.

I agree that typing `--no-ignore-files` is a bit long. By comparison, enabling searching hidden files is just `-.`. Perhaps there is room for a short non-letter option like `-:` to override all .ugrep specified-options all at once. If there is sufficient enthusiasm for this then I'll be happy to add it. It will help in cases where you don't want to figure out what was set in a .ugrep file.

What do you think?

**Comment by wavexx** [comment]
The extra clarification in the manual is nice.

What was surprising to me, is that the --include/exclude doesn't seem to affect --ignore-files, maybe that should be clarified as well. I kind of expected patterns/globs to have a single map internally.

What I like about rg' "-u" option is that very often when used with --ignore-files (and other exclude rules), you're deliberating ignoring sizable chunks of a project because there's _usually_ stuff you don't want to see most of the time. But sometimes, you search for something and you _expect_ results and you suspect you're hiding it due to some exclusion, which you don't know. In some project it might be a hidden configuration file (.github to name one which would require -.), some generated makefile (via .gitignore..), maybe an exclude glob in .ugrep. So which one do I toggle to be sure I'm not ignoring anything? rg repeating -u progressively unignoring stuff does answer this pretty well. Which stuff is unignored first is debatable (depends on what you're doing), but I know that after 3 I'm searching _everything_.

I'm mentioning this because I was using the ack-grep/silversearcher before, and due to this I frequently resorted to plain "grep" when I was in doubt some of my exclusions could ignore stuff I was _expecting_.

It's also true I could just add a shell alias to unexclude all options, but appending -u to the current line is very ergonomic..

**Comment by genivia-inc** [comment]
I exactly understand that when we are in doubt we want to search all files, for example after nothing is returned as a match, but we expected something nonetheless or we want to make sure nothing matched. Searching all files will give this assurance that nothing was found.

How about:
~~~
    --all-files, -@
            Search all files: cancel the specified file and directory search
            restrictions (file and directory types, inclusions and exclusions),
            and cancel --ignore-binary and --ignore-files when specified.  Note
            that hidden files and directories are never searched, unless option
            -.  or --hidden is also specified.
~~~
This new option gives some flexibility with respect to hidden files. The really search everything, use `-@.` (`--all-files --hidden`).

I deliberately picked `@` ("at") which is hopefully easier to remember as a short option associated with `--all-files`.

**Comment by wavexx** [comment]
I personally like how this would work. Maybe we want to see if somebody else has some extra opinion on the behavior?

**Comment by genivia-inc** [comment]
Ping @leahneukirchen @pikumar @stephentalley if any of you is interested in following this discussion and perhaps comment on a new `-@` (`--all-files`) option as described above.

**Comment by leahneukirchen** [comment]
Sounds useful this way!

**Comment by genivia-inc** [comment]
About `-@`: as much as I would like to use a single letter short option for this, there are no single letters unassigned that we can use.

Also, in my opinion, using a special character like `-@` should be OK because it suggest this is a special option i.e. with behavior that is a bit different than the usual way options work. In this case with `-@`, all file selections before ("to the left" on the command line) are ignored, while all file selections after ("to the right" on the command line) are respected. This is not typical for (short) options.

**Comment by wavexx** [comment]
> In this case with -@, all file selections before ("to the left" on the command line) are ignored, while all file selections after ("to the right" on the command line) are respected. This is not typical for (short) options.

I would consider this typical? I didn't really see this difference between short/long options "in the wild".

Generally the rightmost argument always overrides a previous one (incidentally, this is what allows shell aliases to work ok, as you can override previous behavior).

**Comment by genivia-inc** [comment]
> Generally the rightmost argument always overrides a previous one (incidentally, this is what allows shell aliases to work ok, as you can override previous behavior).

True, but surely not all options behave that way. Most options are orthogonal, complimentary, like `-n`, `-b`, and `-k`, `-o`. Some options like `-G`, `-F`, `-E` and `-P` are conflicting (and `-q`, `-l`, (ell) `-c` are too, but stay silent). Some options can be repeated, "pile on" as it were, like `--include` and `--exclude`. And some options switch modes, like `-I`, `-a`, `-W` and `-X` that change `--binary-files=TYPE` so that they do not conflict and can change the way binary files are processed in this case. This latter form overrides the previous mode.

The `-@` option is like a kill switch for all previous options that affect file and directory selections.

**Comment by genivia-inc** [comment]
Working on finalizing version 5 to include this improvement. Version 5 has a regex engine revision to increase search speed, which takes time to verify and test.

**Comment by genivia-inc** [comment]
I will name the new option `--all` with short option `-@`. We like `--all` better, because it removes restrictions from searching files and directories (not just files that `--all-files` perhaps would suggest).

The new option will be available with version 5 to be released very soon.

**Comment by genivia-inc** [comment]
Implemented.
