### ISSUE TITLE
[FR/Q] How do I use `ugrep` as a library in C++?

### ISSUE THREAD

**Issue by NightMachinery** [Genivia/ugrep#345]
I like to add `ugrep` as an option for "fuzzy" finding to https://github.com/ahrm/sioyek/issues/567 . The code currently does this:
```cpp
int score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(s1, s2));

return score > 50;
```

where `s1` is the pattern and `s2` is the string that I want to check for a match. I like to do this match using `ugrep --bool --smart-case`. Can I do this without calling a subprocess?

PS: [Complete code snippet](https://github.com/nightmachinery/sioyek/blob/backspace_delete/pdf_viewer/ui.cpp#L117):
```cpp
bool MySortFilterProxyModel::filterAcceptsRow(int source_row,
	const QModelIndex& source_parent) const
{
	if (FUZZY_SEARCHING) {

		QModelIndex source_index = sourceModel()->index(source_row, this->filterKeyColumn(), source_parent);
		if (source_index.isValid())
		{
			// check current index itself :

			QString key = sourceModel()->data(source_index, filterRole()).toString();
			if (filterString.size() == 0) return true;
			std::wstring s1 = filterString.toStdWString();
			std::wstring s2 = key.toStdWString();
			int score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(s1, s2));

			return score > 50;
		}
		else {
			return false;
		}
	}
	else {
		return QSortFilterProxyModel::filterAcceptsRow(source_row, source_parent);
	}
}

void MySortFilterProxyModel::setFilterCustom(QString filterString) {
	if (FUZZY_SEARCHING) {
		this->filterString = filterString;
		this->setFilterFixedString(filterString);
		sort(0);
	}
	else {
		this->setFilterFixedString(filterString);
	}
}

bool MySortFilterProxyModel::lessThan(const QModelIndex& left,
	const QModelIndex& right) const
{
	if (FUZZY_SEARCHING) {

		QString leftData = sourceModel()->data(left).toString();
		QString rightData = sourceModel()->data(right).toString();

		int left_score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(filterString.toStdWString(), leftData.toStdWString()));
		int right_score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(filterString.toStdWString(), rightData.toStdWString()));
		return left_score > right_score;
	}
	else {
		return QSortFilterProxyModel::lessThan(left, right);
	}
}
```

**Comment by NightMachinery** [comment]
BTW, this application would benefit from being able to sort the results so that "better" matches are on top. I don't think `ugrep` can expose such a score?

```cpp
int left_score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(filterString.toStdWString(), leftData.toStdWString()));
int right_score = static_cast<int>(rapidfuzz::fuzz::partial_ratio(filterString.toStdWString(), rightData.toStdWString()));
		return left_score > right_score;
```

**Comment by genivia-inc** [comment]
Please take a look at this project: [FuzzyMatcher](https://github.com/Genivia/FuzzyMatcher). The fuzzy matcher is also included with [RE/flex](https://github.com/Genivia/RE-flex) which in turn is included in ugrep. For case-independent matching and Unicode support, you want to use the regex converter and pass the converted regex string to the fuzzy matcher for matching. There are [examples](https://github.com/Genivia/FuzzyMatcher#full-unicode-support) that show how to do that and use `(?i)PATTERN` to make `PATTERN` match case insensitive. The fuzzy matcher has an `edits()` method that returns the edit distance of a match, after matching.

**Comment by NightMachinery** [comment]
@genivia-inc Do these libraries support `--bool` syntax?

**Comment by genivia-inc** [comment]
> @genivia-inc Do these libraries support `--bool` syntax?

No. The `--bool` syntax is layered on top, using CNF normalization in `ugrep/src/cnf.cpp` and by using multiple matchers, one for each term in the CNF. E.g. `a(b|c)` is normalized to `(a|b)(a|c)` for which two (fuzzy)matchers are created for patterns `a|b` and `a|c`. Both patterns must match (on the same line or anywhere in a  file with `--files`).
