### ISSUE TITLE
option -z is problematic -- what if I want to search a string inside a .gz but not in a file inside a .tgz?

### ISSUE THREAD

**Issue by schwidom** [Genivia/ugrep#351]
I found no other option to do that. -z makes too much. It could be split in --zfile and --zarchive to have a clear distinction.
And just in case -- what if an an archive contains more zipped files and archives? Then a recursion delimiter woud also be interesting.

Thanks in advance.
Frank Schwidom

**Comment by genivia-inc** [comment]
Not sure what you mean or want. Option `-z` is limited to one level of archives and compressed files. To search nested archives specify `--zmax=2`. If you want to search a string in a raw binary .gz file then don't use option `-z`. If you want to search a .gz but not a .tgz then exclude .tgz from searching with `-O^tgz` or `-g"^*.tgz"`.

**Comment by schwidom** [comment]
Lets say I want to search a string in all files which begin with the literal 'Packages' in a debian repository. So I would search by: 'ugrep packagename -z --include="Packages*" '. But then ugrep also opens tgz files which are not match the "Packages*" pattern and this is not my intention. Obiously ugrep tries to find further 'Package*' files inside of the archive which is already a recursive step more. So it would be better to have an option to do this more precise.

**Comment by schwidom** [comment]
Ok, I missed zmax in my version of ugrep.

**Comment by genivia-inc** [comment]
See also #359 which asks a similar question with my answer to use `xargs`.
