### ISSUE TITLE
Silencing "unnecessary" messages

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#352]
One routine ... dislike I have with `grep` is:

When I search `/` without `sudo`, I get a barrage of

```
ugrep: warning: cannot read /run/systemd/journal/streams/8:62791: Permission denied
```

messages. I understand the usefulness, the utility, and the reason for those messages.

... but they mess up my "expectation" that output is only what I am searching for (or nothing).

Can we "somehow" do so that those messages come "after" `ugrep` is done? or "just" as a summary?

```
ugrep: warning: cannot read 1347637 files: Permission denied
```

**Comment by genivia-inc** [comment]
These messages can be silenced with `-s`. Also specify `--stats` to see a report with the number of warnings generated (but not displayed).
