### ISSUE TITLE
omit line numbers for stdin

### ISSUE THREAD

**Issue by dicktyr** [Genivia/ugrep#356]
it seems reasonable to omit line numbers for stdin when specified as: `--pretty=auto`

**Comment by genivia-inc** [comment]
Thank you for your feedback. I'm not sure if everyone agrees. You can override `-n` with `--no-line-number` or use `ugrep` with the options you want.

**Comment by dicktyr** [comment]
`--no-line-number` appears to be undocumented

in any case, I generally *do* want line numbers for regular files but not for stdin by default

I presume most users agree, and since ugrep is already detecting context, it seems superfluous to create a wrapper script to (un)set options

**Comment by genivia-inc** [comment]
This is documented. Most option have `--no-` variants. This is clearly mentioned in the man page and also mentioned every time in `--help OPTION` at the bottom. It is also mentioned on ugrep.com in the section heading just below "Options".
