### ISSUE TITLE
How to use ugrep instead of grep with git

### ISSUE THREAD

**Issue by jcubic** [Genivia/ugrep#357]
Is there a way to replace `git grep` with ugrep? I'm just testing this tool and most of the time I use grep with git command. If you know how I would add this to README.

I also asked on StackOverflow: [Is there a way to replace grep in git with a different grep tool?](https://stackoverflow.com/q/78009349/387194)

**Comment by genivia-inc** [comment]
I'm curious what made you ask? Note that git grep is integrated into and managed by the git architecture. On the other hand, if you are recursively searching files in a local git repo on your file system then other grep will work just fine. With `ug` you want to specify `--ignore-files` to respect git exclusions. Make this automatic by adding `ignore-files` to your .ugrep config file. Also logical search queries (AND OR NOT) can be specified with `ug`, kind of like git grep, but a lot easier with option `-%` (logically match lines) and `-%%` (logically match files). See `ug --help bool` for details on this topic. Hope this helps.
