### ISSUE TITLE
[FR] Accept Ctrl^\ Keystroke in the ugrep -Q mode

### ISSUE THREAD

**Issue by cdluminate** [Genivia/ugrep#36]
I just noticed that it's not quite convenient to quit from the `ugrep -Q` mode fastly. `ugrep -Q` does not accept the `Ctrl^C` keystroke (`SIGTERM`) and that fine. But I think it should support the `Ctrl^\` keystroke (`SIGQUIT`). Being able to quit from the interactive mode is helpful for faster interaction.

Thanks for the awesome tool.

**Comment by genivia-inc** [comment]
Thanks for the feedback! Perhaps CTRL-\ could be an alternative to ESC. Some tablet keyboards don't sport an ESC key (damn iOS!). So having an alternative for ESC is a functional addition.

In the next release cycle we will be mapping CTRL-C to terminate ugrep without producing output, similar to `SIGINT` or `SIGTERM`.

**Comment by genivia-inc** [comment]
See #30.
