### ISSUE TITLE
inquiry on saving the output interactive

### ISSUE THREAD

**Issue by charulix** [Genivia/ugrep#379]
Question

ug -Q (interactive mode),

1. Was wondering how do we save the output in colour to clipboard so we can paste it in words/powerpoint with the colours. or is there a html options with the coloured fonts?

^Q quit and output but do not know how to use this if it can output in colour

2. M-$ [ ] sort by changed
Is it possible to run the interactive mode with sort by changes as default. Please help to show if yes.

thank you.

**Comment by genivia-inc** [comment]
OK, I will try to answer:

1. right before you quit the TUI, first type ENTER to enter "selection mode" and press `A` for select All, then quit. This produces the output in your terminal, which can be copy-pasted (more easily than in the TUI.)
2. "sort by changed by default" can be specified on the command line with `ug -Q --sort=changed`. If you use this a lot, then perhaps define an alias such as `alias  uqc='ug -Q --sort-changed'`.

Note that the TUI "quit & output" only outputs the selections you've made in "selection mode" with ENTER. Press ENTER to select a line and DEL to unselect.

**Comment by genivia-inc** [comment]
Note that the TUI output can be redictected to a clipboard tool, like this with `xclip` on Linux:
```console
$ ug -Q | xclip -sel clip
```
On MacOS:
```concole
$ ug -Q | pbcopy
```

**Comment by genivia-inc** [comment]
On the subject of converting terminal output with ANSI escapes to HTML, this [ansi2html.sh](http://www.pixelbeat.org/scripts/ansi2html.sh) script mentioned in [this article](http://pablomarin-garcia.blogspot.com/2011/04/converting-ansi-to-html-how-to-convert.html) looks useful.

**Comment by genivia-inc** [comment]
Closing this as answered. I wish there were better tools to pass results to the clipboard, but it is what it is.
