### ISSUE TITLE
ugrep 5.1.3 FTFBS with musl

### ISSUE THREAD

**Issue by leahneukirchen** [Genivia/ugrep#381]
The patch a87445853c297551d49a993ff8b536d2b6c755bd introduced usage of `caddr_t` (not sure why, just using `char *` should work as well?), but it does not `#include <sys/types.h>`. Adding this include fixes build with musl.

**Comment by genivia-inc** [comment]
Thank you for your feedback. The `caddr_t` change was made for AIX. I will add sys/types.h. Thanks for reporting!

**Comment by genivia-inc** [comment]
<img width="578" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/9047c9a1-f450-495e-8de4-7f3f5ce54cc9">
