### ISSUE TITLE
easier windows install

### ISSUE THREAD

**Issue by rdp** [Genivia/ugrep#387]
Couple of things that would make it easier/nicer for windows users looking to install it.

1) on the main page https://ugrep.com/ for windows it says winget/choco/scoop but what I was looking for was the download option.  It gives the impression that there isn't one.  Maybe add a 4th option "download" for windows? :)

2) an install .exe option that could add it to the PATH.  Make it easy for me :)

Cheers!

**Comment by rdp** [comment]
Yeah...it's more for casual users who don't even know what winget/choco/scoop are (like myself)...

**Comment by FONZACUS** [comment]
imho its not needed, for old school guys its just downloading the bin from the releases here and plopping it to %path%
for good practices, make your own path elsewhere (like c://bin lol, like linux) and stuff em here

**Comment by rdp** [comment]
For the website I'd at least add "download" as an option for windows at the
left, it's not immediately clear there, depends on what "level" of user you
want to support here, cheers!

**Comment by genivia-inc** [comment]
OK. But also the "6.0 release" link at the top of ugrep.com takes you to the GitHub release, from where to download ugrep-windows-x64.zip that has the binaries.

**Comment by rdp** [comment]
Right, it just wasn't clear from the left hand that ugrep installs on
"windows via download" ... :)

**Comment by rdp** [comment]
seeing this from fresh eyes again, the links to "winget" are nice now.
However I'd still like to see an option at the bottom "other windows" (like "other linux") download binaries :)

But as you like it, cheers!

**Comment by genivia-inc** [comment]
Downloading `ugrep-windows-x64.zip` from the release artifacts included with every GitHub repo release gives you `ugrep.exe`, `ug.exe` and `ugrep-indexer.exe` binaries.
