### ISSUE TITLE
Bash autocompletion performance

### ISSUE THREAD

**Issue by jack6th** [Genivia/ugrep#395]
ugrep 6.0 on Windows with MSYS2
ugrep is a very useful tool.  I often use it with bash autocompletion. 
I tried on an old laptop.
After I input ug --(press double TAB) I need wait more than 3 second to see the output 'Display all 117 possibilities? (y or n)'.
And I input ug --no(press double TAB) I also need more than 3 second to see the candidate option list.

While I input awk( or aria2c ) --(press double TAB) I can immediately see the bash autocompletion output.
How to make ugrep bash autocompletion faster ?

**Comment by genivia-inc** [comment]
The "usage" completions are produced from `$1 --help` where `$1` is the command e.g. `ug` or `ugrep`, which is then piped through `sed` to produce proper output. This might slow on old machines. Perhaps caching the output of `$1 --help` should improve performance. Or pre-generating the output. I'll look into that.
