### ISSUE TITLE
Compressed search is not multi-threaded

### ISSUE THREAD

**Issue by apprehensions** [Genivia/ugrep#403]
Use-case:
```
ugrep -z [pattern] chromium-125.0.6422.76.tar.xz 
```

**Comment by genivia-inc** [comment]
That is correct.

Searching inside a single tar is not multi-threaded. Searching multiple tars or other files is multi-threaded. A tarball is one sequential file without pointers to its contents to potentially distribute to threads to search in parallel. Only 7zip would potentially be searchable in parallel with multiple threads. Scanning the entire tar file first and then to send contents to threads would add too much overhead and slow it down.

Threads are used to search nested archives, but the search itself is not sped up in parallel.
