### ISSUE TITLE
ugrep --hyperlink unconditionally prepends CWD to hyperlinks of absolute paths

### ISSUE THREAD

**Issue by stephentalley** [Genivia/ugrep#412]
Running ugrep 6.2.

1. ugrep a matching pattern in any absolute path:

```
cd /tmp; ugrep --hyperlink -H a /etc/passwd /dev/null
```

2. Clicking /etc/passwd in the terminal launches a viewer for /tmp//etc/passwd. It appears that the hyperlinking code is assuming the file names are relative and appending the CWD, rather than leaving them as-is.

**Comment by genivia-inc** [comment]
Ah, that's easy to fix. Will be updated in 6.3.
