### ISSUE TITLE
ugrep -O sql doesn't seem to work in gitlab CI runners

### ISSUE THREAD

**Issue by ferdinandyb** [Genivia/ugrep#423]
This is likely not an issue with ugrep _per se_, but I was hoping you have an idea. I'm trying to run a simple `ugrep -O sql create` in gitlab's CI/CD. The command works on my computer (Ubuntu WSL), it works in alpine docker, but it does not work on the alpine or ubuntu images used by gitlab, rather they fail with an exit code of 1. I'm assuming this means it hasn't found any sql files.  On the other hand the files it should find are definitely there since ` find . -type f -name "*.sql"` yields all of them, so that shouldn't be the reason.

Any ideas? Is this a bug or is there something magic going on in a runner that may cause this issue?

**Comment by genivia-inc** [comment]
Apologies for the delay.

The `-O sql` option merely sets `-g"*.sql"` which is the same as `--include="*.sql"` to only search `sql` files. There is nothing special about it, other than traversing directories in recursive searches to only search the `sql` files when found in the directory listing. Are you sure you're doing a recursive search? Check with `--stats` and use `-r` explicitly when in doubt.
