### ISSUE TITLE
https://ugrep.com/ is down

### ISSUE THREAD

**Issue by runxel** [Genivia/ugrep#424]
Neither does [www.ugrep.com](https://www.ugrep.com/) work.

<img width="836" alt="grafik" src="https://github.com/user-attachments/assets/9d8f96a5-f2b3-4fa2-9836-8872d648571e">

**Comment by xrat** [comment]
Checked right now. Works for me!

**Comment by runxel** [comment]
Yeah it works again. 🥳

**Comment by genivia-inc** [comment]
Not sure what happened. The site is hosted on GitHub pages, so if GitHub goes down then ugrep.com goes down. Registration is for years to come. So no worries.
