### ISSUE TITLE
PAGER/VISUAL vs --view

### ISSUE THREAD

**Issue by Konfekt** [Genivia/ugrep#431]
Since the help/man page states that `--view` defines the `Ctrl-Y` binding, how about leaving the `F2` key bound to `${PAGER:-${VISUAL:-$EDITOR}}` so that a file can be quickly viewed and then opened if need be?

**Comment by genivia-inc** [comment]
Thank you for your feedback.

F2 is just the same as CTRL-Y in the TUI, but you can view a file with `less` and then edit it in `less` with the `v` command (press `v`):
~~~
NAME
       less - opposite of more

...

       v      Invokes an editor to edit the current file being viewed.  The editor is taken from the
              environment variable VISUAL if defined, or EDITOR if VISUAL is not defined, or defaults to
              "vi" if neither VISUAL nor EDITOR is defined.  See also the discussion of LESSEDIT under the
              section on PROMPTS below.
~~~
