### ISSUE TITLE
Alias conflict: pgrep is a commonly used process-grep utility

### ISSUE THREAD

**Issue by f440** [Genivia/ugrep#433]
Hi, thank you for the great work on ugrep!

I noticed that in the recommended aliases, `pgrep` is suggested for Perl regular expression searches:

```shell
alias pgrep  = 'ugrep -P'    # search with Perl regular expressions
```

However, pgrep is already a standard utility on Unix-like systems that searches for processes by name. It's part of the procps package and is commonly used in system administration and scripting.

To avoid confusion and potential issues, maybe we could consider an alternative alias name (e.g. plgrep) for the Perl regex functionality? 

What do you think?

**Comment by genivia-inc** [comment]
Ah, yes it makes sense to update the suggested aliases e.g. `pugrep` perhaps.

**Comment by genivia-inc** [comment]
Updated [README section](https://github.com/Genivia/ugrep#short-and-quick-command-aliases) with suggested aliases
