### ISSUE TITLE
The editor does not open and the program freezes

### ISSUE THREAD

**Issue by mrkingmidas** [Genivia/ugrep#438]
How to repeat in `cmd.exe`:
- `SET Editor=notepad.exe` or `SET Editor=micro.exe`
- run `ugrep -Q`
- Press `F2` or `Ctrl+Y`
- We see a black screen with a cursor and nothing else. Only closing the process helps. 
- But also after this the “arrows” do not work, `^[[D^[[A^[[C^[[B` are entered. `chcp 866` helps to get them back to work (this is the default for the system)

ugrep 7.0.3

Windows 10 21H1, ConEmu 230724, lang: ru, codepage: 866

**Comment by genivia-inc** [comment]
It works as tested on my Windows 11 system with ConEmu. I don't get what  and why a code page would change that.

**Comment by mrkingmidas** [comment]
The situation is more complicated - now I was looking for how to write an example and sometimes it still works.

The problem seems to be if run `ugrep -Q` and move only with the `Up/Down` arrows (without searching) and then press `F2`. Tomorrow I'll try to localize the problem situation.

**Comment by genivia-inc** [comment]
I tested this right now with ConEmu using `SET Editor=notepad.exe` then in the TUI press CTRL-Y to edit a large file.

This takes a second to start notepad. Notepad will pop up with the file just fine. After quitting notepad the TUI continues to work fine.

Note that _you must stop editing the file_ for the TUI to continue. Otherwise it will just wait with a black screen. This is normal.

The TUI checks if the file was changed after editing or viewing. If the file is changed, then a new search for that file will happen so the TUI screen is always up to date.

**Comment by genivia-inc** [comment]
We could output `Waiting on notepad.exe to finish` in the TUI screen to make it clear that the TUI needs notepad to end.

**Comment by mrkingmidas** [comment]
Using a build with a “code page” (the same on regular 7.0.3) I recorded a ![GIF](https://i.imgur.com/V3tU40v.gif)

Steps in ConEmu (in `cmd.exe` the same):
- `SET Editor=notepad.exe`
- `ugrep -Q` and search the text, then `F2` - we see `notepad.exe`. Also in task manager
- _Clear the search field_ and press `F2` - ugrep writes that it launches `notepad.exe`, but this is not in the task manager!

**Comment by genivia-inc** [comment]
Well, it works absolutely fine on my Windows 11 machine with cmd.exe and ConEmu using the v7.0.4 pre-update. Launching notepad.exe multiple times for files is OK. It doesn't matter if a pattern is cleared or a pattern is entered. I also tried editing the file and saving it, which also works fine.

I even tried with two ugrep instances running at the same time and then F2 in both to edit the same file. That works too, with the first ugrep just returning back and the second ugrep waiting for notepad.exe to finish. Not getting stuck.

To be perfectly honest, I am 100% convinced the logic in ugrep is correct, because `_wsystem()` is launched every time F2 or CTRL-Y is pressed, then ugrep just waits for notepad.exe to finish. It gets back exactly where it was or performs a new search if the file was changed.

If `_wsystem()` doesn't launch the specified notepad.exe command on your end, then something outside of ugrep's control must be wrong and there is nothing I can do about that that would change that.

**Comment by mrkingmidas** [comment]
> If `_wsystem()` doesn't launch the specified notepad.exe command on your end, then something outside of ugrep's control must be wrong and there is nothing I can do about that that would change that.

May be related to active non-English locale.
Now I tried to run `ugrep -Q` version 7.0.2 (before the appearance of `_wsystem`) and there calling the editor or the `more` command (with an empty `EDITOR` variable) work correctly!

**Comment by genivia-inc** [comment]
> Perhaps it has something to do with the contents of the files (or their display on the screen), since I also noticed that this does not happen on all files.

Does that also happen on your end when the viewer is `more` which is the default viewer?

**Comment by mrkingmidas** [comment]
> Does that also happen on your end when the viewer is `more` which is the default viewer?

Yes, demo on two files from source `LICENSE.txt` and `man.sh`, I am press `F2` or `Ctrl+Y`:

![example](https://i.imgur.com/8vPZSDh.png)

**Comment by genivia-inc** [comment]
Does it happen when you first `chcp 65001` and then run ugrep -Q?

**Comment by mrkingmidas** [comment]
> Does it happen when you first `chcp 65001` and then run ugrep -Q?

No, same effect of freeze.

----

Now I noticed something else: if in the same example of two files you scroll the screen to the end of the second file (using arrows or `PgDn`), then the second file also works and returning to the first using arrows too! But if you search for something and clear the search field, it hangs on `F2` again.

**Comment by genivia-inc** [comment]
I made a small change to the UTF-8 conversion, just to make sure it's not that. Try the updated [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

If not that, it might be something in the keyboard read logic to make it work with ConEmu (added to v7.0.3).

I don't have this problem you describe on my Windows 11 machine, making this a mystery as to what causes it.

**Comment by mrkingmidas** [comment]
> I made a small change to the UTF-8 conversion, just to make sure it's not that. Try the updated [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)
> 
> If not that, it might be something in the keyboard read logic to make it work with ConEmu (added to v7.0.3).
> 
> I don't have this problem you describe on my Windows 11 machine, making this a mystery as to what causes it.

This build also freezes :-(

And different options too:
- CP=866
- CP=65001
- `more`
- `SET Editor=notepad.exe`

**Comment by mrkingmidas** [comment]
> I made a small change to the UTF-8 conversion, just to make sure it's not that. Try the updated [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)
> 
> If not that, it might be something in the keyboard read logic to make it work with ConEmu (added to v7.0.3).
> 
> I don't have this problem you describe on my Windows 11 machine, making this a mystery as to what causes it.

Can you please put together a build with ConEmu modifications disabled (appearing in 7.0.3)?

**Comment by genivia-inc** [comment]
So it is not the UTF-8 logic, which makes sense. If v7.0.3 has the same problem then it is likely the ConEmu mod.

**Comment by mrkingmidas** [comment]
> So it is not the UTF-8 logic, which makes sense. If v7.0.3 has the same problem then it is likely the ConEmu mod.

Can you please put together a build with ConEmu modifications disabled (appearing in 7.0.3)?

**Comment by mrkingmidas** [comment]
> So it is not the UTF-8 logic, which makes sense. If v7.0.3 has the same problem then it is likely the ConEmu mod.

And I didn’t write before: closing `ugrep -Q` with such a freeze using `Ctrl+C` does not work. And `Ctrl+Break` works.

----

I ran today's tests only in `cmd.exe`

**Comment by genivia-inc** [comment]
> Can you please put together a build with ConEmu modifications disabled (appearing in 7.0.3)?

Try the [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

**Comment by mrkingmidas** [comment]
> > Can you please put together a build with ConEmu modifications disabled (appearing in 7.0.3)?
> 
> Try the [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

Also freeze on `F2` or `Ctrl+Y` 😥

**Comment by mrkingmidas** [comment]
> > Can you please put together a build with ConEmu modifications disabled (appearing in 7.0.3)?
> 
> Try the [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

Please, can you create build with rollback changes from [_wsystem](https://github.com/Genivia/ugrep/issues/436#issuecomment-2460404260) using old 7.0.2 code ?

**Comment by genivia-inc** [comment]
BTW, trying CTRL-S to scroll down to the next match does not work when CTRL-W works. This appears to be a problem described [here](https://stackoverflow.com/questions/39695431/ctrl-s-input-event-in-windows-console-with-readconsoleinputw). I've added `ENABLE_EXTENDED_FLAGS` which makes CTRL-S work again.

> Please, can you create build with rollback changes from https://github.com/Genivia/ugrep/issues/436#issuecomment-2460404260 using old 7.0.2 code ?

Sure.

**Comment by mrkingmidas** [comment]
> BTW, trying CTRL-S to scroll down to the next match does not work when CTRL-W works. This appears to be a problem described [here](https://stackoverflow.com/questions/39695431/ctrl-s-input-event-in-windows-console-with-readconsoleinputw). I've added `ENABLE_EXTENDED_FLAGS` which makes CTRL-S work again. It appears to be an [undocumented flag](https://stackoverflow.com/questions/76156132/non-documented-console-input-mode-flags) so I will test for any side effects.

It's strange, because in the latest builds on my system Ctrl+S works the same everywhere.

**Comment by genivia-inc** [comment]
> It's strange, because in the latest builds on my system Ctrl+S works the same everywhere in cmd.exe

Could be Powershell.

> Please, can you create build with rollback changes from https://github.com/Genivia/ugrep/issues/436#issuecomment-2460404260 using old 7.0.2 code ?

Try [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

This one omits `wsystem` to use `system` again. It also sets `ENABLE_EXTENDED_FLAGS` to make CTRL-S work. It includes the ConEmu mod.

**Comment by mrkingmidas** [comment]
> > It's strange, because in the latest builds on my system Ctrl+S works the same everywhere in cmd.exe
> 
> Could be Powershell.
> 
> > Please, can you create build with rollback changes from [#436 (comment)](https://github.com/Genivia/ugrep/issues/436#issuecomment-2460404260) using old 7.0.2 code ?
> 
> Try [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)
> 
> This one omits `wsystem` to use `system` again. It also sets `ENABLE_EXTENDED_FLAGS` to make CTRL-S work. It includes the ConEmu mod.

Works in `cmd.exe` and `ConEmu`! `Ctrl+S` also works. And non-ASCII filenames not work as described

**Comment by genivia-inc** [comment]
OK, if this latest version works then I wonder if the problem is actually caused by `_flushall()` which I've added with `_wsystem()` because the API doc mentions that `_flushall()` [is required](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/system-wsystem?view=msvc-170) before calling `_system()` or `_wsystem()`: _"You must explicitly flush, by using or, or close any stream before you call system."_

**Comment by genivia-inc** [comment]
One more version to try please. This one is without `_flushall()` but with `_wsystem()`: [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

**Comment by mrkingmidas** [comment]
> One more version to try please. This one is without `_flushall()` but with `_wsystem()`: [bin/win64/ugrep.exe](https://github.com/Genivia/ugrep/tree/master/bin/win64)

Hooray! Works!

- In `cmd.exe` and `ConEmu`
- `notepad.exe` and `more`

**Comment by genivia-inc** [comment]
Thanks for testing.

To summarize:
- the ConEmu mod works to ignore "key up" events for ANSI key codes such as cursor keys that generate multiple key down codes with `ENABLE_VIRTUAL_TERMINAL_INPUT`
- CTRL-S now works with `ENABLE_EXTENDED_FLAGS`, it wasn't working with Powershell on Windows 11 on my end
- `_wsystem()` invokes the specified `PAGER`, `VISUAL` or `EDITOR` environment variable or the `--view=COMMAND` option that takes precedence, the pathname of the file to view/edit is passed to the `COMMAND` in wide string format to allow non-ASCII filenames
- `_flushall()` has unintended consequences to freeze the TUI (and perhaps breaks other things), even though the `_system` and `_wsystem` documentation says that we must use it! All seems fine when we don't use it
- restore original code page on exit
- show "waiting on COMMAND to finish" in the TUI with F2 or CTRL-Y to avoid confusion when TUI is blank

I will release an official update v7.0.4 soon.
