### ISSUE TITLE
"Empty expression" error when using `\A` inside group

### ISSUE THREAD

**Issue by alvin55531** [Genivia/ugrep#439]
If I put `\A` inside a capture group or non-capture group, it'll give an error:
Command:
```
ugrep -P '(?:\A|.*Testword5)
```
(I have a file that contains "Testword5" for this test search)

Output:
```
ugrep: error: error at position 9
(?m)(?:\A|.*Testword5)
         \___empty expression
```

I've looked through the man page. The only thing that seems relevant is the `--empty` flag, but using it gives the same results.

**Comment by genivia-inc** [comment]
I should add that matching a single `\A` is not possible. Only the `^` and `$` anchors can be used to match without a pattern, but the `\A` and `\Z` anchors need a pattern as "context" to assert the begin-of-file match.

**Comment by alvin55531** [comment]
Thank you for the clarification! 

So the non-empty expression must be inside the capture group/non-capture group with the `\A`? So it has to be `(?:\A.*|.*Testword)` and not `(?:\A|Testword)someotherpattern`? 

Is this a limitation set by ugrep (perhaps for performance?) or a limitation of the regex engine ugrep uses. I tried the original regex (on Regex101) with PCRE2 and it would match successfully.

**Comment by genivia-inc** [comment]
This is to avoid confusion and problems, i.e. when `\A` does not match anything. This syntax check only applies to the regex syntax, not to its meaning. Regex can be arbitrarily complex, so an accurate check can only be done in the DFA but that is not useful to find the location in the regex that caused it and it won't work with option `-P` (PCRE2) that also does not produce the expected output for a sole `\A` without a pattern that follows it.

For regex like `(\A|aaa)bbb` one can also write `(\Abbb|aaabbb)` which is the same.

**Comment by genivia-inc** [comment]
> Is this a limitation set by ugrep (perhaps for performance?) or a limitation of the regex engine ugrep uses. I tried the original regex (on Regex101) with PCRE2 and it would match successfully.

Using a sole `\A` doesn't work with PCRE2 using ugrep option `-P` when I temporarily removed the limitation. PCRE2 only matches lines with "test" with the regex `(\A|test)`.

Therefore, disallowing a sole `\A` when not followed by a pattern prevents problems and confusion. Sure, something like `(\A|test)ing` should match `ing` at the start of a file, but this is the same as writing the regex `\Aing|testing. Any factored regex can be expanded this way and works with ugrep just fine.

**Comment by alvin55531** [comment]
For the time being, I have found a workaround, that is to wrap `\A` in lookbehinds. 

Instead of `(?:\A|test)ing`, use `(?:(?<=\A)|test)ing`. The latter appears to match what I'd expect from the former pattern. 

If your original pattern was something like this: `(?:\A|(?<=test))ing`, you could even simplify it to this: `(?<=\A|test)ing`.

Expanding it to `\Aing|testing` could work, but if the duplicated part of the pattern is longer, the overall pattern can get really long and annoying quickly.
