### ISSUE TITLE
exit code 2 due to ugrep: warning: cannot decompress unsupported compression format: tests/archive.tar.bz3

### ISSUE THREAD

**Issue by vt-alt** [Genivia/ugrep#448]
I tried to disable bzip3 support [because it does not compile anymore], but after this `ugrep -r -z` started to produce error exit code (`2`) related to a warning: `ugrep: warning: cannot decompress unsupported compression format: tests/archive.tar.bz3` (on test run ugrep source code).

Maybe it would be better to treat `unsupported compression format` as a binary file instead?

Now new compression formats (if in future) added to ugrep but not compiled in would cause unexpected error exit code, because there is such unsupported file (but supported for generating errors), this would cause some scripts to unexpectedly to fail (by a logic not based on matches found or not).

**Comment by genivia-inc** [comment]
I agree. It makes sense to not exit with code 2 in this case.

**Comment by genivia-inc** [comment]
Fixed in 7.1.2.

**Comment by vt-alt** [comment]
Thank you!
