### ISSUE TITLE
Hidden files ignored without --hidden even when given on command line

### ISSUE THREAD

**Issue by rrthomas** [Genivia/ugrep#45]
This is both unintuitive and not compatible with standard grep!

```
$ ugrep foo .bar
[exit code 1]
$ ugrep --hidden foo .bar
[matches displayed]
```

Thanks for ugrep, it looks really interesting, and I'm enjoying trying it out.

**Comment by genivia-inc** [comment]
Hiding hidden files by default is not only a popular feature, but in fact, common unix utilities like `ls` do the same. Grep is outdated by that standard and should follow modern conventions.

See the note in the README:

> ### Equivalence to GNU grep and BSD grep
> 
> **ugrep** accepts GNU/BSD grep command options and produces GNU/BSD grep
> compatible output, making **ugrep** an excellent drop-in replacement for grep
> power users.
> 
> GNU and BSD grep and their common variants are equivalent to **ugrep** when the
> following options are used (`-U` disables Unicode matching with UTF-8 patterns):
> 
> ~~~
>     grep   = ugrep --sort -G -U -Y -. -Dread -dread
>     egrep  = ugrep --sort -E -U -Y -. -Dread -dread
>     fgrep  = ugrep --sort -F -U -Y -. -Dread -dread
> ~~~
> [...] Option `-.` searches hidden files (dotfiles).

The installation has a `--enable-hidden` to make the latter permanent.

**Comment by genivia-inc** [comment]
So yeah, ugrep does what it says it does: not show hidden files unless you use `-.` or `--hidden`.

**Comment by genivia-inc** [comment]
For command line arguments that are hidden files, it might be better to always search them and not ignore them. That would be similar to utilities like `ls` that list them also. I'll updated this in the next release cycle.

**Comment by rrthomas** [comment]
Thanks for the response, and for the reminder of the compatibility flags. What I was trying to say is exactly what you said in your last comment!
