### ISSUE TITLE
Replacing `grep` with `ugrep` makes `./configure` fail

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#48]
_As shown in https://github.com/rocky/zshdb/issues/27_:

```console
$ git clone https://github.com/rocky/zshdb && zshdb
$ zshdb → λ git master → bat ./autogen.sh 
───────┬─────────────────────────────────────────────────────────────
       │ File: ./autogen.sh
───────┼─────────────────────────────────────────────────────────────
   1   │ #!/bin/zsh
   2   │ cp README.md README
   3   │ autoreconf -i && \
   4   │ autoconf && {
   5   │   echo "Running configure with --enable-maintainer-mode $@"
   6   │   ./configure --enable-maintainer-mode $@
   7   │ }
───────┴─────────────────────────────────────────────────────────────
$ ./autogen.sh
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Running configure with --enable-maintainer-mode 
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for grep that handles long lines and -e... /bin/grep
checking for a sed that does not truncate output... /bin/sed
checking for zsh... /usr/bin/zsh
checking Checking whether /usr/bin/zsh is compatible with zshdb... zsh 5.4.2 (x86_64-ubuntu-linux-gnu) is recent enough.
yes!
checking for diff... /usr/bin/diff
adding -w to diff in regression tests
adding --unified to diff in regression tests
checking whether ln -s works... yes
checking for rm... /bin/rm
checking that generated files are newer than configure... done
configure: creating ./config.status
configure: error: could not make ./config.status
$ echo $?
1
```

I know that `chmod -x ugrep`ing [the artifact I have extracted](https://github.com/Genivia/ugrep/issues/22#issuecomment-611084763) fixes the above issue.

Unfortunately, I am not familiar with `./configure` at all.

**Comment by genivia-inc** [comment]
Thanks for sharing this.

It looks like a bug in the `-G` option. The `configure` scripts runs `grep -v '^ *+'`, which means `ugrep -GUY. '^ *+'` when `alias grep='ugrep -GUY.'`. After changing one line of ugrep code that flags the combination `*+` as invalid (when it is valid with option `-G`), I get this to work just fine.

**Comment by genivia-inc** [comment]
Version 2.3.1 should fix this, as tested on my side.

**Comment by stdedos** [comment]
Actually, I had `ugrep` setup simply as

```console
$ ~ → ls -lah .installs/bin 
total 12M
drwxr-xr-x  2 stdedos stdedos 4,0K Ιουν 22 08:39 .
drwxr-xr-x 11 stdedos stdedos 4,0K Ιουν 21 20:15 ..
lrwxrwxrwx  1 stdedos stdedos    5 Απρ   8 01:17 grep -> ugrep
lrwxrwxrwx  1 stdedos stdedos   11 Απρ  14 20:05 ugrep -> ugrep-2.0.0
-rwxr-xr-x  2 stdedos stdedos 741K Απρ   8 00:00 ugrep-1.8.1
-rwxr-xr-x  1 stdedos stdedos 785K Απρ  14 19:49 ugrep-2.0.0
```

Since there is already a `grep` alias (`grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}`) and I don't know how would re-aliasing again would stack up.

When I fix getting steamrolling releases for `ugrep` for me, I guess I have to check my linking system too

**Comment by genivia-inc** [comment]
In principle it should be OK to set it up `grep` this way except that `ugrep` behaves like `egrep` by default, so `egrep -> ugrep` is fine but `grep -> ugrep` is not. Linking `egrep` to `ugrep` is fine because `ugrep` behave exactly like `egrep` when the standard (POSIX) grep options are used so we can ignore using `-U`, `-Y` and perhaps `-.` as well. Still, using aliases is preferable and more flexible.

> I don't know how would re-aliasing again would stack up.

Like this:

    alias grep='ugrep -GUY. --exclude-dir={.bzr,.CVS,.git,.hg,.svn,.idea,.tox}'

Or to exclude all dot files and directories instead of the ones listed (i.e. no `-.` to search hidden), and to support Unicode matching (no `-U` for "binary" search patterns) with improved empty match semantics by default (no `-Y` to always show empty matches):

    alias grep='ugrep -G'

**Comment by stdedos** [comment]
Thank you for your suggestion.

I know that I could simply merge those aliases manually myself.
My case here is that I did not do the `grep` alias myself (this OS is a forced-zsh playground, and I half hate it already).

I will end up doing a dummy script to hide `ugrep -GUY.` inside the now-link `grep`. I hadn't noticed that `grep` needs to be aliased specifically. All the rest being said, I guess I was just a bit lazy in the end (since this is my first "standalone" OS, I am merging a lot of scattered utility files to create a "single point of truth" filesystem / codebase).

If/when I solve the debian packaging of `ugrep`, my next step would be to make `ugrep` introspect its execution name, and apply the suggested aliases by default instead. If `ugrep` is called as `grep`, internally change its defaults to `-GUY.` _and only then_ start arg-parsing (analogously to `busybox`).

**Comment by genivia-inc** [comment]
Oh, I had totally forgotten that `ugrep` can check that it is named `grep`, `egrep`, or `fgrep` as hard/soft links. Thanks for the reminder! You can expect to see this in v2.3.2 and the appropriate options will be applied automatically.

**Comment by genivia-inc** [comment]
I propose the following addition to the `options` function in `src/ugrep.cpp`:

~~~
// parse the command-line options
void options(int argc, const char **argv)
{
  // automatically apply the appropriate options when the program is named grep, egrep, or fgrep

  const char *program = strrchr(argv[0], PATHSEPCHR);

  if (program == NULL)
    program = argv[0];
  else
    ++program;

  if (strcmp(program, "grep") == 0)
  {
    flag_basic_regexp = true;
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
  else if (strcmp(program, "egrep") == 0)
  {
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
  else if (strcmp(program, "fgrep") == 0)
  {
    flag_fixed_strings = true;
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
  else if (strcmp(program, "zgrep") == 0)
  {
    flag_decompress = true;
    flag_basic_regexp = true;
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
  else if (strcmp(program, "zegrep") == 0)
  {
    flag_decompress = true;
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
  else if (strcmp(program, "zfgrep") == 0)
  {
    flag_decompress = true;
    flag_fixed_strings = true;
    flag_binary = true;
    flag_hidden = true;
    flag_empty = true;
  }
~~~

Here I enabled `flag_binary` for option `-U`. However, we could check if the `LC_ALL` or `LANG` environment variables are set. If `LANG` has UTF-8 support, then option `-U` is probably best not to use as the intent of the user is to match Unicode e.g. when he/she uses option `-P`.

**Comment by stdedos** [comment]
Please delete my comment and the one yours above, and move them to a new issue
I'll then respond 😄

**Comment by genivia-inc** [comment]
The v2.3.2 update checks for filename `grep`, `egrep`, `fgrep`, `zgrep`, `zegrep`, and `zfgrep`. This auto-enables options `-E`, `-F`, and `-z` with `-.` (hidden) and `-Y` (empty matches). Option `-U` is not enabled for these, because IMHO it is bad to disable Unicode matching and GNU grep doesn't support it anyway, so there should not be a backward compatibility problem.

**Comment by genivia-inc** [comment]
Have you had some issues with the v2.3.2 update or does it successfully address the issue?

**Comment by stdedos** [comment]
Apologies @genivia-inc, I have been / am so busy this last week, I really don't have time for honestly testing.

_I don't think so_, but maybe next week I can report if I run into any issues.
