### ISSUE TITLE
alocal reference hardcoded?

### ISSUE THREAD

**Issue by RuneBergh** [Genivia/ugrep#5]
Had to use autoreconf -vfi on both systems i have been testing on. Have not checked the code, so feel free to shoot me down.  Both servers were ubuntu 16.04 LTS.

**Comment by genivia-inc** [comment]
This might be a problem with file time stamps in GitHub. I had to deal with that issue before that required `autoreconf -vfi` after downloading from GitHub.

**Comment by RuneBergh** [comment]
Thanks!
