### ISSUE TITLE
Request: RE: ugrep predefined patterns

### ISSUE THREAD

**Issue by JeffreyShran** [Genivia/ugrep#55]
Hi,

A useful addition to the -f method to run multiple pattern files would offer users a more convenient way to 'bulk' run regex lists.

So for example, instead of running `ug -f html/comments -f html/img -f html/href ...`  An alternative way to run everything in a folder and it's sub folders might be: `ug -f html/* ...`

The flexibility to group these regexes in a folder structure is greatly appreciated for organisational purposes. I do however often need to search large datasets for many different items of interest so calling a top level folder would be most useful.

**Comment by genivia-inc** [comment]
@JeffreyShran Thank you for your question and suggestion!

> So for example, instead of running ug -f html/comments -f html/img -f html/href ... An alternative way to run everything in a folder and it's sub folders might be: ug -f html/* ...

Here are three different ways to accomplish this.

1. bash and most other shells support "brace expansion":

        ug -fhtml/{comments,img,href} ...

    which expands to

        ug -fhtml/comments -fhtml/img -fhtml/href ...

    This works for any bash command and shell utility. Granted, it is not a `*` wildcard, but gives you a nice shortcut.

2. create a configuration file, say `html.ug` in the directory that you often want to search in, or place it in your home directory, if this is something you want to use often or anywhere:

        file=html/comments
        file=html/img
        file=html/href

    Generate a basic configuration file with `ug --save-config=html.ug` and then add these three lines. Now `ug ---html.ug ...` searches with these patterns. Note that three dashes `---` is the same as `ug --config=html.ug`.

3. create one pattern file, say `all`, by concatenating the pattern files together and place the new pattern file `all` in a (new) subdirectory in your home, say `patterns/html/all`. In .bashrc add

        export GREP_PATH=$HOME/patterns

    Now `ug -fhtml/all ...` works, because option `-f` checks the working directory first, then `GREP_PATH`, then the `/usr/local/share/ugrep/patterns` installed patterns. Perhaps it is better not to use `html` again to name your local patterns to avoid any possible confusion with the "global" `html` patterns, but you get the idea.

**Comment by JeffreyShran** [comment]
Thanks for responding so quickly. I really appreciate it. I had considered creating an 'all' file as in option 3. However I thought that there must be a better approach and the other 2 options certainly do that without making any changes to ugrep which is great.

Thanks again for your support and thanks for making this great tool available to us.
