### ISSUE TITLE
Run benchmarks using repeatable measurement techniques

### ISSUE THREAD

**Issue by spacejam** [Genivia/ugrep#58]
https://sled.rs/perf#experiment-checklist

Since this works with files, you probably want to drop vm caches, otherwise you're not really testing file access performance unless you're using O_DIRECT (a quick search in the repo didn't show any O_DIRECT flags, apologies if I missed it). Searching files that are already in the kernel's pagecache may be an interesting data point, but probably not the main one.

Also, when doing comparative benchmarking it's often a good idea to disable turbo boost (after compiling everything) to stabilize your CPU frequency. Unstabilized CPU frequencies are often the biggest source of runtime variance in many benchmarks, especially subsecond benchmarks.

I think by taking these steps and being clear about them, it will help to tell your story in a more effective way through numbers.

**Comment by genivia-inc** [comment]
Thank you for your feedback! I will continue to improve the benchmarks and ugrep's performance as evolves.

I tried to convey in the performance section in the README is that performance is not lacking behind other tools, so you're not trading down in performance when enjoying a more feature-rich search tool like ugrep. What I mean is that usability features and search options are critical goals for the ugrep project, with performance next. Users and contributors to ugrep seem to agree. They shared that they want features and that it would be great if the performance is (still) very good.

Not so long ago I came up with a new pattern matching algorithm and conducted an extensive set of tests to compare this algorithm to other popular pattern matching algorithms, before implementing it in ugrep. Let me share with you that the "secret sauce" is this new pattern matching algorithm. This algorithm is best benchmarked using raw CPU performance like everyone else does (at least in technical publications). I have not published the performance and details of this new algorithm yet, but plan to do so in the near future.
