### ISSUE TITLE
[FR] new --format placeholder: file name without path

### ISSUE THREAD

**Issue by paoloschi** [Genivia/ugrep#61]
this _ugrep_ is fantastic!!!! kudos!!!!

just a really minor, low priority request which I think could be easy to implement:
in the _ugrep_ manual I don't see for the `--format` option the presence of a placeholder equivalent to this one in GNU command _find_:

```%f        File's name with any leading directories removed (only the last element).```

(since `%f` in _ugrep_ is already assigned, any other placeholder letter would be fine)
I felt this need today after reformatting to JSON the _ugrep_ output I piped to _jq_ command, whereby I need to group the same file names coming from different directories (...) 
it is obvious that they are rare use cases but it can occour and then, not having the name already separated from the path, it forces to manipulate the string _pathname_ afterwards…
thank you

**Comment by genivia-inc** [comment]
Thank you for your feedback! It makes sense to add a basename field for the format option.

**Comment by genivia-inc** [comment]
I've updated the master branch with an updated ugrep source code (`src/output.cpp`) with new format fields `%a` and `%p`:

       %a     the file basename without directory path.
       %p     the directory path to the file.

If there is a problem, let me know. Otherwise this update will be folded into the next release. Note: `bin/win64/ugrep.exe` is not updated.

**Comment by paoloschi** [comment]
compiled from source just now without any hassle (about _ugrep.exe_, I forgot to mention my OS which is linux, Void Linux, exclusively)
I tested both new placeholders and everything works as expected.
thank you so much!

I just add that I observed a difference with respect to what `%p` produces in _ugrep_ compared to the equivalent `-printf '%h'` in _find_: I see that _ugrep_ with `%p` preserves the final _slash_ while GNU _find_ removes it.
I was wondering if in these cases a uniformity of result between the different tools is desirable.
but I'm not a programmer, It's just an observation that came to me...

**Comment by genivia-inc** [comment]
> I see that ugrep with %p preserves the final slash while GNU find removes it.

We should remove the final slash. I made the necessary change to the master branch.

**Comment by paoloschi** [comment]
I recompiled and verified the removal of the slash.
Thank you again for fulfill my request!
So, can we close this issue now?

**Comment by genivia-inc** [comment]
Feature was added to v2.5.3.
