### ISSUE TITLE
Support SRELL (or NIRE) library

### ISSUE THREAD

**Issue by data-man** [Genivia/ugrep#66]
First of all, thank you so much for the great tool!

-------
[SRELL](http://www.akenotsuki.com/misc/srell/en/)
> is a template library that has an ECMAScript (JavaScript) compatible regular expression engine.

[NIRE](http://www.akenotsuki.com/misc/nire/en/)
> NIRE is a fork of SRELL.

without some features.

**Comment by genivia-inc** [comment]
Thanks for you suggestion. Interesting replacement of `std::regex`.

However, I did not find any information if this library supports partial matching. Partial matching is critical to search large files without having to buffer the entire file (or mmap), just a portion of it as a buffered window. PCRE supports two forms of partial matching, soft (gives up for cases like `a*` when one or more `a`'s are found) and hard (requires input until `a*` can match all `a`'s). See https://www.pcre.org/current/doc/html/pcre2partial.html . The built-in matcher is the fast DFA-based RE/flex matcher that supports partial matching to consume more input only when necessary.

Without hard partial matching the entire file must be stored e.g. with mmap. That is not desirable when the file is large ( a couple of GB).

Does SRELL support partial matching?

**Comment by data-man** [comment]
> Does SRELL support partial matching?

I guess not, because I didnt find a partial matching in ECMA-262 language specification.

BTW, maybe you will be interested in BenHanson's [projects](https://github.com/BenHanson?tab=repositories).

**Comment by genivia-inc** [comment]
Thanks for the pointers.

Please note that the ugrep regex pattern matchers are RE/flex matchers. [RE/flex](https://github.com/Genivia/RE-flex) is a flexible and extensible framework for regex matching, regex search, and lexical analysis (a.k.a. scanners and tokenizers).

The framework is extensible. To add new regex libraries to RE/flex, a new C++ class can be created and derived from [`reflex::AbstractMatcher`](https://www.genivia.com/doc/reflex/html/classreflex_1_1_abstract_matcher.html). This class should implement a `match()` method to perform `find`, `matches`, `scan`, and `split` operations on text.

RE/flex matchers are provided as C++ classes for PCRE, BoostRegex, and std::regex. There is also a C++ class extension of the built-in fast RE/flex matcher for approximate pattern matching, the [FuzzyMatcher](https://github.com/Genivia/FuzzyMatcher). The PCRE (or Boost.Regex) and FuzzyMatcher are used for ugrep options `-P` and `-Z`.
