### ISSUE TITLE
In fuzzy mode, the first letter of the pattern does not get fuzzed

### ISSUE THREAD

**Issue by jakkanen** [Genivia/ugrep#68]
Given file `words`:
```
abcde
_bcde
a_cde
ab_de
abc_e
```
observed:
```
$ ugrep -Z1 bcd words 
abcde
_bcde
ab_de
abc_e
abcd_
```

I would expect the `a_cde` line to be matched as well
ugrep 2.5.3

**Comment by genivia-inc** [comment]
See the man page and ugrep help (`ug --help`): it states that the first character of the pattern always matches.

You can make it optional with `?` or use a dot to match anything.

This is an important choice to reduce the "randomness" of results when patterns are short and greatly optimizes speed when matching many GB of data, while still offering control by using `?` and other regex constructs.
