### ISSUE TITLE
Segementation fault with over 9 files on Cygwin

### ISSUE THREAD

**Issue by ISO8807** [Genivia/ugrep#7]
I'd like to be able to use ugrep at a Cygwin prompt on Windows 10. Unfortunately I get a segmentation fault if there are more than nine files on the command line, e.g.:

  ugrep thing f1 f2 f3 f4 f5 f6 f6 f7 f8 f9 f10

For this reason I also get segmentation faults when using shell filename expansion, e.g.:

  ugrep thing f*

Any thoughts? Many thanks!

**Comment by genivia-inc** [comment]
I think you may be trying to run the pre-built `ugrep.exe` that comes with the software?

**Comment by genivia-inc** [comment]
Try the v1.5.5 update.

**Comment by ISO8807** [comment]
Many thanks for the quick response.

| I think you may be trying to run the pre-built ugrep.exe that comes
| with the software?

Yes, I'm using the pre-built Windows version.

| Try the v1.5.5 update

I just tried 1.5.5 but am seeing the same kind of issue:

  ugrep TEST [a-g]*    works (48 files, 396 characters of file names)

  ugrep TEST [a-h]*    fails (57 files, 461 characters of file names)

It looks like this is a command-line limit rather than a file limit. It seems to fails around 440 characters of arguments. I don't know if a Cygwin version (rather than Windows native version) would work better for me.

**Comment by genivia-inc** [comment]
I suspect this is a Cygwin issue running the pre-built ugrep.exe, which was built with MSVC++. Ugrep has no limits on `argc` and `argv[]` at all. I tried with ugrep 1.5.5 built on Cygwin with 294 files and long file names. I don't see this issue at all.

**Comment by ISO8807** [comment]
| I suspect this is a Cygwin issue running the pre-built ugrep.exe

I suspect you're right, though I've never had problems before running Windows binaries from a Cygwin prompt.

I tried the same test (with a long list of explicit filenames) at a DOS command prompt and indeed it works fine.

Many thanks for your prompt help. And congratulations on an impressively-featured utility.

**Comment by genivia-inc** [comment]
A problem with `ugrep.exe` job stealing for load balancing is fixed in 1.5.10. I suspect the original issue you reported here may have been a symptom of this.

**Comment by ISO8807** [comment]
Thanks for your investigations and work-arounds for Cygwin limitations. I think can close this issue.

**Comment by genivia-inc** [comment]
Just a quick update on progress on ugrep. I hope you're still interested. I've improved `ugrep.exe` to support options `-P` (Perl matching) and `-z` (decompress/unarchive) as well as fixed an issue with `ugrep.exe` command-line globbing. It's just as capable as the *nix variants now. Also a Visual Studio project directory `vs` is included.

Enjoy!
