### ISSUE TITLE
[FR] Make ugrep run continuously in the background

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Genivia/ugrep#75]
I have a bunch of files and I need to run ugrep with the `--tag` options to mark the match and redirect to a file. However, I need to do this many times. Below are some examples:

```
ugrep --tag="<div>,</div>" "term1" > term1.txt
ugrep --tag="<div>,</div>" "term2" > term2.txt
ugrep --tag="<div>,</div>" "term3" > term3.txt
...
```

I can easily write a script to automate this process. But the problem is that ugrep will be start up and shut down many times. For a small amount of time, this is not an issue.  But if we need to search hundreds of thousands or even millions of times the performance penalty will quickly adds up. 

Is it possible to add an option to let ugrep continuously run in the background so that the process start up and shut down penalty could be avoid?

**Comment by genivia-inc** [comment]
Thanks for your suggestion.

I suggest to use `xargs` to run multiple ugrep searches simultaneously. Or use a script with `&&` to run parallel tasks.

I don't think the fork overhead is significant enough to look into adding more complexity to run ugrep continuously. It is not clear how a ugrep daemon process would efficiently receive new file names to search and where to send the results to.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the suggestion.
