### ISSUE TITLE
ugrep -z crashes on windows for some archives

### ISSUE THREAD

**Issue by Kelly12612** [Genivia/ugrep#76]
Below is what I could get from a debug build of ugrep on my machine, not as much details as I was hoping for, hopefully it's enough for you to go on.  

The thread 0xe8d4 has exited with code 0 (0x0).
Debug Assertion Failed!

Program: D:\BMCProjects\ami_dev\ugrep\vs\ugrep\x64\Debug\ugrep.exe
File: minkernel\crts\ucrt\src\appcrt\lowio\close.cpp
Line: 48

Expression: (fh >= 0 && (unsigned)fh < (unsigned)_nhandle)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

**Comment by genivia-inc** [comment]
Thanks for the feedback.

I will take a closer look. What ugrep options did you use, besides `-z`?

**Comment by Kelly12612** [comment]
The entire command line was "ugrep -z hello" (just trying it out).
I ran procmon and found that it seemed to have been examining an 800mb 7-zip archive when it crashed (at least one thread was), don't know if that's important or not.
I tried both a 32 bit and a 64 bit local build, both crashes, although the 64 bit build seemed to run a bit longer before crashing.

**Comment by genivia-inc** [comment]
> I ran procmon and found that it seemed to have been examining an 800mb 7-zip archive when it crashed (at least one thread was), don't know if that's important or not.

Most likely a problem with 7-zip, if that is the format searched. The latest versions of ugrep do not decompress 7-zip. That may explain the problem, although there should of course not be an assertion failure or crash.

**Comment by Kelly12612** [comment]
Right, I was just running it in a large directory tree, Is this the correct syntax to have it ignore *.7z? 
    ugrep -z --exclude=*.7z hello
I tried that and it still crashed, although I didn't see it processing any files ending in .7z in the procmon output.

**Comment by genivia-inc** [comment]
Right. The report points to an issue when executing close on Windows, which does not depend on the type of file. It should not be a problem to trace that problem down.

**Comment by genivia-inc** [comment]
I've created a 3.0.4 pre-release x64 version at our secure download location: https://www.genivia.com/files/ugrep.exe

This upgrade corrects a couple of minor issues: hex dump output improvements and fixing an issue when searching zip/tar files in the query UI that may cause the UI to hang sometimes. I tested the x64 VS Debug version of ugrep.exe 3.0.4 with option `-z` on a large directory of various files, including compressed files. This does not produce the problem you describe. However, it would be important to know if it does or does not resolve the problem you describe.

**Comment by Kelly12612** [comment]
I ran the pre 3.0.4 build in the same directory, same command line.  It did not crash......

**Comment by genivia-inc** [comment]
Good to know>. The problem was related to a combination of conditions. I've updated the logic, verified the execution traces, and ran additional tests.

**Comment by genivia-inc** [comment]
Ugrep v3.0.4 is released with the correction.
