### ISSUE TITLE
Inconsistent -C, -Q & -Z  options

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Genivia/ugrep#77]
Today I noticed an issue with ugrep's `-C` option. See my below testing.
```
F:\_>ugrep --version
ugrep 3.0.4 WIN32 +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>

F:\_>ugrep --help | ugrep -i -m 2 all
            ignores binary matches.  `text' treats all binary files as text,
            it as commands.  `hex' reports all matches in hexadecimal.

F:\_>ugrep --help | ugrep -i -m2 all
            ignores binary matches.  `text' treats all binary files as text,
            it as commands.  `hex' reports all matches in hexadecimal.

F:\_>ugrep --help | ugrep -i -m 2 -C 2 all
ugrep: warning: all: No such file or directory

F:\_>ugrep --help | ugrep -i -m 2 -C "2" all
ugrep: warning: all: No such file or directory

F:\_>ugrep --help | ugrep -i -m 2 -C2 all
            `with-hex'.  The default is `binary' to search binary files and to
            report a match without displaying the match.  `without-match'
            ignores binary matches.  `text' treats all binary files as text,
            which might output binary garbage to the terminal, which can have
            problematic consequences if the terminal driver interprets some of
            it as commands.  `hex' reports all matches in hexadecimal.
            `with-hex' only reports binary matches in hexadecimal, leaving text
            matches alone.  A match is considered binary when matching a zero
--
            default, ACTION is `skip', i.e., silently skip directories unless
            specified on the command line.  If ACTION is `read', warn when

```
It seems I have to connect the `-C` with its parameter value `2` together to make it work as expected. I check the help and the document clearly specified this behavior:
```
-C[NUM], --context[=NUM]
```

This is not the same as `-A` or `-B`:

```
-A NUM, --after-context=NUM
-B NUM, --before-context=NUM
```

Why not make them all behave the same? I checked the document and there are other options behave similar:
```
    -A NUM, --after-context=NUM
    -B NUM, --before-context=NUM
    -C[NUM], --context[=NUM]<------------------------------
    -D ACTION, --devices=ACTION
    -d ACTION, --directories=ACTION
    -e PATTERN, --regexp=PATTERN
    -f FILE, --file=FILE
    -g GLOBS, --glob=GLOBS
    -J NUM, --jobs=NUM
    -K FIRST[,LAST], --range=FIRST[,LAST]
    -M MAGIC, --file-magic=MAGIC
    -m NUM, --max-count=NUM
    -N PATTERN, --neg-regexp=PATTERN
    -O EXTENSIONS, --file-extension=EXTENSIONS
    -Q[DELAY], --query[=DELAY]<------------------------------
    -t TYPES, --file-type=TYPES
    -Z[MAX], --fuzzy[=MAX]<------------------------------
```

Is it possible to make them behave consistent? This will slightly improve the usability of ugrep. Bwt, ripgrep happily accepts `-C 2`. 

```
F:\_>ugrep --help | rg -i -m 2 -C 2 all
            `with-hex'.  The default is `binary' to search binary files and to
            report a match without displaying the match.  `without-match'
            ignores binary matches.  `text' treats all binary files as text,
            which might output binary garbage to the terminal, which can have
            problematic consequences if the terminal driver interprets some of
            it as commands.  `hex' reports all matches in hexadecimal.
            `with-hex' only reports binary matches in hexadecimal, leaving text
            matches alone.  A match is considered binary when matching a zero

F:\_>
```

**Comment by genivia-inc** [comment]
> It seems I have to connect the -C with its parameter value 2 together to make it work as expected. I check the help and the document clearly specified this behavior:
> 
>` -C[NUM], --context[=NUM]`
> 
> 
> Why not make them all behave the same?

This behavior is inherited from BSD grep 2.5.1, which comes standard with MacOS:
~~~
     -C[num], --context[=num]
             Print num lines of leading and trailing context surrounding each
             match.  The default is 2 and is equivalent to -A 2 -B 2.  Note:
             no whitespace may be given between the option and its argument.
~~~
I agree that it is not absolutely necessary to have this as an optional value, because the latest BSD grep requires `NUM` also.

I'll change it for option `-C`.

IMO we should keep the argument values for `-Q` and `-Z` optional.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the explanation! Just out of curiosity, is it a BSD convention to connect an option with its optional value together?

**Comment by genivia-inc** [comment]
> Just out of curiosity, is it a BSD convention to connect an option with its optional value together?

Yes. No space is allowed between `-C` and `NUM`.

This supports `grep -RCn pattern` for example, which in this case does not require splitting the options up in `grep -R -C2 -n pattern`.

One the one hand this is convenient. Spacing between the option and its argument isn't often used anyway. On the other hand, for consistency with `-A` and `-B`, I think we should drop it.

But for `-Q` and `-Z` it is important to keep their arguments optional, i.e. without spacing. I'd rather simply run `ug -QZlz` than `ug -Q5 -Z1 -lz`.

PS. I am working on a major release that implements logical connectives such as `--and`, `--and-all`, `--and-any`, `--not`, to combine patterns, which involves a bit of work for the design. I want these options to be intuitive to use, meaning I'm evaluating difference approaches.

**Comment by genivia-inc** [comment]
I noticed that you run `ugrep --help | ugrep -i -m 2 all` but you may also want to try `ugrep --help all` to properly display all options that mention `all` (matching mixed case).

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the clarification and the tip! Looking forward to the new features.

**Comment by genivia-inc** [comment]
PS. I've updated ugrep to v3.0.5 with the `-C` option change.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for reminding!
