### ISSUE TITLE
ugrep rel 3.0.4 do not run on Windows 7 - 64 bit

### ISSUE THREAD

**Issue by skarsgal** [Genivia/ugrep#78]
When I run ugrep.exe rel. 3.0.4 on Windows 7 / 64 bit, I obtain this error:
'The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll' and program do not run.
But release 2.5.6 works fine.

**Comment by genivia-inc** [comment]
There is a 32bit Win version of ugrep.exe [included with the repo](https://github.com/Genivia/ugrep/tree/master/bin/win32) that should work. Let me know if that binary has a problem on Windows 7. I decided to include the 64 bit version with the latest releases to download. The [CreateFile2](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfile2) call of the Win32 API is necessary to handle Unicode filenames properly, which is new to ugrep v3.0.

**Comment by skarsgal** [comment]
Just tried.  Same error with ugrep.exe  32 bit on Windows 7 64 bit.
Anyway thanks.

**Comment by genivia-inc** [comment]
Hmmm. Indeed, I'm a bit surprised that this API is not supported on Win before Windows 8. We should change to CreateFileW for the upcoming release. That would work without losing any features.

**Comment by genivia-inc** [comment]
I made this small change to produce a v3.0.4 ugrep.exe update and replaced the release artifact. It is the same version, just changed CreateFile2 to CreateFileW.  Tested this with Unicode file names on Windows 10 and it looks OK.

**Comment by skarsgal** [comment]
Yes, it works.
Thanks

**Comment by genivia-inc** [comment]
Thanks for reporting this!
