### ISSUE TITLE
3.0.4: color seems to be disabled by default

### ISSUE THREAD

**Issue by rrthomas** [Genivia/ugrep#79]
I just upgraded from v2.5.x.

To demonstrate what happens, in a terminal I run:

```
$ `which ug` foo bar.txt
[uncolored output]
$ `which ug` --color=auto foo bar.txt
[colored output]
```

This suggests that `--color=auto` is no longer the default, as documented? I use `which` above to ensure that I'm getting the binary, rather than any alias.

Thanks for continuing to work on ugrep; I just upgraded my installation to be able to decompress lz4!

**Comment by genivia-inc** [comment]
Color is always the default when standard output is directed to a terminal and the environment variables indicate that a color term is set. There isn't any change in the code from 2.5.x to 3.x with respect to coloring. Your examples work on all of our machines.

Perhaps you have a .ugrep config that disables color? Or ugrep was built without the default `--enable-color` configuration option?

**Comment by rrthomas** [comment]
Thanks for confirming nothing has changed with ugrep in respect to color. This seems to be a Heisenbug, perhaps to do with the terminal in which I rebuilt ugrep, because I cannot now reproduce it. (I checked that I had not configured ugrep with any flags, and that I did not have any ugrep configuration file.)

**Comment by rrthomas** [comment]
Sorry, I realized I *am* still experiencing the bug, I just added `--color=auto` to my aliases to work around it!

**Comment by rrthomas** [comment]
```
$ echo $TERM
xterm-kitty # I also tried in gnome-terminal, same problem
$ cd ugrep
$ ./config.status --config

$ ugrep --version
ugrep 3.0.4 x86_64-pc-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
$ locate \\.ugrep
$ # no output
```

**Comment by rrthomas** [comment]
I found the problem: I tried rebuilding with explicit `--enable-color`, and it now works as expected.

I then tried building with just `./configure` again, and once again, it does not color by default.

So it seems that `--enable-color` is not actually the default?

**Comment by genivia-inc** [comment]
The `./build.sh` script does all that, as the README installation explains.

**Comment by rrthomas** [comment]
Thanks! It would cause less confusion if `--enable-color` were changed to `--disable-color`, so it really was the default; this would help users like myself who don't spot the non-standard `build.sh`: for building from git, all that should be necessary is `autoreconf -fi`, `./configure [OPTIONS] && make` as normal, and from a release tarball, just the second step. I can't see anything in `build.sh` that couldn't either be removed or folded into `Makefile.am`.

**Comment by rrthomas** [comment]
I'd be happy to help fix it so that `build.sh` isn't needed or is reduced to a trivial script, according to what you're trying to achieve with it.

**Comment by genivia-inc** [comment]
I understand. I think the `--enable-colors` option should be deprecated. I'll do that for the next release. A new option `--disable-auto-color` will be added, just in case.

**Comment by genivia-inc** [comment]
An update for these configure options change and some minor other improvements will be released momentarily.
