### ISSUE TITLE
Query mode (-Q) does not work on Windows (<10)

### ISSUE THREAD

**Issue by gaasedelen** [Genivia/ugrep#81]
Just a heads up, but Query mode `-Q` appears to be broken (?) on Windows 8/8.1. It exits immediately and prints the following:

![image](https://user-images.githubusercontent.com/9522648/99865850-932aeb00-2b7a-11eb-8add-3f7b248b67d1.png)

I do a lot of development in a Windows 8.1 VM as it's lighter to virtualize, so that's why I noticed. `ug -Q` works fine on my host (w10).

This is v3.0.5, WIN x64 (latest)

**Comment by genivia-inc** [comment]
The problem is that older Window's command prompts do not support ANSI capabilities. ANSI is required (see the `-Q` option manual page and README).

It typically works fine with PowerShell or other terminal programs that support ANSI.
