### ISSUE TITLE
Query mode (-Q) does not work on Windows 7 x64

### ISSUE THREAD

**Issue by skarsgal** [Genivia/ugrep#84]
I have tried last build 3.0.6 on my Windows x64.
When I put the command 
**ug -Q**
I obtain an error:
1. as image
[]https://i.imgur.com/CiuqiAE.png(url)
2. as text
C:\downloads>ug -Q
[mugrep: [1;31mno keyboard detected[m

This error (?) is similar to issue #81.
Do You can fix this issue ?
Thanks

**Comment by genivia-inc** [comment]
Thanks for the feedback. An ANSI-capable terminal is required to support option `-Q`. Ugrep enables ANSI for keyboard input and color output with the `SetConsoleMode` API with `ENABLE_VIRTUAL_TERMINAL_INPUT` and `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. If this fails, then you get a "no keyboard detected" error or "no ANSI terminal screen detected". Even when we work around the `ENABLE_VIRTUAL_TERMINAL_INPUT` failure, then still you won't be able to use the query UI without the terminal app offering some basic ANSI control code support.

Windows 7 Command Prompt is just too old to support this. Perhaps a  different terminal program like ConEmu works, see https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling

If anyone has a list of console or terminal apps that allow `ug -Q` to work with older Windows versions, then we should list those in the README.

**Comment by skarsgal** [comment]
Thanks for the reply.
I have tried **Cmder** - Console Emulator
- web site https://cmder.net that's based on ConEmu. 
- GitHub https://github.com/cmderdev/cmder
but when I have typed: 
ug -Q 
I have obtained answer 'ugrep: no keyboard detected'. (in red)

I think that Windows 7 do not support ANSI, not even with Cmder.
So I think that You can close this issue.

**Comment by genivia-inc** [comment]
Thanks for checking. Sorry we can't support the interactive query UI on Win7 right now.

If I find some time In the future, I may rewrite part the query UI code to support Win7 using Window's native console API calls such as `SetConsoleTextAttribute` and `SetConsoleCursorPosition`. Seems not too difficult, but a hassle to implement and time consuming. Or perhaps someone could fork ugrep and give it a try?

Appreciate that Windows supports ANSI codes as of Windows 10. But they're late to do so.
