### ISSUE TITLE
query mode shows "keys" 

### ISSUE THREAD

**Issue by ulugbekna** [Genivia/ugrep#86]
Hi, when I open a tool with `--help` and pipe into `ug -Q`, I get : 

![image](https://user-images.githubusercontent.com/16353531/102317453-60b5b780-3f99-11eb-8b3c-0520717ee7ee.png)

It should be like:

![image](https://user-images.githubusercontent.com/16353531/102317478-6e6b3d00-3f99-11eb-8095-120960e1d4a2.png)

Am I doing something wrong?

**Comment by genivia-inc** [comment]
Nothing wrong here, just that the CTRL-H (`^H`) that you see are not interpreted by the query UI. Control codes are displayed, not executed or hidden. The man page output uses CTRL-H to back over characters to display them in bold. But that is a "man thing".

**Comment by genivia-inc** [comment]
The `man man` page has some tips to help in this case, see the last line in this dump:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/102387551-83969a80-3f9e-11eb-8db2-e85e0eca8f47.png">

    man XYZ | col -b | ugrep -Q

This removes the backspacing and makes the man output searchable.

**Comment by ulugbekna** [comment]
Thanks for a quick reply and an awesome tool! :-)
