### ISSUE TITLE
`--basic-regexp` does not work with `--word-regexp` but this works with GNU/BSD grep

### ISSUE THREAD

**Issue by smac89** [Genivia/ugrep#87]
The README recommends using the following alias to emulate GNU/BSD grep:

```
alias grep='ugrep --sort --basic-regexp --binary --empty --hidden'
```

I did this, but when I attempted to search for a word (`grep -w word`), it fails to find the word, but regular grep is able to do this.

---

### Note
- I found that removing `--basic-regexp` allows `-w` to work
- Also using `--extended-regexp` in combination with `-w` works

**Comment by genivia-inc** [comment]
Good catch! This combo is not in the tests, alas, so missed it. That is something to look into.

**Comment by genivia-inc** [comment]
I've committed v3.1.1 with a fix for this issue.
