### ISSUE TITLE
Create snap package for ugrep

### ISSUE THREAD

**Issue by sidahmed-malaoui** [Genivia/ugrep#88]
Are you willing to create a snap package for ugrep ? 

I can help you with that if it's the case.

PS : Thank you for this wonderful tool :D

**Comment by genivia-inc** [comment]
Thank you for your kind feedback and suggestion!

I'd love to create more packages for ugrep, but this is the first time I've heard of snap packages, so I'm not familiar with those.

Do you have experience creating snap packages? If so, could you give this a try and then we could perhaps setup something (semi-)automatic for future snap packages for ugrep updates?

**Comment by sidahmed-malaoui** [comment]
Yes dude, I have some experience with snap packaging, and I will be glad to help you through this issue.

## What's a snap packaging
It's a packaging format made by Canonical (Ubuntu's producers and main maintainers). You can get more infos here [https://snapcraft.io/](https://snapcraft.io/). 

## What are the advantages of snap packages
  - When a software is packaged as a snap package, and published on the Snapstore, the package can be installed on almost any Linux distro using one simple command : `sudo snap install ugrep`, or using the Ubuntu Software Center.
  - You can link your snapstore account with your github repository. This will allow automatic packaging and publishing.
  - snaps implement delta updates, this means that when a user needs to upgrade to latest version of `ugrep`, snap won't download the whole package, but it will only download the difference between the two versions of the package.
  - All `ugrep` dependencies will exist inside the snap package. That's why snap packages can be installed on any Linux Distro without any problem.

## What are the disadvantages of snap packages
  - The package size is big comparing to other packaging formats. Because all dependencies are included in the package.
  - By default, snap packages don't have full access over the system. We have two choices here : 
    - We define the snap package as **classic**. This way it will have full access to the system. But, publishing a **classic** snap will take sometime (I'm not 100% sure about this information).
    - We define necessary permissions, like the permission to access home directory, and external storage devices.

## How to proceed

As a contributor, I will : 
  - Create the necessary configuration and structure to make the snap packaging possible.
  - Test the snap package to make sure it's working correctly.

As a maintainer (You), you should : 
  - Create a snapstore account.
  - Register the name `ugrep`, so you can publish a package using this name.
  - Link your registred name with your github repository. This will allow snaps to be automatically build and published with each commit for example.

So, what do you think ?

**Comment by xaljer** [comment]
Appimage is also easy to use on Linux.

**Comment by genivia-inc** [comment]
Sounds good to me. The only question is, who will maintain the snap package? It says "as a contributor, I will..."

**Comment by sidahmed-malaoui** [comment]
@genivia-inc Like I said before, snap packages are automatically built and published. The only thing to do to maintain the snap package is to change the version field inside `/snap/snapcraft.yml` (this can be automated too). But I will also be glad to help if there is any problem.

**Comment by genivia-inc** [comment]
No problem. Sounds like I have a bit of reading to do ;-)

**Comment by sidahmed-malaoui** [comment]
@genivia-inc Good luck dude. And tell me when you're ready to start. 

You can create a new branch for this, so we won't mess with master at all. I'll fork and do a pull request to the new branch which you'll create.

Cheers.

**Comment by genivia-inc** [comment]
This page gave more info on the snapcraft.yaml https://snapcraft.io/about/publish#c , however clicking on C/C++ then "Continue" produces 404 "Ah, snap...". Clicking on Tutorials and Docs in the top banner gives an Internal Server error.

**Comment by sidahmed-malaoui** [comment]
Ah i see. may be they have a problem with their website dude.

I hope they'll fix it soon

**Comment by stdedos** [comment]
If you are interested in debian packages, there _used to be_ official packaging on https://salsa.debian.org/debian/ugrep/-/tree/master/.

I must have those file somewhere; I can send you a review for those if you wish.
After you merge those files, and install `pristine-tar` and `debocker`, it would require some simple maintenance of the `debian` directory and `debocker build -o build` to generate artifacts (which you could then host on Github)
