### ISSUE TITLE
Text not found in simple PDF

### ISSUE THREAD

**Issue by htgoebel** [Genivia/ugrep#91]
While ugrep finds "ello" in `tests/Hello.pdf` provided with the source:
The text "ello" is not found in the [attached "Hello, world" PDF](https://github.com/Genivia/ugrep/files/5772942/Hello.pdf).

### How to reproduce
* Save attached PDF as "Hello.pdf"
* proof text is contained:`pdftotext Hello.pdf -` → shows "Hello, world!"
* run `ug ello Hello.pdf `
* → No results shown

Attached PDF has been generated from for postscript file using `ps2pdf13 Hello.ps Hello.pdf`
```
%
/Courier findfont 24 scalefont setfont
100 650 moveto (Hello, world!) show showpage
```
ps2pdf is part of ghostscript. Using `ps2pdf14` did not solve the issue.

### Observations
Maybe this is an encoding issue: The "Hello.pdf" provided with the source seem to use "/MacRomanEncoding".

**Comment by genivia-inc** [comment]
We ran tests with PDF files and `pdftotext` which works in most cases for PDF files produced by common utilities and office tools.

However, `pdftotext` is not a magical tool. There are cases when it garbles the text or does not produce anything. For example it could depend on the PDF font encodings or if the font is stored as bitmaps, then nothing can be output.

When I run `pdftotext Hello.pdf` (your file) it does not output anything.

I cannot fix the `pdftotext` program to make ugrep work, unfortunately.

**Comment by genivia-inc** [comment]
By the way, in the past I used LaTeX a lot with Ghostscript and ps2pdf. This produces PDF files that do not embed fonts. This method should not be used.

**Comment by htgoebel** [comment]
This issue is not related to pdftotext, but to ugrep core: While ugrep is able to grep the PDF provided in the source, it can't grep the simple one attached.

Two more points:
1. You need to add a dash as a second parameter when running pdftotext. Otherwise it will create a file "Hello.txt".
2. ugrep does not use any external filter (pdftotext) by default, thus pdftotext is not involved here in any way beside proving "Hello" is contained in the PDF's text.

**Comment by genivia-inc** [comment]
There are PDF files that will not work though, because of bitmapped fonts.

This is what I get:
~~~
$ ugrep --filter='pdf:pdftotext % -' '' Hello.pdf
Hello, world!
~~~
and
~~~
$ pdftotext Hello.pdf - | ugrep ''
Hello, world!
~~~
Works like a charm as explained in the documentation.

So what is the problem?

**Comment by genivia-inc** [comment]
I now understand what you are trying to point out, because the test files include a PDF file. However, the PDF is included as an example binary file for testing ugrep options that affect binary searching. The PDF is not meant to be a "text" file to search.

We should keep all the test files as they are.

**Comment by htgoebel** [comment]
After more investigations I understood: It's not the text in the document body which matches, but the title from the metadata.

I was thinking ugrep is magically searching the document body, while I could not spot any code in the source for decoding the PDF streams.

Side note (while not being a PDF export, I've spend quite some time on it.):
> because of bitmapped fonts.

This sounds like a wrong understanding of PDF. 
Whether the fonts are includes as splines or as bitmap or not at all is irrelevant for (not) searching the contained text. In a PDF the text-strings are part of the "program" carried in data streams. The font data is separate. Normally you can not "spot" the text-strings since the data-streams are compressed.
