### ISSUE TITLE
ugrep does not support some legacy cpio formats

### ISSUE THREAD

**Issue by htgoebel** [Genivia/ugrep#92]
ugrep can not search cpio archives created on (current) GNU/Linux systems.
cpio (GNU cpio) 2.13, Copyright © 2017 Free Software Foundation

### How to reproduce
* Download and extract [attached new.cpio.zip](https://github.com/Genivia/ugrep/files/5774591/new.cpio.zip) (github does not allow uploading cpios files, this is why this is ziped)
* run `ug -z Hello /tmp/new.cpio`
* → "Binary file new.cpio matches"

### Expected behavior
* Command should output some hits like 
```
{Hello.bat}:echo "Hello World!"
Binary file /tmp/old.cpio{Hello.class} matches
{Hello.java}:public class Hello // prints a Hello World! greeting
[…]
```

### Background
* `tests/gen.sh` does not specify which cpio format to use. Defaults seem to differ between platforms.
* The `archive.cpio` contained in the tests 
    * file type is a "ASCII cpio archive (pre-SVR4 or odc)" 
    * `ug -z Hello archive.cpio` returns the expected result.
* The attached archive generated by `ls Hello.{bat,class,java,pdf,sh,txt} empty.txt | cpio -o --quiet > new.cpio`,
   * file type is "cpio archive"
    * `ug -z Hello archive.cpio` only says "Binary file new.cpio matches"
* Using `cpio --format odc …` creates a cpio-file which is identical to the `tests/archive.cpio` (beside timestamps, etc. of course) and can be seached be `ug -z`
    * Note' I'm already working on a pull-request for (among other changes) pinning the archive type

Here is a list of formats supported by GNU cpio 2.17 (from the man-page):
```
              Use  given  archive  FORMAT.   Valid  formats are (the number in
              parentheses gives maximum size for individual archive member):

              bin    The obsolete binary format.  (2147483647 bytes)

              odc    The old (POSIX.1) portable format. (8589934591 bytes)

              newc   The new (SVR4) portable format, which supports file  sys-
                     tems having more than 65536 i-nodes. (4294967295 bytes)

              crc    The new (SVR4) portable format with a checksum added.

              tar    The old tar format. (8589934591 bytes)

              ustar  The  POSIX.1  tar  format.   Also  recognizes GNU tar ar-
                     chives, which are similar but not identical.  (8589934591
                     bytes)

              hpbin  The  obsolete  binary  format  used by HPUX's cpio (which
                     stores device files differently).

              hpodc  The portable format used by HPUX's cpio (which stores de-
                     vice files differently).
```
The GNU cpio 2.17 texinfo-file says:
> By default, cpio creates binary format archives, for compatibility with
older cpio programs.

and
> When extracting from archives, cpio automatically
recognizes which kind of archive it is reading and can read archives
created on machines with a different byte-order.

**Comment by genivia-inc** [comment]
Support for CPIO `odc`, `newc`, and `crc` is included, as well as `tar`, `ustar` and `pax` are supported. The obsolete `bin` format and the HP-specific binary formats are not supported. I did not see any compelling reason to do so when I read about the current state of CPIO usage.

**Comment by genivia-inc** [comment]
My machine does not even support `bin`. The man page states that `odc` is the default. I am pretty sure that CPIO default `bin` is obsolete and should be avoided.

**Comment by htgoebel** [comment]
I agree that there is not much use in supporting an outdated format, esp. given the state of cpio usage. Anyhow binary format is still the default format of GNU cpio 2.13 (from 2017).

Taging this as enhancement is fine for me, I have no pressing need to get this implemented.

**Comment by genivia-inc** [comment]
I think that adding `bin` support is fine, just in case to add, so why not. Have you looked into this perhaps as a future pull request?

**Comment by htgoebel** [comment]
> Have you looked into this perhaps as a future pull request?

No, sorry. Please do not expect a pull-request for this from me. I'm not a C programmer.

**Comment by genivia-inc** [comment]
> No, sorry. Please do not expect a pull-request for this from me. I'm not a C programmer.

No problem. Happy to get some feedback.

**Comment by genivia-inc** [comment]
After searching for the elusive CPIO `bin` format spec, I have not been able yet to find it. This old binary format appears to be referred to as the original PWB/UNIX 1.0 format I believe.

https://manpages.debian.org/testing/libarchive-dev/cpio.5.en.html

Your legacy CPIO file has no identifying magic number as far as I can tell:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/104774205-44e23480-5744-11eb-8e53-808a96b98598.png">

Without a magic number it will not be possible the detect this format to expand and search it.

Note that the `odc` format is also a binary format. The magic number is `070707`. This format is supported by ugrep.

The `newc` format is non-binary, ASCII-based. It has magic number `070701`. The `newc+crc` format has magic number `070702`. Both are supported by ugrep.
