### ISSUE TITLE
Mention in README.md that ugrep can be installed with homebrew on Linux

### ISSUE THREAD

**Issue by sidahmed-malaoui** [Genivia/ugrep#96]
I, personally, didn't know that Homebrew works in Linux too, because almost every github repository I met, mentions Homebrew for MacOS only.

It will be awesome if you mention that this package can be installed on MacOS and **Linux** using Homebrew, by changing README.md file.

PS : Thank you for this wonderful tool.

**Comment by genivia-inc** [comment]
Thank you for your feedback. The README is updated.
