### ISSUE TITLE
ugrep -Q with --pager options clash: core dump "double free detected in tcache 2"

### ISSUE THREAD

**Issue by htgoebel** [Genivia/ugrep#99]
`ugrep -Q --pager` crashes with "afree(): double free detected in tcache 2".
- after prssing the first character to be searched
- immediately when run from an empty directory
- immediately when passed an empty directory as argument

* Doesn't crash when `--pager´ is not passed
* Also crashes when configured with `--enable-pager` and `--pager` not passed.
* When running under valgrind, I could not reproduce the error - anyhow this might be caused by me not having *any* experience with valgrind.
* With my very limited knowledge about gdb, I tracked this down to "Query::execute (fd=6) at query.cpp:1659", which reads: 
  ```
     fclose(output);
  ```
    When out-commending this line I, the error vanished.

Please let my know when I sould test some patch.

#### How to reproduce
```
mkdir xxxx
cd xxxx
/path/to/ugrep -Q --pager  # → crash "free(): double free detected in tcache 2"
export MALLOC_CHECK_=1
/path/to/ugrep -Q --pager  # → crash "free(): invalid pointer"
```

#### Environment
ugrep 3.1.3 x86_64-unknown-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
on GNU guix

**Comment by genivia-inc** [comment]
The `--pager` and `-Q` options are mutually exclusive. Perhaps internally that is not fully checked so the pipe to the pager is still closed, which will obviously fail as there is no pager.

- `-Q` should override `--pager`.
- `-Q` and `--pager` should produce an error.

The first option is probably better, because the `.ugrep` configuration may have set `--pager` and in that case `-Q` will not work.

**Comment by genivia-inc** [comment]
Adding this to `src/ugrep.cpp` line 4968 before calling `terminal()` disables `--pager` when `-Q` is used:
~~~
  // --query: override --pager
  if (flag_query > 0)
    flag_pager = NULL;
~~~

**Comment by genivia-inc** [comment]
Version v3.1.4 is released. This update should correct the problem.

**Comment by htgoebel** [comment]
Works like a charm. Thanks for the quick fix :-) ugrep should show up in GNU Guix in two weeks latest.

> The first option is probably better, because the .ugrep configuration may have set --pager and in that case -Q will not work.

+1
